
# =============================================================================
# X. PREGUNTAS Y REPASO
T.ap("bX", "X. Preguntas de examen y repaso", donde(
  "Para cerrar el tema: las **preguntas de examen** que incluye la guía M101 (con su respuesta) y el **repaso por bloques**. En la pestaña de test del bloque encontrarás el resto de preguntas de este tema, y el **Test Constitución** entrena los artículos 1 a 55.",
  ["1 Preguntas de la guía M101", "2 Repaso por bloques"]))

T.ap("s49", "X.1 Preguntas de la guía M101", f"""
La guía del módulo incluye estas dos preguntas de examen. Intenta responder **antes de mirar la solución**.

**1.** ¿En qué parte de la Constitución Española (en adelante CE) se regula la nacionalidad española?
a) En el Título Preliminar. · b) En el Preámbulo. · c) En el Título Primero. · d) En el Título Segundo.

*Respuesta de la guía: **c)**. Se regula en el **art. 11**, que está en el **capítulo primero del Título I**.* {c("CE", "a11", "La nacionalidad española se adquiere, se conserva y se pierde de acuerdo con lo establecido por la ley")}

**2.** De acuerdo con su Preámbulo, ¿quién ratifica la Constitución Española de 1978?
a) El Rey. · b) El pueblo español. · c) Las Cortes Generales. · d) El Gobierno.

*Respuesta de la guía: **b)**. El Preámbulo cierra con la fórmula* {c("CE", "preambulo", "las Cortes aprueban y el pueblo español ratifica")}*: las Cortes **aprueban**, el pueblo **ratifica**.*
""", 2)

T.ap("s50", "X.2 Repaso por bloques", f"""
{tabla(["Bloque", "Lo imprescindible"], [
  ["**I · Fechas**", "Aprobación **31-10-1978** (Cortes) · ratificación **6-12-1978** (pueblo) · sanción y promulgación **27-12-1978** · BOE y entrada en vigor **29-12-1978**. Reformas: **13.2 (1992)**, **135 (2011)**, **49 (2024)**, **69.3 (2026)**."],
  ["**II · Estructura**", "Dogmática **1-55** / orgánica **56-169** · 11 títulos · **169** artículos · disposiciones **4-9-1-1** · Título I: **10 | 11-13 | 14 | 15-29 | 30-38 | 39-52 | 53-54 | 55**."],
  ["**III · Contenido**", "De qué trata cada artículo del 1 al 55 (→ Test Constitución). Estructura democrática: arts. **6, 7, 36 y 52**. Art. **9.3**: siete garantías."],
  ["**IV · Niveles**", "Sección 1.ª: **todas** las garantías · art. 14: todas menos LO · sección 2.ª: vinculan, ley e inconstitucionalidad (**amparo solo 30.2**) · cap. III: **informan**."],
  ["**V · Garantías**", "LO: **15-29** (art. 81) · tutela preferente y sumaria: **14-29** · amparo: **14-29 + 30.2** · Defensor: **Título I** · inconstitucionalidad y vinculación: **cap. II (14-38)**."],
  ["**VI · Suspensión**", "Alarma: **Gobierno**, **15 días**, sin suspensión · excepción: **Gobierno + autorización del Congreso**, **30 (+30)** · sitio: **Congreso, m. absoluta**, a propuesta del Gobierno. **17.3** solo en sitio."],
  ["**VII · TC**", "**12** (4+4+2+2) · **9 años**, tercios cada 3 · Presidente **3 años** · **15 años** de ejercicio · amparo **3 meses/20 días/30 días** · inconstitucionalidad **3 meses**."],
  ["**VIII · Defensor**", "Alto comisionado de las Cortes · **3/5 + 3/5** (o m. absoluta Senado) · **5 años** · **2 adjuntos** · queja **1 año** · sumaria e informal."],
  ["**IX · Reforma**", "Iniciativa **87.1 y 87.2** (no popular) · **167**: 3/5, paritaria, m. absoluta Senado + 2/3 Congreso, referéndum si **1/10 en 15 días** · **168**: 2/3, disolución, 2/3, referéndum obligatorio · no se inicia en guerra ni estados del 116."]])}

{ir("#/ce/test", "🧭 Hacer el Test Constitución")} {ir("#/ce/organigrama", "🗺 Organigrama")} {ir("#/ce/texto", "📜 Constitución completa")}

{resumen([
  "La Constitución es la **única norma** en que se estudia la **estructura y el contenido artículo por artículo**.",
  "**Los niveles de protección** del Título I son la clave: **cuadro IV.2**.",
  "**Suspensión (art. 55)**: dominar quién declara, cuánto dura y qué derechos se pueden suspender.",
  "**TC, Defensor y reforma**: mayorías, plazos y quién interpone cada recurso."], "Siguiente: XI. Cronología e hitos")}
""", 2)

# =============================================================================
# XI. CRONOLOGÍA E HITOS
T.ap("bXI", "XI. Cronología e hitos", donde(
  "Cierre del tema: las fechas y normas que conviene tener a mano, en orden. Para la jurisprudencia del Tribunal Constitucional se necesita la fuente oficial; se incorporará cuando se aporte.",
  ["1 Línea del tiempo"]))

T.ap("s51", "XI.1 Línea del tiempo", f"""
{tabla(["Fecha", "Hecho", "Por qué importa"], [
  ["**31-10-1978**", "Las **Cortes Generales** aprueban la Constitución en sesión plenaria del Congreso y del Senado", "**Aprobación** (verbo: aprueban)"],
  ["**6-12-1978**", "Referéndum: el **pueblo español** ratifica la Constitución", "**Ratificación**"],
  ["**27-12-1978**", "El **Rey** sanciona y promulga la Constitución ante las Cortes", "**Sanción y promulgación**"],
  ["**29-12-1978**", "**Publicación en el BOE** y **entrada en vigor**", "Entra en vigor el mismo día de su publicación (disposición final)"],
  ["**18-1-1980**", "**LO 2/1980**, de referéndum (BOE 23-1-1980)", "Regula el referéndum constitucional"],
  ["**3-10-1979**", "**LO 2/1979**, del Tribunal Constitucional (BOE 5-10-1979)", "Desarrolla el Título IX"],
  ["**6-4-1981**", "**LO 3/1981**, del Defensor del Pueblo (BOE 7-5-1981)", "Desarrolla el art. 54"],
  ["**1-6-1981**", "**LO 4/1981**, de los estados de alarma, excepción y sitio (BOE 5-6-1981)", "Desarrolla el art. 116"],
  ["**27-8-1992**", "Reforma del **art. 13.2** (BOE 28-8-1992)", "Sufragio **pasivo** municipal"],
  ["**27-9-2011**", "Reforma del **art. 135** (BOE 27-9-2011)", "Estabilidad presupuestaria"],
  ["**15-2-2024**", "Reforma del **art. 49** (BOE 17-2-2024)", "Personas con discapacidad"],
  ["**19-5-2026**", "Reforma del **art. 69.3** (BOE 20-5-2026)", "Islas del Senado: Ibiza y Formentera"]])}

*Fechas de aprobación y ratificación: guía M101. Fechas de las leyes y reformas: texto de cada norma y metadatos del BOE.*
""", 2)

# ---------------------------------------------------------------------------- PREGUNTAS (T.q)
def Q(k, art, cat, q, ops, exp, frags): T.q(k, art, cat, q, ops, exp, frags)
Q("CE", "a11", "Estructura", "¿En qué parte de la Constitución Española se regula la nacionalidad española?", ["En el Título Primero.", "En el Título Preliminar.", "En el Preámbulo.", "En el Título Segundo."],
  "La nacionalidad (art. 11) está en el capítulo primero del **Título I**. El Título preliminar es de principios (arts. 1 a 9), el Preámbulo no tiene artículos y el Título II es de la Corona.", ["La nacionalidad española se adquiere, se conserva y se pierde de acuerdo con lo establecido por la ley"])
Q("CE", "preambulo", "Fechas", "De acuerdo con su Preámbulo, ¿quién ratifica la Constitución Española de 1978?", ["El pueblo español.", "El Rey.", "Las Cortes Generales.", "El Gobierno."],
  "El Preámbulo termina diciendo que las Cortes **aprueban** y el pueblo español **ratifica**. El Rey la sanciona y promulga; el Gobierno no interviene.", ["las Cortes aprueban y el pueblo español ratifica"])
Q("CE", "s1", "Estructura", "La Sección 1.ª del Capítulo segundo del Título I, «De los derechos fundamentales y de las libertades públicas», comprende los artículos:", ["15 a 29.", "14 a 29.", "14 a 38.", "30 a 38."],
  "Es la sección más protegida: arts. **15 a 29**. El art. 14 queda fuera de las secciones; los arts. 30 a 38 son la sección 2.ª; el capítulo II va de 14 a 38.", ["De los derechos fundamentales y de las libertades públicas"])
Q("CE", "ctercero", "Estructura", "¿Qué capítulo del Título I se denomina «De los principios rectores de la política social y económica»?", ["El capítulo tercero.", "El capítulo segundo.", "El capítulo cuarto.", "El capítulo primero."],
  "Es el **capítulo tercero** (arts. 39 a 52). El segundo es «Derechos y libertades», el cuarto «De las garantías…» y el primero «De los españoles y los extranjeros».", ["De los principios rectores de la política social y económica"])
Q("CE", "a14", "Estructura", "El artículo 14 de la Constitución (igualdad ante la ley) se encuentra:", ["En el capítulo segundo del Título I, fuera de las secciones primera y segunda.", "En la sección primera del capítulo segundo del Título I.", "En el capítulo primero del Título I.", "En el Título preliminar."],
  "El art. 14 está dentro del capítulo segundo pero **fuera de las secciones**: la sección 1.ª empieza en el art. 15.", ["Los españoles son iguales ante la ley"])
Q("CE", "a1", "Contenido", "Según el artículo 1.1 de la Constitución, los valores superiores del ordenamiento jurídico son:", ["La libertad, la justicia, la igualdad y el pluralismo político.", "La dignidad de la persona, la libertad, la justicia y la paz social.", "La libertad, la igualdad, la fraternidad y la justicia.", "La justicia, la seguridad, la igualdad y la solidaridad."],
  "Son cuatro: libertad, justicia, igualdad y pluralismo político. La dignidad de la persona es el fundamento del orden político (art. 10.1).", ["la libertad, la justicia, la igualdad y el pluralismo político"])
Q("CE", "a3", "Contenido", "¿Qué artículo de la Constitución declara que el castellano es la lengua española oficial del Estado?", ["El artículo 3.", "El artículo 2.", "El artículo 4.", "El artículo 5."],
  "El art. 3 regula la lengua. El 2 trata de la unidad y la autonomía, el 4 de la bandera y el 5 de la capital.", ["El castellano es la lengua española oficial del Estado"])
Q("CE", "a17", "Contenido", "Según el artículo 17.2 de la Constitución, el plazo máximo de la detención preventiva es de:", ["Setenta y dos horas.", "Veinticuatro horas.", "Cuarenta y ocho horas.", "Diez días."],
  "El detenido debe ser puesto en libertad o a disposición judicial como máximo en **setenta y dos horas**. Los diez días son la detención gubernativa en el estado de excepción (LO 4/1981).", ["en el plazo máximo de setenta y dos horas"])
Q("CE", "a36", "Contenido", "¿A cuál de estas organizaciones exige expresamente la Constitución una estructura interna y un funcionamiento democráticos?", ["A los Colegios Profesionales.", "A las Fuerzas Armadas.", "A las Universidades.", "A las fundaciones."],
  "Lo exigen los arts. 6 (partidos), 7 (sindicatos y asociaciones empresariales), 36 (Colegios Profesionales) y 52 (organizaciones profesionales).", ["La estructura interna y el funcionamiento de los Colegios deberán ser democráticos"])
Q("CE", "a81", "Garantías", "Según el artículo 81.1 de la Constitución, son leyes orgánicas las relativas al desarrollo de:", ["Los derechos fundamentales y de las libertades públicas.", "Todos los derechos del Título I.", "Los principios rectores de la política social y económica.", "Los derechos y deberes de los ciudadanos de la sección 2.ª."],
  "Solo el desarrollo de los **derechos fundamentales y libertades públicas** (sección 1.ª, arts. 15 a 29) exige ley orgánica; el resto del Título I, ley ordinaria.", ["desarrollo de los derechos fundamentales y de las libertades públicas"])
Q("CE", "a81", "Garantías", "La aprobación, modificación o derogación de las leyes orgánicas exige:", ["Mayoría absoluta del Congreso, en una votación final sobre el conjunto del proyecto.", "Mayoría de tres quintos del Congreso y del Senado.", "Mayoría simple del Congreso.", "Mayoría de dos tercios del Congreso."],
  "Art. 81.2: **mayoría absoluta del Congreso** en votación final sobre el conjunto.", ["mayoría absoluta del Congreso, en una votación final sobre el conjunto del proyecto"])
Q("CE", "a53", "Garantías", "¿Para qué derechos prevé el art. 53.2 de la Constitución la tutela ante los tribunales ordinarios por un procedimiento basado en los principios de preferencia y sumariedad?", ["Los del artículo 14 y la Sección primera del Capítulo segundo.", "Todos los del Capítulo segundo.", "Todos los del Título I.", "Los de la Sección segunda del Capítulo segundo."],
  "El art. 53.2 cubre el **art. 14 y la sección 1.ª** del capítulo II (arts. 14 a 29). No todo el capítulo II (vinculan, art. 53.1), ni todo el Título I (Defensor, art. 54).", ["Cualquier ciudadano podrá recabar la tutela de las libertades y derechos reconocidos en el artículo 14 y la Sección primera del Capítulo segundo"])
Q("CE", "a53", "Garantías", "El recurso de amparo ante el Tribunal Constitucional es aplicable, según el art. 53.2 de la Constitución, además de a los derechos del artículo 14 y la Sección primera del Capítulo segundo, a:", ["La objeción de conciencia reconocida en el artículo 30.", "El derecho a la propiedad privada y a la herencia.", "El derecho al trabajo.", "El derecho a la protección de la salud."],
  "Solo la **objeción de conciencia del art. 30.2** de la sección 2.ª tiene amparo. La propiedad (33) y el trabajo (35) son de la sección 2.ª sin amparo; la salud (43) es del capítulo III.", ["Este último recurso será aplicable a la objeción de conciencia reconocida en el artículo 30"])
Q("CE", "a53", "Garantías", "Según el artículo 53.3 de la Constitución, los principios reconocidos en el Capítulo tercero:", ["Solo podrán ser alegados ante la Jurisdicción ordinaria de acuerdo con lo que dispongan las leyes que los desarrollen.", "Podrán ser alegados directamente ante el Tribunal Constitucional mediante recurso de amparo.", "Vinculan a todos los poderes públicos con la misma eficacia que los derechos del capítulo segundo.", "Solo pueden regularse por ley orgánica."],
  "Los principios rectores **informan** la legislación, la práctica judicial y la actuación de los poderes públicos, pero solo se alegan ante la jurisdicción ordinaria según las leyes que los desarrollen.", ["Sólo podrán ser alegados ante la Jurisdicción ordinaria de acuerdo con lo que dispongan las leyes que los desarrollen"])
Q("CE", "a54", "Defensor del Pueblo", "El Defensor del Pueblo, según el artículo 54 de la Constitución, es:", ["Alto comisionado de las Cortes Generales, designado por éstas para la defensa de los derechos comprendidos en el Título I.", "Alto comisionado del Gobierno, designado por el Consejo de Ministros.", "Órgano del Poder Judicial para la defensa de los derechos fundamentales.", "Alto comisionado del Congreso de los Diputados, designado para defender los derechos de la sección 1.ª."],
  "Es comisionado de las **Cortes Generales** (no del Gobierno ni del Congreso solo) y defiende **todos los derechos del Título I**, no solo los de la sección 1.ª.", ["alto comisionado de las Cortes Generales, designado por éstas para la defensa de los derechos comprendidos en este Título"])
Q("LOTC", "acuarentaycuatro", "Garantías", "El plazo para interponer el recurso de amparo frente a una violación originada en un acto u omisión de un órgano judicial es de:", ["30 días, a partir de la notificación de la resolución recaída en el proceso judicial.", "20 días, a partir de la notificación de la resolución recaída en el proceso judicial.", "Tres meses, desde que la resolución sea firme.", "Diez días, a partir de la publicación de la sentencia."],
  "Art. 44.2 LOTC: **30 días**. Los 20 días son para el Gobierno y los órganos ejecutivos de las CCAA (art. 43) y los 3 meses para las Cortes y Asambleas (art. 42).", ["El plazo para interponer el recurso de amparo será de 30 días"])
Q("LOTC", "acuarentaytres", "Garantías", "El plazo para interponer recurso de amparo frente a violaciones originadas por actos del Gobierno o de sus autoridades o funcionarios, una vez agotada la vía judicial, es de:", ["Veinte días siguientes a la notificación de la resolución recaída en el previo proceso judicial.", "Treinta días desde la notificación de la resolución.", "Tres meses desde que sea firme.", "Dos meses desde la publicación del acto."],
  "Art. 43.2 LOTC: **veinte días**. Contra órgano judicial: 30 días (art. 44). Contra decisiones de Cortes o Asambleas sin valor de ley: 3 meses (art. 42).", ["veinte días siguientes a la notificación de la resolución recaída en el previo proceso judicial"])
Q("LOTC", "acuarentaydos", "Garantías", "Las decisiones o actos sin valor de ley de las Cortes que violen derechos susceptibles de amparo podrán ser recurridas en amparo dentro del plazo de:", ["Tres meses desde que, con arreglo a las normas internas de las Cámaras, sean firmes.", "Veinte días desde su notificación.", "Treinta días desde su publicación.", "Un mes desde que sean firmes."],
  "Art. 42 LOTC: **tres meses** desde que sean firmes.", ["tres meses desde que, con arreglo a las normas internas de las Cámaras o Asambleas, sean firmes"])
Q("CE", "a162", "Garantías", "¿Quién NO está legitimado para interponer el recurso de inconstitucionalidad según el artículo 162.1.a) de la Constitución?", ["El Ministerio Fiscal.", "El Defensor del Pueblo.", "Cincuenta Diputados.", "El Presidente del Gobierno."],
  "Están legitimados el Presidente del Gobierno, el Defensor del Pueblo, 50 Diputados, 50 Senadores y los órganos ejecutivos y, en su caso, las Asambleas de las CCAA. El Ministerio Fiscal solo puede interponer amparo.", ["el Presidente del Gobierno, el Defensor del Pueblo, 50 Diputados, 50 Senadores"])
Q("LOTC", "atreintaytres", "Garantías", "El recurso de inconstitucionalidad se formulará dentro del plazo de:", ["Tres meses a partir de la publicación de la ley, disposición o acto con fuerza de ley impugnado.", "Dos meses a partir de su publicación.", "Seis meses a partir de su entrada en vigor.", "Un año a partir de su publicación."],
  "Art. 33.1 LOTC: **tres meses** desde la publicación (nueve meses en los casos del art. 33.2).", ["tres meses a partir de la publicación de la Ley, disposición o acto con fuerza de Ley impugnado"])
Q("CE", "a116", "Suspensión", "¿Quién declara el estado de sitio, según el artículo 116.4 de la Constitución?", ["El Congreso de los Diputados, por mayoría absoluta y a propuesta exclusiva del Gobierno.", "El Gobierno, mediante decreto acordado en Consejo de Ministros.", "El Gobierno, previa autorización del Congreso de los Diputados.", "Las Cortes Generales en sesión conjunta, por mayoría de tres quintos."],
  "El **Congreso** declara el sitio por **mayoría absoluta**, a propuesta **exclusiva** del Gobierno. El Gobierno declara la alarma (decreto) y la excepción (con autorización previa).", ["declarado por la mayoría absoluta del Congreso de los Diputados, a propuesta exclusiva del Gobierno"])
Q("CE", "a116", "Suspensión", "El estado de alarma será declarado por el Gobierno por un plazo máximo de:", ["Quince días, sin cuya autorización del Congreso no podrá ser prorrogado dicho plazo.", "Treinta días, prorrogables por otro plazo igual.", "Quince días, prorrogables libremente por el Gobierno.", "El que determine el Congreso de los Diputados."],
  "Alarma: **quince días**, y la prórroga necesita **autorización del Congreso**. Los 30 días prorrogables son de la excepción; la duración fijada por el Congreso, del sitio.", ["por un plazo máximo de quince días", "sin cuya autorización no podrá ser prorrogado dicho plazo"])
Q("CE", "a116", "Suspensión", "El estado de excepción:", ["Lo declara el Gobierno previa autorización del Congreso, por un plazo máximo de treinta días prorrogables por otro plazo igual.", "Lo declara el Congreso por mayoría absoluta, a propuesta del Gobierno.", "Lo declara el Gobierno dando cuenta al Congreso, por un plazo máximo de quince días.", "Lo declara el Gobierno sin intervención del Congreso, por treinta días no prorrogables."],
  "Excepción: **Gobierno con autorización previa del Congreso**, hasta **30 días** + otro plazo igual con los mismos requisitos.", ["previa autorización del Congreso de los Diputados", "que no podrá exceder de treinta días, prorrogables por otro plazo igual"])
Q("CE", "a55", "Suspensión", "¿Qué apartado de qué artículo queda exceptuado de la suspensión en el estado de excepción, aunque sí puede suspenderse en el de sitio?", ["El apartado 3 del artículo 17.", "El apartado 2 del artículo 18.", "El apartado 2 del artículo 17.", "El apartado 2 del artículo 28."],
  "El 55.1 exceptúa el **17.3** (garantías del detenido) en el estado de excepción; en el de sitio sí puede suspenderse (art. 32.3 LO 4/1981).", ["Se exceptúa de lo establecido anteriormente el apartado 3 del artículo 17 para el supuesto de declaración de estado de excepción"])
Q("CE", "a55", "Suspensión", "¿Cuál de estos derechos puede ser suspendido cuando se declare el estado de excepción o de sitio, según el artículo 55.1 de la Constitución?", ["El derecho de huelga (art. 28.2).", "El derecho a la vida (art. 15).", "La libertad ideológica y religiosa (art. 16).", "El derecho a la educación (art. 27)."],
  "El 55.1 enumera 17, 18.2 y 18.3, 19, 20.1.a) y d) y 20.5, 21, 28.2 y 37.2. Ni la vida, ni la libertad ideológica ni la educación están en la lista.", ["28, apartado 2"])
Q("CE", "a116", "Suspensión", "Mientras estén declarados los estados de alarma, excepción o sitio:", ["No podrá procederse a la disolución del Congreso.", "Podrá disolverse el Congreso si lo pide el Gobierno.", "Queda suspendido el funcionamiento de las Cámaras.", "Se suspende el principio de responsabilidad del Gobierno."],
  "Art. 116.5: **no puede disolverse el Congreso** y no se interrumpe el funcionamiento de las Cámaras ni de los demás poderes; art. 116.6: no se modifica la responsabilidad del Gobierno y sus agentes.", ["No podrá procederse a la disolución del Congreso"])
Q("CE", "a55", "Suspensión", "Según el artículo 55.2 de la Constitución, una ley orgánica podrá determinar los casos en que, de forma individual, pueden ser suspendidos para personas determinadas los derechos de los artículos:", ["17.2, 18.2 y 18.3.", "17, 19 y 21.", "18.1, 20 y 28.2.", "15, 16 y 17.1."],
  "La suspensión **individual** (bandas armadas y elementos terroristas) afecta a **17.2, 18.2 y 18.3**, con intervención judicial y control parlamentario.", ["los derechos reconocidos en los artículos 17, apartado 2, y 18, apartados 2 y 3"])
Q("CE", "a159", "Tribunal Constitucional", "El Tribunal Constitucional se compone de 12 miembros nombrados por el Rey; de ellos, a propuesta del Gobierno:", ["Dos.", "Cuatro.", "Tres.", "Seis."],
  "Art. 159.1 CE: 4 a propuesta del Congreso, 4 del Senado, **2 del Gobierno** y 2 del Consejo General del Poder Judicial.", ["dos a propuesta del Gobierno, y dos a propuesta del Consejo General del Poder Judicial"])
Q("CE", "a159", "Tribunal Constitucional", "Los miembros del Tribunal Constitucional serán designados por un período de:", ["Nueve años y se renovarán por terceras partes cada tres.", "Seis años y se renovarán por mitades cada tres.", "Nueve años y se renovarán por mitades cada cuatro y medio.", "Doce años sin renovación."],
  "Art. 159.3: **nueve años**, renovación **por terceras partes cada tres**.", ["nueve años y se renovarán por terceras partes cada tres"])
Q("CE", "a160", "Tribunal Constitucional", "El Presidente del Tribunal Constitucional es nombrado:", ["Entre sus miembros por el Rey, a propuesta del Tribunal en pleno, por tres años.", "Por el Rey, a propuesta del Gobierno, por nueve años.", "Por el Congreso de los Diputados, por mayoría de tres quintos.", "Por el Consejo General del Poder Judicial, por cinco años."],
  "Art. 160: lo nombra el **Rey**, **entre sus miembros**, a propuesta del **Pleno del Tribunal**, por **tres años**.", ["nombrado entre sus miembros por el Rey, a propuesta del mismo Tribunal en pleno y por un período de tres años"])
Q("CE", "a159", "Tribunal Constitucional", "Los miembros del Tribunal Constitucional deberán ser nombrados entre juristas de reconocida competencia con:", ["Más de quince años de ejercicio profesional.", "Más de diez años de ejercicio profesional.", "Más de veinte años de ejercicio profesional.", "Más de cinco años de ejercicio profesional."],
  "Art. 159.2: **más de quince años** de ejercicio profesional (Magistrados y Fiscales, Profesores de Universidad, funcionarios públicos y Abogados).", ["más de quince años de ejercicio profesional"])
Q("CE", "a164", "Tribunal Constitucional", "Las sentencias del Tribunal Constitucional tienen el valor de cosa juzgada:", ["A partir del día siguiente de su publicación, y no cabe recurso alguno contra ellas.", "Desde la fecha de la sentencia, y cabe recurso ante el Pleno.", "A partir del mes siguiente a su publicación.", "Desde su notificación a las partes, con recurso de súplica."],
  "Art. 164.1: se publican en el BOE con los votos particulares, tienen valor de cosa juzgada **desde el día siguiente a su publicación** y **no cabe recurso alguno**.", ["valor de cosa juzgada a partir del día siguiente de su publicación y no cabe recurso alguno contra ellas"])
Q("CE", "a163", "Tribunal Constitucional", "¿Quién plantea la cuestión de inconstitucionalidad ante el Tribunal Constitucional?", ["Un órgano judicial que considere que una norma con rango de ley aplicable al caso, de cuya validez dependa el fallo, pueda ser contraria a la Constitución.", "Cualquier ciudadano que se considere perjudicado por una ley.", "El Defensor del Pueblo, de oficio.", "El Gobierno, cuando una ley autonómica invada sus competencias."],
  "Art. 163 CE: la plantea el **órgano judicial** (en el proceso, de oficio o a instancia de parte, una vez concluso y dentro del plazo para dictar sentencia: art. 35 LOTC).", ["Cuando un órgano judicial considere"])
Q("CE", "a161", "Tribunal Constitucional", "Cuando el Gobierno impugna ante el Tribunal Constitucional disposiciones y resoluciones adoptadas por los órganos de las Comunidades Autónomas, la impugnación produce la suspensión, pero el Tribunal deberá ratificarla o levantarla en un plazo no superior a:", ["Cinco meses.", "Un mes.", "Tres meses.", "Seis meses."],
  "Art. 161.2: **cinco meses**.", ["en un plazo no superior a cinco meses"])
Q("LODP", "asegundo", "Defensor del Pueblo", "Para la elección del Defensor del Pueblo, el Pleno del Congreso designará a quien obtenga:", ["Una votación favorable de las tres quintas partes de sus miembros, ratificada por la misma mayoría del Senado en un plazo máximo de veinte días.", "Mayoría simple del Congreso, ratificada por el Senado en un mes.", "Dos tercios del Congreso y mayoría absoluta del Senado.", "Mayoría absoluta de cada Cámara reunidas en sesión conjunta."],
  "Art. 2.4 LO 3/1981: **3/5 del Congreso** y ratificación, en **veinte días**, por la misma mayoría del Senado. Si no se alcanzan, la Comisión Mixta formula **nuevas propuestas en el plazo máximo de un mes** y, una vez lograda la mayoría de 3/5 en el Congreso, basta la **mayoría absoluta del Senado** (art. 2.5).", ["tres quintas partes de los miembros del Congreso", "en un plazo máximo de veinte días"])
Q("LODP", "asegundo", "Defensor del Pueblo", "El Defensor del Pueblo será elegido por las Cortes Generales para un periodo de:", ["Cinco años.", "Cuatro años.", "Seis años.", "Nueve años."],
  "Art. 2.1 LO 3/1981: **cinco años**.", ["para un periodo de cinco años"])
Q("LODP", "aquince", "Defensor del Pueblo", "Toda queja ante el Defensor del Pueblo se presentará en el plazo máximo de:", ["Un año, contado a partir del momento en que se tuviera conocimiento de los hechos.", "Seis meses desde la notificación del acto.", "Dos meses desde que se agote la vía administrativa.", "Tres años desde que ocurran los hechos."],
  "Art. 15.1 LO 3/1981: **un año** desde que se conocen los hechos; la queja es gratuita y sin abogado ni procurador.", ["en el plazo máximo de un año"])
Q("LODP", "aoctavo", "Defensor del Pueblo", "El Defensor del Pueblo estará auxiliado por:", ["Un Adjunto Primero y un Adjunto Segundo.", "Tres Adjuntos.", "Un único Adjunto.", "Cuatro Adjuntos, uno por cada grupo parlamentario."],
  "Art. 8.1 LO 3/1981: **dos** Adjuntos, a los que nombra y separa él previa conformidad de las Cámaras.", ["Adjunto Primero y un Adjunto Segundo"])
Q("CE", "a166", "Reforma", "La iniciativa de reforma constitucional se ejercerá en los términos previstos en los apartados 1 y 2 del artículo 87. Por tanto, NO puede ejercerla:", ["La iniciativa popular.", "El Gobierno.", "Las Asambleas de las Comunidades Autónomas.", "El Senado."],
  "El art. 166 remite a los apartados 1 y 2 del art. 87 (Gobierno, Congreso, Senado y Asambleas autonómicas); la **iniciativa popular** es el 87.3 y queda fuera.", ["apartados 1 y 2 del artículo 87"])
Q("CE", "a167", "Reforma", "Según el artículo 167 de la Constitución, los proyectos de reforma constitucional deberán ser aprobados por:", ["Una mayoría de tres quintos de cada una de las Cámaras.", "Una mayoría de dos tercios de cada una de las Cámaras.", "Mayoría absoluta del Congreso.", "Mayoría de tres quintos del Congreso y mayoría simple del Senado."],
  "Art. 167.1: **3/5 de cada Cámara**. Los 2/3 son del art. 168 (y del Congreso en el 167.2).", ["una mayoría de tres quintos de cada una de las Cámaras"])
Q("CE", "a167", "Reforma", "Aprobada la reforma por las Cortes Generales por el procedimiento del art. 167, será sometida a referéndum para su ratificación cuando así lo soliciten:", ["Una décima parte de los miembros de cualquiera de las Cámaras, dentro de los quince días siguientes a su aprobación.", "Una quinta parte de los miembros de cualquiera de las Cámaras, dentro del mes siguiente.", "Cincuenta Diputados o cincuenta Senadores, dentro de los treinta días siguientes.", "El Gobierno, dentro de los quince días siguientes."],
  "Art. 167.3: referéndum **facultativo**: **1/10** de los miembros de cualquier Cámara, en **15 días**.", ["una décima parte de los miembros de cualquiera de las Cámaras"])
Q("CE", "a168", "Reforma", "Cuando se propusiere la revisión total de la Constitución o una parcial que afecte al Título preliminar, se procederá a la aprobación del principio por mayoría de:", ["Dos tercios de cada Cámara y a la disolución inmediata de las Cortes.", "Tres quintos de cada Cámara y al referéndum facultativo.", "Mayoría absoluta de cada Cámara y a la convocatoria de elecciones.", "Dos tercios del Congreso y mayoría absoluta del Senado."],
  "Art. 168.1: **2/3 de cada Cámara** y **disolución inmediata** de las Cortes; las nuevas Cámaras ratifican y aprueban el texto por 2/3 y se somete a **referéndum obligatorio**.", ["mayoría de dos tercios de cada Cámara, y a la disolución inmediata de las Cortes"])
Q("CE", "a168", "Reforma", "El procedimiento agravado de reforma del art. 168 se aplica cuando la reforma afecte:", ["Al Título preliminar, al Capítulo segundo, Sección primera del Título I, o al Título II.", "Al Título I completo y al Título II.", "A los artículos 14 a 38 y al Título VIII.", "Al Título preliminar, al Título I y al Título X."],
  "Solo se protege con el 168 la **revisión total**, el **Título preliminar**, la **sección 1.ª del capítulo II del Título I** (15-29, no el 14) y el **Título II** (la Corona).", ["al Título preliminar, al Capítulo segundo, Sección primera del Título I, o al Título II"])
Q("CE", "a169", "Reforma", "No podrá iniciarse la reforma constitucional:", ["En tiempo de guerra o de vigencia de alguno de los estados previstos en el artículo 116.", "Durante los seis meses anteriores a unas elecciones generales.", "Mientras esté disuelto el Congreso.", "En los dos años siguientes a otra reforma."],
  "Art. 169: ni en **tiempo de guerra** ni durante los estados de **alarma, excepción o sitio** (art. 116).", ["en tiempo de guerra o de vigencia de alguno de los estados previstos en el artículo 116"])
Q("CE", "a13", "Reforma", "La reforma constitucional de 1992 modificó el artículo 13.2 para:", ["Reconocer a los extranjeros, por reciprocidad, el derecho de sufragio activo y pasivo en las elecciones municipales.", "Establecer el principio de estabilidad presupuestaria.", "Sustituir el término «disminuidos» por «personas con discapacidad».", "Crear una circunscripción propia en el Senado para la isla de Formentera."],
  "La reforma de 1992 (art. 13.2) añadió el sufragio **pasivo** en las municipales. La de 2011 (135) es la estabilidad presupuestaria; la de 2024 (49), la discapacidad; la de 2026 (69.3), las islas del Senado.", ["sufragio activo y pasivo en las elecciones municipales"])

# --- Preguntas oficiales GACE 2018 (módulo M107; texto del cuestionario y respuesta de la plantilla: 1 → A, 2 → D) ----------
T.q("CE", "a168", "Reforma", "De acuerdo con el artículo 168 de la Constitución Española de 1978 se debe someter a referéndum una reforma de la Constitución que afectase al siguiente artículo:",
    ["El artículo 3 que señala que «El castellano es la lengua oficial del Estado».", "El artículo 11.2 que señala que «Ningún español de origen podrá ser privado de su nacionalidad».", "El artículo 12 que señala que «Los españoles son mayores de edad a los 18 años».", "El artículo 43.1 que señala que «Se reconoce el derecho a la protección de la salud»."],
    "Respuesta a) (plantilla oficial). El art. 168 se aplica a la revisión total o a la parcial que afecte al **Título preliminar**, a la **sección 1.ª del capítulo II del Título I** o al **Título II**: el art. 3 está en el Título preliminar. Los arts. 11 y 12 están en el capítulo I del Título I y el 43 en el capítulo III: se reformarían por el art. 167.",
    ["Título preliminar"])
T.Q[-1]["real"] = "GACE 2018 · pregunta oficial (plantilla: a)"
T.q("CE", "a20", "Contenido", "De acuerdo con el artículo 20 de la Constitución Española, ¿podría acordarse el secuestro de publicaciones, grabaciones u otros medios de información?",
    ["Sólo en virtud de resolución judicial.", "En ningún caso, por suponer una violación de las libertades reconocidas en el artículo 20 de la Constitución.", "Únicamente cuando se vulnere el derecho a la protección de la juventud y de la infancia.", "Sí, en virtud de resolución del Ministerio de la Presidencia."],
    "Respuesta de la plantilla oficial: «Sólo en virtud de resolución judicial». El art. 20.5 dice: «Sólo podrá acordarse el **secuestro de publicaciones, grabaciones y otros medios de información en virtud de resolución judicial**». «En ningún caso…» es falsa, porque el 20.5 sí lo permite; «Únicamente cuando se vulnere el derecho a la protección de la juventud y de la infancia» confunde el secuestro con uno de los límites del 20.4; «Sí, en virtud de resolución del Ministerio de la Presidencia» es falsa: no basta una resolución administrativa.",
    ["en virtud de resolución judicial"])
T.Q[-1]["real"] = "GACE 2018 · pregunta oficial (plantilla: d)"
