
# =============================================================================
# PREGUNTAS DE LA ACADEMIA (M104 «Test de repaso» y M105 «Test de tema»).
# Enunciado y opciones literales del documento; la respuesta es la de su clave (M104: tabla final;
# M105: tabla final y respuesta en rojo en las soluciones) y se ha comprobado contra el texto vigente.
# Se marcan con "ac" (filtro «Academia» del test de cada tema) y "t" (tema al que van).
def AC(src, n, tema, k, art, cat, q, ops, ok, exp, frags, aviso=None, retenida=None):
    """ops: opciones en el orden del documento (a, b, c, d); ok: letra de la clave."""
    i = "abcd".index(ok)
    orden = [ops[i]] + [o for j, o in enumerate(ops) if j != i]
    if frags is None:
        T.Q.append({"q": q, "o": orden, "c": 0, "e": "", "cat": cat})
    else:
        T.q(k, art, cat, q, orden, "", frags)
    T.Q[-1]["o"], T.Q[-1]["c"] = list(ops), i          # orden y letra del documento (la app baraja y avisa de la letra original)
    e = f"Solución de la academia ({src} · pregunta {n}). {exp}"
    if aviso: e += f" ⚠ {aviso}"
    T.Q[-1].update({"e": e, "ac": f"{src} · pregunta {n}", "t": tema})
    if retenida: T.Q[-1]["retenida"] = retenida     # se ve en los datos, pero queda fuera del test (premisa o respuesta desfasada)

# ------------------------------------------------------------------ M104 · Test de repaso
M = "M104"
AC(M, 1, 1, "CE", "tpreliminar", "Estructura", "Son características de la Constitución Española:",
   ["Su carácter abierto y de fácil modificación.", "Su poca extensión y su falta de definición de un modelo territorial.", "Su carácter escrito, extenso y rígido en su contenido.", "Su falta de definición del modelo de Estado."], "c",
   "La CE es **escrita**, **extensa** (169 artículos) y **rígida** (Título X: arts. 166 a 169; procedimiento agravado, art. 168).", None)
AC(M, 2, 1, "CE", "a1", "Contenido", "¿Cuáles de los siguientes se propugnan como valores superiores del ordenamiento jurídico español de acuerdo con el artículo 1.1 de la Constitución Española?",
   ["La democracia y el pluralismo político.", "La justicia y la libertad.", "La igualdad y el Estado Social.", "La legalidad y la Nación española."], "b",
   "Art. 1.1 CE: «propugna como valores superiores de su ordenamiento jurídico la libertad, la justicia, la igualdad y el pluralismo político». La democracia, el Estado social, la legalidad y la Nación **no** son valores superiores.", ["la libertad, la justicia, la igualdad y el pluralismo político"])
AC(M, 3, 1, "CE", "a6", "Estructura", "El Título Preliminar de la Constitución Española de 1978 engloba una serie de preceptos entre los que se encuentra el relativo a:",
   ["La regulación sobre la adquisición de la nacionalidad española.", "La naturaleza, funcionamiento y estructura de los partidos políticos.", "La entrada en vigor de la propia Constitución.", "El reconocimiento de los derechos históricos de los territorios forales."], "b",
   "Art. 6 CE (Título Preliminar): «Los partidos políticos expresan el pluralismo político, concurren a la formación y manifestación de la voluntad popular y son instrumento fundamental para la participación política. Su creación y el ejercicio de su actividad son libres dentro del respeto a la Constitución y a la ley. Su estructura interna y funcionamiento deberán ser democráticos.»", ["Su estructura interna y funcionamiento deberán ser democráticos"])
AC(M, 4, 1, "CE", "a8", "Estructura", "El artículo 8 de la CE establece que las Fuerzas Armadas tienen como misión:",
   ["Garantizar la unidad e independencia de España.", "Garantizar la estabilidad e independencia de la Nación.", "Garantizar la soberanía y estabilidad de la Nación.", "Garantizar la soberanía e independencia de España."], "d",
   "Art. 8.1 CE: las Fuerzas Armadas tienen como misión «garantizar la soberanía e independencia de España, defender su integridad territorial y el ordenamiento constitucional».", ["garantizar la soberanía e independencia de España, defender su integridad territorial y el ordenamiento constitucional"])
AC(M, 5, 2, "CE", "a20", "Contenido", "Según la Constitución Española, es un derecho fundamental:",
   ["Derecho a contraer matrimonio con plena igualdad jurídica.", "Derecho a la libertad de cátedra.", "Derecho a la propiedad privada.", "Derecho a la libre elección de profesión u oficio."], "b",
   "Art. 20.1.c CE: «Se reconocen y protegen los derechos: […] c) A la libertad de cátedra.» Está en la sección 1.ª del capítulo II del Título I (arts. 15 a 29), la de los **derechos fundamentales y libertades públicas**; el matrimonio (art. 32), la propiedad (art. 33) y la libre elección de profesión (art. 35) están en la sección 2.ª.", ["A la libertad de cátedra"])
AC(M, 6, 2, "CE", "a29", "Contenido", "De acuerdo a lo establecido en la Constitución Española, el derecho de petición individual y colectivo se considera:",
   ["Un derecho y deber de los ciudadanos.", "Un principio rector de la política social y económica.", "Un derecho fundamental.", "Un valor social para los ciudadanos."], "c",
   "Art. 29.1 CE: «Todos los españoles tendrán el derecho de petición individual y colectiva, por escrito, en la forma y con los efectos que determine la ley.» Está en la sección 1.ª del capítulo II (arts. 15 a 29): es un **derecho fundamental**.", ["derecho de petición individual y colectiva"])
AC(M, 7, 2, "CE", "a53", "Garantías", "El derecho a disfrutar de una vivienda digna y adecuada del artículo 47 de la CE goza de la siguiente garantía constitucional de acuerdo con su artículo 53:",
   ["Ante su vulneración cabe recurso de amparo ante el Tribunal Constitucional.", "Sólo podrá ser alegado ante la Jurisdicción ordinaria de acuerdo con lo que disponga la ley orgánica que lo desarrolle.", "Vincula a todos los poderes públicos.", "Su protección informará la legislación positiva, la práctica judicial y la actuación de los poderes públicos."], "d",
   "Art. 53.3 CE: «El reconocimiento, el respeto y la protección de los principios reconocidos en el Capítulo tercero informarán la legislación positiva, la práctica judicial y la actuación de los poderes públicos.» El art. 47 está en el capítulo III (principios rectores).", ["informarán la legislación positiva, la práctica judicial y la actuación de los poderes públicos"])
AC(M, 8, 2, "CE", "a81", "Garantías", "Según la Constitución Española, ¿cuál de los siguientes derechos y libertades son desarrollados por ley orgánica?",
   ["El derecho a la negociación colectiva laboral entre los representantes de los trabajadores y empresarios.", "El derecho a sindicarse libremente.", "El derecho de los trabajadores y empresarios a adoptar medidas de conflicto colectivo.", "La libertad de empresa en el marco de la economía de mercado."], "b",
   "Art. 81.1 CE: son leyes orgánicas «las relativas al desarrollo de los derechos fundamentales y de las libertades públicas». El derecho a sindicarse (art. 28.1) está en la sección 1.ª; la negociación colectiva (37.1), el conflicto colectivo (37.2) y la libertad de empresa (38) están en la sección 2.ª.", ["las relativas al desarrollo de los derechos fundamentales y de las libertades públicas"])
AC(M, 9, 2, "CE", "a55", "Suspensión", "En función de lo establecido en el artículo 55 de la Constitución Española, indique cuál de estos derechos y deberes NO es susceptible de suspensión en caso de estado de excepción ni de sitio:",
   ["El derecho de reunión (artículo 21 CE).", "El derecho a la libertad (artículo 17 CE).", "El derecho de acceso a cargos públicos (artículo 23 CE).", "El derecho de huelga (artículo 28 CE)."], "c",
   "Art. 55.1 CE: pueden suspenderse los arts. 17, 18.2 y 18.3, 19, 20.1.a) y d) y 20.5, 21, 28.2 y 37.2. **El art. 23 no está en la lista**, luego no es suspendible.", ["artículos 21, 28, apartado 2, y artículo 37, apartado 2"])
AC(M, 10, 2, "CE", "a116", "Suspensión", "De acuerdo con el artículo 116 de la Constitución Española, el estado de sitio será declarado por:",
   ["El Gobierno mediante Decreto acordado en el Consejo de Ministros, dando cuenta al Congreso de los Diputados.", "Mayoría de 3/5 de las Cortes Generales, a propuesta del Gobierno.", "Mayoría absoluta del Congreso de los Diputados, a propuesta exclusiva del Gobierno.", "El Gobierno mediante Decreto acordado en el Consejo de Ministros y previa autorización del Congreso de los Diputados."], "c",
   "Art. 116.4 CE: «El estado de sitio será declarado por la mayoría absoluta del Congreso de los Diputados, a propuesta exclusiva del Gobierno.» (La opción a) es el estado de alarma, 116.2; la d), el de excepción, 116.3.)", ["declarado por la mayoría absoluta del Congreso de los Diputados, a propuesta exclusiva del Gobierno"])
AC(M, 11, 2, "LODP", "aquince", "Defensor del Pueblo", "De acuerdo con la Ley Orgánica 3/1981, de 6 de abril, del Defensor del Pueblo, las quejas ante esta Institución deberán presentarse en el plazo máximo de:",
   ["Seis meses contados a partir del momento en que el interesado tuviera conocimiento de los hechos objeto de la queja.", "Un año contado a partir del momento en que el interesado tuviera conocimiento de los hechos objeto de la queja.", "Un año contado a partir del momento en que se produzcan los hechos objeto de la queja.", "Seis meses contados a partir del momento en que se produzcan los hechos objeto de la queja."], "b",
   "Art. 15.1 LO 3/1981: la queja se presentará «en el plazo máximo de un año, contado a partir del momento en que tuviera conocimiento de los hechos objeto de la misma».", ["en el plazo máximo de un año, contado a partir del momento en que tuviera conocimiento de los hechos objeto de la misma"])
AC(M, 12, 2, "LODP", "atercero", "Defensor del Pueblo", "Según la Ley Orgánica 3/1981, de 6 de abril, del Defensor del Pueblo, es requisito necesario para ser nombrado Defensor del Pueblo:",
   ["Ser español, mayor de edad, con residencia en España en los 2 años inmediatamente anteriores al nombramiento.", "Ser español, mayor de edad, con derechos de sufragio activo y pasivo y no haber sido inhabilitado para el ejercicio del cargo por las Cortes Generales.", "Ser español, mayor de edad, en pleno disfrute de los derechos civiles y políticos.", "Ser nacional de un Estado Miembros de la Unión Europea, con residencia en España en los 2 años inmediatamente anteriores al nombramiento."], "c",
   "Art. 3 LO 3/1981: «Podrá ser elegido Defensor del Pueblo cualquier español mayor de edad que se encuentre en el pleno disfrute de sus derechos civiles y políticos.»", ["cualquier español mayor de edad que se encuentre en el pleno disfrute de sus derechos civiles y políticos"])
AC(M, 13, 2, "LODP", "atreinta", "Defensor del Pueblo", "Según Ley Orgánica 3/1981, de 6 de abril, del Defensor del Pueblo:",
   ["El Defensor del Pueblo cesa exclusivamente por renuncia, expiración de su mandato y fallecimiento.", "El Defensor del Pueblo puede concluir su acción investigadora con la emisión de una advertencia.", "El Defensor del Pueblo puede recibir quejas que las autoridades administrativas presenten en asuntos de su competencia.", "Los poderes públicos pueden negarse a auxiliar con carácter preferente y urgente al Defensor del Pueblo en sus investigaciones."], "b",
   "Art. 30.1 LO 3/1981: «El Defensor del Pueblo, con ocasión de sus investigaciones, podrá formular a las autoridades y funcionarios de las Administraciones Públicas advertencias, recomendaciones, recordatorios de sus deberes legales y sugerencias para la adopción de nuevas medidas.»", ["advertencias, recomendaciones, recordatorios de sus deberes legales y sugerencias"])
AC(M, 14, 3, "CE", "a159", "Tribunal Constitucional", "Según establece el artículo 159.6 de la Constitución Española, el Tribunal Constitucional se compone de:",
   ["10 miembros nombrados por Rey; de ellos, tres a propuesta del Congreso por mayoría de tres quintos de sus miembros; tres a propuesta del Senado, con idéntica mayoría; dos a propuesta del Gobierno, y dos a propuesta del Consejo General del Poder Judicial.",
    "12 miembros nombrados por Rey; de ellos, cuatro a propuesta del Congreso por mayoría de dos tercios de sus miembros; cuatro a propuesta del Senado, con idéntica mayoría; dos a propuesta del Gobierno, y dos a propuesta del Consejo General del Poder Judicial.",
    "12 miembros nombrados por Rey; de ellos, cuatro a propuesta del Congreso por mayoría de tres cuartos de sus miembros; cuatro a propuesta del Senado, con idéntica mayoría; dos a propuesta del Gobierno, y dos a propuesta del Consejo General del Poder Judicial.",
    "12 miembros nombrados por Rey; de ellos, cuatro a propuesta del Congreso por mayoría de tres quintos de sus miembros; cuatro a propuesta del Senado, con idéntica mayoría; dos a propuesta del Gobierno, y dos a propuesta del Consejo General del Poder Judicial."], "d",
   "Art. 159.1 CE: «El Tribunal Constitucional se compone de 12 miembros nombrados por el Rey; de ellos, cuatro a propuesta del Congreso por mayoría de tres quintos de sus miembros; cuatro a propuesta del Senado, con idéntica mayoría; dos a propuesta del Gobierno, y dos a propuesta del Consejo General del Poder Judicial.»",
   ["cuatro a propuesta del Congreso por mayoría de tres quintos de sus miembros; cuatro a propuesta del Senado, con idéntica mayoría; dos a propuesta del Gobierno, y dos a propuesta del Consejo General del Poder Judicial"],
   aviso="el documento cita «art. 159.6», pero el artículo 159 solo tiene cinco apartados: la composición está en el **159.1** (prevalece la norma).")
AC(M, 15, 3, "CE", "a164", "Tribunal Constitucional", "Conforme al artículo 164 de la Constitución Española, las sentencias del Tribunal Constitucional:",
   ["Las que estimen subjetivamente un derecho tienen plenos efectos frente a todos.", "Pueden ser objeto de recurso de casación para la unificación de la doctrina.", "Se publicarán en el Boletín Oficial del Estado con los votos particulares, si los hubiere.", "Tiene el valor de cosa juzgada desde el día de su publicación."], "c",
   "Art. 164.1 CE: «Las sentencias del Tribunal Constitucional se publicarán en el boletín oficial del Estado con los votos particulares, si los hubiere. Tienen el valor de cosa juzgada a partir del día siguiente de su publicación y no cabe recurso alguno contra ellas.» (La d) falla en «desde el día de su publicación».)", ["se publicarán en el boletín oficial del Estado con los votos particulares, si los hubiere"])
AC(M, 16, 3, "CE", "a159", "Tribunal Constitucional", "Según el artículo 159 de la Constitución Española, los miembros del Tribunal Constitucional, aparte de sus incompatibilidades específicas, tendrán las incompatibilidades propias de:",
   ["Los miembros de las Cortes Generales.", "Los miembros del Gobierno de España.", "Los miembros del Tribunal de Cuentas.", "Los miembros del Poder Judicial."], "d",
   "Art. 159.4 CE: «En lo demás los miembros del Tribunal Constitucional tendrán las incompatibilidades propias de los miembros del poder judicial.»", ["tendrán las incompatibilidades propias de los miembros del poder judicial"],
   aviso="el documento cita «art. 159.3», pero esta regla está en el segundo párrafo del **159.4** (el 159.3 es el periodo de nueve años).")
AC(M, 17, 3, "CE", "a161", "Tribunal Constitucional", "De acuerdo con el artículo 161.1 de la Constitución, el Tribunal Constitucional tiene jurisdicción en todo el territorio español y es competente para reconocer:",
   ["De los conflictos de competencia entre Comunidades Autónomas.", "Del recurso de inconstitucionalidad contra leyes y reglamentos.", "Del recurso de casación.", "De las demás materias que le atribuyan las leyes estatales y las leyes de las Comunidades Autónomas."], "a",
   "Art. 161.1.c CE: «De los conflictos de competencia entre el Estado y las Comunidades Autónomas o de los de éstas entre sí.» (El recurso de inconstitucionalidad es contra leyes y disposiciones normativas con fuerza de ley —también contra Tratados y Reglamentos de las Cámaras, art. 27.2 LOTC—, no contra reglamentos administrativos; y las demás materias las atribuyen la Constitución o las leyes orgánicas.)", ["De los conflictos de competencia entre el Estado y las Comunidades Autónomas o de los de éstas entre sí"])
AC(M, 18, 1, "CE", "a166", "Reforma", "La iniciativa de reforma constitucional corresponde, según nuestra normativa constitucional:",
   ["Al Gobierno.", "Al Defensor del Pueblo.", "Al Tribunal Constitucional.", "A los órganos colegiados ejecutivos de las Comunidades Autónomas."], "a",
   "Art. 166 CE: la iniciativa de reforma se ejercerá «en los términos previstos en los apartados 1 y 2 del artículo 87»: **Gobierno**, Congreso, Senado y Asambleas de las Comunidades Autónomas.", ["apartados 1 y 2 del artículo 87"])
AC(M, 19, 1, "CE", "a167", "Reforma", "De conformidad con el artículo 167.1 de la Constitución Española, los proyectos de reforma constitucional deberán ser aprobados:",
   ["Por una mayoría de tres quintos de cada una de las Cámaras.", "Por una mayoría de dos tercios de cada una de las Cámaras.", "Por una mayoría simple de cada una de las Cámaras.", "Por una mayoría absoluta de cada una de las Cámaras."], "a",
   "Art. 167.1 CE: «Los proyectos de reforma constitucional deberán ser aprobados por una mayoría de tres quintos de cada una de las Cámaras.»", ["una mayoría de tres quintos de cada una de las Cámaras"])
AC(M, 20, 1, "CE", "a167", "Reforma", "Señale la respuesta correcta en relación con la regulación que recoge el artículo 167 de la Constitución Española sobre reforma constitucional:",
   ["La reforma constitucional, una vez aprobada por las Cortes Generales, será sometida a referéndum para su ratificación cuando así lo soliciten, dentro de los quince días siguientes a su aprobación, una décima parte de los miembros de cualquiera de las Cámaras.",
    "La reforma constitucional, una vez aprobada por las Cortes Generales, será sometida a referéndum para su ratificación cuando así lo solicite, dentro de los quince días siguientes a su aprobación, una décima parte de los miembros del Congreso de los Diputados.",
    "La reforma constitucional, una vez aprobada por las Cortes Generales, será sometida a referéndum para su ratificación cuando así lo soliciten, dentro de los veinte días siguientes a su aprobación, una décima parte de los miembros de cualquiera de las Cámaras.",
    "La reforma constitucional, una vez aprobada por las Cortes Generales, será sometida a referéndum para su ratificación cuando así lo soliciten, dentro de los veinte días siguientes a su aprobación, una décima parte de los miembros del Congreso de los Diputados."], "a",
   "Art. 167.3 CE: «Aprobada la reforma por las Cortes Generales, será sometida a referéndum para su ratificación cuando así lo soliciten, dentro de los quince días siguientes a su aprobación, una décima parte de los miembros de cualquiera de las Cámaras.»", ["dentro de los quince días siguientes a su aprobación, una décima parte de los miembros de cualquiera de las Cámaras"])

# ------------------------------------------------------------------ M105 · Test de tema
M = "M105"
NOEXP = "El documento no desarrolla esta solución; el artículo, de la norma vigente: "
AC(M, 1, 2, "CE", "a55", "Suspensión", "La suspensión de los derechos y libertades se encuentra regulada en la Constitución en:",
   ["En el Capítulo III del Título I.", "En sus artículos 52 y 53.", "En el artículo 58.", "En el Capítulo V del Título I."], "d",
   "Art. 55 CE, «De la suspensión de los derechos y libertades»: «Los derechos reconocidos en los artículos 17, 18, apartados 2 y 3, artículos 19, 20, apartados 1, a) y d), y 5, artículos 21, 28, apartado 2, y artículo 37, apartado 2, podrán ser suspendidos cuando se acuerde la declaración del estado de excepción o de sitio en los términos previstos en la Constitución.» Es el único artículo del **capítulo V del Título I**.", ["podrán ser suspendidos cuando se acuerde la declaración del estado de excepción o de sitio"])
AC(M, 2, 3, "CE", "a161", "Tribunal Constitucional", "Según el artículo 161 de la Constitución Española de 1978, el Tribunal Constitucional:",
   ["Dicta sentencias que pueden ser objeto de recurso por los órganos colegiados ejecutivos de las Comunidades Autónomas.", "Es competente para conocer de los conflictos de competencia entre el Estado y las Comunidades Autónomas o de los de éstas entre sí.", "Es el órgano jurisdiccional superior en todos los órdenes.", "Tiene jurisdicción en aquellas Comunidades Autónomas que explícitamente lo reconozcan en sus Estatutos de Autonomía, sin perjuicio de la jurisdicción que corresponde al Tribunal Supremo."], "b",
   "Art. 161.1 CE: «El Tribunal Constitucional tiene jurisdicción en todo el territorio español y es competente para conocer: […] c) De los conflictos de competencia entre el Estado y las Comunidades Autónomas o de los de éstas entre sí.»", ["De los conflictos de competencia entre el Estado y las Comunidades Autónomas o de los de éstas entre sí", "tiene jurisdicción en todo el territorio español"])
AC(M, 3, 2, "CE", "a19", "Suspensión", "Conforme al artículo 55 de la Constitución Española de 1978, el derecho de los españoles a circular por el territorio nacional:",
   ["Es un derecho fundamental que no puede ser suspendido.", "Podrá ser suspendido para personas determinadas, en relación con las investigaciones correspondientes a la actuación de bandas armadas o elementos terroristas.", "Podrá ser limitado por motivos políticos.", "Podrá ser suspendido cuando se acuerde la declaración del estado de excepción o de sitio."], "d",
   "Art. 19 CE: «Los españoles tienen derecho a elegir libremente su residencia y a circular por el territorio nacional.» El art. 55.1 incluye el art. 19 entre los derechos que «podrán ser suspendidos cuando se acuerde la declaración del estado de excepción o de sitio». (La suspensión individual del 55.2 solo alcanza a los arts. 17.2 y 18.2 y 18.3; y el art. 19 dice que el derecho de entrar y salir «no podrá ser limitado por motivos políticos o ideológicos».)", ["Los españoles tienen derecho a elegir libremente su residencia y a circular por el territorio nacional"])
AC(M, 4, 2, "CE", "a20", "Contenido", "Según la Constitución Española de 1978, es un derecho fundamental:",
   ["El derecho a la negociación colectiva laboral.", "El derecho a comunicar o recibir libremente información veraz por cualquier medio de difusión.", "El derecho a contraer matrimonio con plena igualdad jurídica.", "El derecho a disfrutar de un medio ambiente adecuado para el desarrollo de la persona."], "b",
   "Art. 20.1.d CE: «Se reconocen y protegen los derechos: […] d) A comunicar o recibir libremente información veraz por cualquier medio de difusión.» Está en la sección 1.ª (derechos fundamentales y libertades públicas).", ["A comunicar o recibir libremente información veraz por cualquier medio de difusión"])
AC(M, 5, 2, "LODP", "adiez", "Defensor del Pueblo", "Según la Ley Orgánica 3/1981, de 6 de abril, del Defensor del Pueblo, podrá dirigirse al Defensor del Pueblo:",
   ["Toda persona natural o jurídica que invoque un interés legítimo, sin restricción alguna.", "Toda persona natural o jurídica que invoque un interés legítimo, siempre que sean nacionales españoles o residentes en España.", "Toda persona natural que invoque un interés legítimo, pero no las personas jurídicas.", "Toda persona natural que invoque un interés legítimo, excepto las personas menores de edad."], "a",
   NOEXP + "art. 10.1 LO 3/1981: «Podrá dirigirse al Defensor del Pueblo toda persona natural o jurídica que invoque un interés legítimo, sin restricción alguna. No podrán constituir impedimento para ello la nacionalidad, residencia, sexo, minoría de edad, la incapacidad legal del sujeto, el internamiento en un centro penitenciario o de reclusión o, en general, cualquier relación especial de sujeción o dependencia de una Administración o Poder público.»", ["toda persona natural o jurídica que invoque un interés legítimo, sin restricción alguna", "nacionalidad, residencia, sexo, minoría de edad"])
AC(M, 6, 2, "CE", "a49", "Contenido", "El actual artículo 49 de la Constitución Española de 1978 establece que los poderes públicos impulsarán las políticas que garanticen la plena autonomía personal y la inclusión social de las personas con discapacidad:",
   ["En entornos universalmente accesibles.", "Mediante los ajustes razonables necesarios.", "Garantizando su tratamiento, rehabilitación e integración.", "Fomentando medidas de acción positiva."], "a",
   "Art. 49.2 CE: «Los poderes públicos impulsarán las políticas que garanticen la plena autonomía personal y la inclusión social de las personas con discapacidad, en entornos universalmente accesibles.»", ["la plena autonomía personal y la inclusión social de las personas con discapacidad, en entornos universalmente accesibles"])
AC(M, 7, 2, "CE", "a29", "Contenido", "Según la Constitución Española de 1978, es un derecho fundamental:",
   ["El derecho a la propiedad privada.", "El derecho a disfrutar de una vivienda digna y adecuada.", "El derecho de petición.", "El derecho a la negociación colectiva laboral."], "c",
   "Art. 29.1 CE: «Todos los españoles tendrán el derecho de petición individual y colectiva, por escrito, en la forma y con los efectos que determine la ley.» El documento recuerda que los arts. 15 a 29 son la «Sección 1.ª De los derechos fundamentales y de las libertades públicas».", ["derecho de petición individual y colectiva"])
AC(M, 8, 1, "CE", "a167", "Reforma", "Según el Título X de la Constitución Española de 1978, ¿cuál de las siguientes opciones es correcta?",
   ["La reforma constitucional será aprobada por mayoría de dos tercios de cada Cámara si se lleva a cabo durante la vigencia del estado de excepción.", "No es preceptiva la ratificación por referéndum para la reforma del artículo 49 de la CE relativo a las personas con discapacidad.", "La reforma del Título II de la CE será sometida a referéndum cuando así lo soliciten una décima parte de los miembros de cualquiera de las Cámaras.", "Los proyectos de reforma constitucional del Título V de la CE deberán ser aprobados por una mayoría de dos tercios de cada una de las Cámaras."], "b",
   "Art. 167.3 CE: el referéndum se celebra «cuando así lo soliciten, dentro de los quince días siguientes a su aprobación, una décima parte de los miembros de cualquiera de las Cámaras» (**facultativo**). El art. 49 no está protegido por el art. 168 (Título preliminar, sección 1.ª del capítulo II del Título I y Título II), por lo que su reforma sigue el 167 y el referéndum **no es preceptivo**. La a) falla por el art. 169 (no se puede iniciar la reforma en estado de excepción); la c), porque el Título II va por el art. 168 (referéndum obligatorio); la d), porque el Título V va por el 167.1 (tres quintos).", ["una décima parte de los miembros de cualquiera de las Cámaras"])
AC(M, 9, 2, "CE", "a17", "Contenido", "De acuerdo con el artículo 17 de la Constitución Española de 1978, ¿cuál sería el plazo máximo de duración de la prisión provisional?",
   ["72 horas.", "1 año.", "Se determinará por Ley.", "Se determinará por Reglamento."], "c",
   "Art. 17.4 CE: «[…] por ley se determinará el plazo máximo de duración de la prisión provisional.» (Las 72 horas son el plazo máximo de la **detención preventiva**, art. 17.2.)", ["por ley se determinará el plazo máximo de duración de la prisión provisional"])
AC(M, 10, 2, "LODP", "asegundo", "Defensor del Pueblo", "Según el artículo 2 de la Ley Orgánica 3/1981, de 6 de abril, del Defensor del Pueblo, ¿qué Comisión se designará en las Cortes Generales para relacionarse con el Defensor del Pueblo e informar a los respectivos Plenos en cuantas ocasiones sea necesario?",
   ["Una Comisión Mixta Congreso-Senado.", "Una Comisión Mixta de Control Parlamentario.", "Una Comisión Permanente Congreso-Senado.", "Una Comisión de Investigación."], "a",
   "Art. 2.2 LO 3/1981: «Se designará en las Cortes Generales una Comisión Mixta Congreso-Senado encargada de relacionarse con el Defensor del Pueblo e informar a los respectivos Plenos en cuantas ocasiones sea necesario.»", ["Comisión Mixta Congreso-Senado encargada de relacionarse con el Defensor del Pueblo e informar a los respectivos Plenos en cuantas ocasiones sea necesario"])
AC(M, 11, 1, "CE", "tpreliminar", "Estructura", "¿En cuántos títulos se encuentra estructurada la Constitución Española de 1978?",
   ["Un título preliminar y 10 títulos.", "Cinco títulos divididos en 10 subtítulos.", "No se estructura en títulos, sino en apartados.", "Dos títulos divididos en 10 artículos."], "a",
   "La CE consta de un **Título Preliminar** y **diez títulos** (del I al X), 169 artículos y las disposiciones adicionales, transitorias, derogatoria y final. El documento no desarrolla esta solución.", None)
AC(M, 12, 2, "CE", "a27", "Contenido", "Según el artículo 27 de la Constitución Española de 1978, la enseñanza básica es:",
   ["Obligatoria y gratuita.", "Voluntaria y gratuita.", "Obligatoria y de pago.", "Voluntaria y de pago."], "a",
   "Art. 27.4 CE: «La enseñanza básica es obligatoria y gratuita.»", ["La enseñanza básica es obligatoria y gratuita"])
AC(M, 13, 1, "CE", "a167", "Reforma", "Conforme a lo previsto en la Constitución Española de 1978, ¿qué mayoría se exige en el procedimiento de reforma constitucional contemplado en el artículo 167.1?",
   ["Mayoría de dos tercios de cada una de las Cámaras.", "Mayoría de tres quintos de cada una de las Cámaras.", "Mayoría de tres quintos del Congreso de los Diputados.", "Mayoría de dos tercios del Congreso de los Diputados."], "b",
   NOEXP + "art. 167.1 CE: «Los proyectos de reforma constitucional deberán ser aprobados por una mayoría de tres quintos de cada una de las Cámaras.»", ["una mayoría de tres quintos de cada una de las Cámaras"])
AC(M, 14, 1, "CE", "a1", "Contenido", "Conforme a lo previsto en la Constitución Española de 1978, la soberanía nacional reside:",
   ["En las Cortes Generales.", "En el Rey.", "En el pueblo español.", "En el poder judicial."], "c",
   "Art. 1.2 CE: «La soberanía nacional reside en el pueblo español, del que emanan los poderes del Estado.»", ["La soberanía nacional reside en el pueblo español, del que emanan los poderes del Estado"])
AC(M, 15, 3, "CE", "a159", "Tribunal Constitucional", "¿Quién nombra, conforme a lo previsto en la Constitución Española de 1978, a los miembros del Tribunal Constitucional?",
   ["El Congreso de los Diputados.", "El Senado.", "El Rey.", "El Gobierno."], "c",
   NOEXP + "art. 159.1 CE: «El Tribunal Constitucional se compone de 12 miembros nombrados por el Rey […]». Congreso, Senado, Gobierno y Consejo General del Poder Judicial **proponen**; el Rey **nombra**.", ["12 miembros nombrados por el Rey"])
AC(M, 16, 1, "CE", "a168", "Reforma", "De acuerdo con el artículo 168 de la Constitución Española, en caso de revisión total de la Constitución, el nuevo texto constitucional aprobado por las Cortes Generales será sometido a referéndum para su ratificación:",
   ["En todos los casos.", "Cuando así lo solicite, dentro de los quince días siguientes a su aprobación, una mayoría de dos tercios de cada Cámara.", "Cuando así lo soliciten, dentro de los veinte días siguientes a su aprobación, cincuenta diputados o cincuenta senadores.", "Cuando así lo solicite, dentro de los quince días siguientes a su aprobación, una décima parte de los miembros de cualquiera de las Cámaras."], "a",
   "Art. 168.3 CE: «Aprobada la reforma por las Cortes Generales, será sometida a referéndum para su ratificación.» Es el referéndum **obligatorio** (el facultativo, a petición de una décima parte de los miembros de cualquier Cámara, es del art. 167.3).", ["será sometida a referéndum para su ratificación"])
AC(M, 17, 1, "CE", "a9", "Contenido", "En el artículo 9 de la Constitución Española se garantizan, entre otros, los principios de:",
   ["Legalidad, responsabilidad y fraternidad.", "Legalidad, libertad y jerarquía normativa.", "Jerarquía normativa, publicidad de las normas y seguridad jurídica.", "Jerarquía normativa, retroactividad de las disposiciones sancionadoras no favorables o restrictivas de derechos individuales y arbitrariedad de los poderes públicos."], "c",
   "Art. 9.3 CE: «La Constitución garantiza el principio de legalidad, la jerarquía normativa, la publicidad de las normas, la irretroactividad de las disposiciones sancionadoras no favorables o restrictivas de derechos individuales, la seguridad jurídica, la responsabilidad y la interdicción de la arbitrariedad de los poderes públicos.» (La d) cambia «irretroactividad» por «retroactividad» y «interdicción de la arbitrariedad» por «arbitrariedad».)", ["la jerarquía normativa, la publicidad de las normas, la irretroactividad de las disposiciones sancionadoras no favorables o restrictivas de derechos individuales, la seguridad jurídica"])
AC(M, 18, 3, "CE", "a162", "Tribunal Constitucional", "De acuerdo con el artículo 162 de la Constitución Española, está legitimado para interponer el recurso de inconstitucionalidad:",
   ["El Congreso de los Diputados por mayoría de tres quintos.", "25 Senadores.", "Cualquier miembro del Consejo de Ministros.", "El Defensor del Pueblo."], "d",
   NOEXP + "art. 162.1.a) CE: están legitimados «el Presidente del Gobierno, el Defensor del Pueblo, 50 Diputados, 50 Senadores, los órganos colegiados ejecutivos de las Comunidades Autónomas y, en su caso, las Asambleas de las mismas».", ["el Defensor del Pueblo, 50 Diputados, 50 Senadores"])
AC(M, 19, 1, "CE", "tpreliminar", "Estructura", "La Constitución Española de 1978 consta de:",
   ["Un Preámbulo, 269 artículos, 6 disposiciones adicionales, 9 disposiciones transitorias, 1 disposición derogatoria y 1 disposición final.", "Un Título Preliminar, 396 artículos, 4 disposiciones adicionales, 4 disposiciones transitorias, 1 disposición derogatoria y 1 disposición final.", "Un Preámbulo, 169 artículos, 4 disposiciones adicionales, 9 disposiciones transitorias, 1 disposición derogatoria y 1 disposición final.", "Un Preámbulo, 166 artículos, 14 disposiciones adicionales, 10 disposiciones transitorias, 10 disposiciones derogatorias y 1 disposición final."], "c",
   "Un Preámbulo, **169** artículos, **4** disposiciones adicionales, **9** transitorias, **1** derogatoria y **1** final (regla «4-9-1-1»). El documento no desarrolla esta solución.", None)
AC(M, 20, 2, "CE", "a19", "Contenido", "¿En qué artículo de la Constitución Española de 1978 se recoge el derecho de los españoles a elegir libremente su residencia y a circular libremente por el territorio nacional?",
   ["En el artículo 19.", "En el artículo 20.", "En el artículo 17.", "En el artículo 18."], "a",
   "Art. 19 CE: «Los españoles tienen derecho a elegir libremente su residencia y a circular por el territorio nacional. Asimismo, tienen derecho a entrar y salir libremente de España en los términos que la ley establezca. Este derecho no podrá ser limitado por motivos políticos o ideológicos.»", ["Los españoles tienen derecho a elegir libremente su residencia y a circular por el territorio nacional"])
AC(M, 21, 3, "LOTC", "acatorce", "Tribunal Constitucional", "De acuerdo con lo establecido en la Ley Orgánica 2/1979, de 3 de octubre, del Tribunal Constitucional, el Tribunal en Pleno puede adoptar acuerdos cuando estén presentes:",
   ["Al menos, tres quintos de los miembros que en cada momento lo compongan.", "La mitad más uno de los miembros que en cada momento lo compongan.", "Al menos, dos tercios de los miembros que en cada momento lo compongan.", "Al menos, un tercio de los miembros que en cada momento lo compongan."], "c",
   "Art. 14 LO 2/1979: «El Tribunal en Pleno puede adoptar acuerdos cuando estén presentes, al menos, dos tercios de los miembros que en cada momento lo compongan. Los acuerdos de las Salas requerirán asimismo la presencia de dos tercios de los miembros que en cada momento las compongan. En las Secciones se requerirá la presencia de dos miembros, salvo que haya discrepancia, requiriéndose entonces la de sus tres miembros.»", ["El Tribunal en Pleno puede adoptar acuerdos cuando estén presentes, al menos, dos tercios de los miembros que en cada momento lo compongan"])
AC(M, 22, 3, "CE", "a161", "Tribunal Constitucional", "En virtud del artículo 161 de la Constitución Española de 1978, ¿en cuál de los siguientes supuestos se produce la suspensión de la disposición o resolución recurrida ante el Tribunal Constitucional?",
   ["Cuando el Defensor del Pueblo interpone recurso de amparo.", "Cuando un órgano judicial plantea cuestión de inconstitucionalidad.", "Cuando cincuenta Diputados interponen recurso de inconstitucionalidad.", "Cuando el Gobierno impugna una disposición o resolución adoptada por los órganos de las Comunidades Autónomas."], "d",
   "Art. 161.2 CE: «El Gobierno podrá impugnar ante el Tribunal Constitucional las disposiciones y resoluciones adoptadas por los órganos de las Comunidades Autónomas. La impugnación producirá la suspensión de la disposición o resolución recurrida, pero el Tribunal, en su caso, deberá ratificarla o levantarla en un plazo no superior a cinco meses.»", ["La impugnación producirá la suspensión de la disposición o resolución recurrida"])
AC(M, 23, 1, "CE", "a169", "Reforma", "Indique la afirmación correcta:",
   ["No podrá iniciarse la reforma constitucional en tiempo de guerra o de vigencia de los estados de alarma, excepción o sitio.", "La reforma constitucional podrá iniciarse en cualquier momento, siempre que se cuente con la mayoría requerida para su iniciativa.", "La reforma constitucional no podrá iniciarse en tiempo de guerra, pero sí en tiempo de vigencia de los estados de alarma, excepción o sitio.", "La reforma constitucional podrá iniciarse por el Jefe del Estado."], "a",
   NOEXP + "art. 169 CE: «No podrá iniciarse la reforma constitucional en tiempo de guerra o de vigencia de alguno de los estados previstos en el artículo 116.» (Los estados del art. 116 son el de alarma, el de excepción y el de sitio.) La iniciativa (art. 166 → 87.1 y 87.2) no corresponde al Jefe del Estado.", ["en tiempo de guerra o de vigencia de alguno de los estados previstos en el artículo 116"])
AC(M, 24, 2, "CE", "a18", "Contenido", "¿En qué artículo de la Constitución Española de 1978 se recoge la garantía del derecho fundamental al honor, a la intimidad personal y familiar y a la propia imagen?",
   ["Artículo 15.", "Artículo 17.", "Artículo 16.", "Artículo 18."], "d",
   NOEXP + "art. 18.1 CE: «Se garantiza el derecho al honor, a la intimidad personal y familiar y a la propia imagen.»", ["Se garantiza el derecho al honor, a la intimidad personal y familiar y a la propia imagen"])
AC(M, 25, 3, "CE", "a159", "Tribunal Constitucional", "La designación para el cargo de Magistrado del Tribunal Constitucional se hace por un plazo de:",
   ["Por un plazo de seis años, renovándose por terceras partes cada tres.", "Por un plazo de tres años.", "Por un plazo de nueve años renovándose por terceras partes cada tres.", "Por un plazo de cuatro años."], "c",
   "Art. 159.3 CE: «Los miembros del Tribunal Constitucional serán designados por un período de nueve años y se renovarán por terceras partes cada tres.»", ["serán designados por un período de nueve años y se renovarán por terceras partes cada tres"])
AC(M, 26, 2, "CE", "a43", "Contenido", "Señale cuál de los siguientes derechos NO se considera un derecho fundamental según lo establecido en la Constitución Española de 1978:",
   ["A la libertad y a la seguridad.", "A la protección de la salud.", "A la participación en los asuntos públicos.", "A la prohibición de los Tribunales de Honor."], "b",
   "Art. 43.1 CE: «Se reconoce el derecho a la protección de la salud.» Está en el capítulo III del Título I (principios rectores), no en la sección 1.ª (arts. 15 a 29): la libertad y seguridad (art. 17), la participación en los asuntos públicos (art. 23) y la prohibición de los Tribunales de Honor (art. 26) sí son derechos fundamentales.", ["Se reconoce el derecho a la protección de la salud"])
AC(M, "27 (actualizada a la reforma de 2026)", 1, "CE", "a69", "Reforma", "Señale qué artículos de la Constitución Española de 1978 se han reformado desde su publicación y entrada en vigor:",
   ["El artículo 13.2, el 135, el 49 y el 69.3.", "El artículo 13.4, el 135, el 49 y el 69.3.", "Únicamente el artículo 13.2 y el 135.", "El artículo 13.3, el 135, el 47 y el 69.3."], "a",
   "**Pregunta de la academia actualizada** (el documento es anterior a 2026 y no incluía la cuarta reforma). Las cuatro reformas vigentes son: **1992** (art. 13.2: sufragio pasivo en las municipales), **2011** (art. 135: estabilidad presupuestaria), **2024** (art. 49: personas con discapacidad) y **2026** (art. 69.3: circunscripciones insulares del Senado; Formentera elige un senador propio).", ["uno a cada una de las siguientes islas: Ibiza, Formentera, Menorca"])
AC(M, 28, 2, "CE", "a11", "Contenido", "Según el artículo 11.3 de la Constitución Española de 1978, en los países iberoamericanos podrán naturalizarse los españoles sin perder su nacionalidad de origen:",
   ["Siempre que tales países reconozcan a sus ciudadanos un derecho recíproco.", "Aunque no hayan tenido o tengan una particular vinculación con España.", "En los casos que la normativa de tales países lo permita para los ciudadanos españoles y europeos.", "Aun cuando no reconozcan a sus ciudadanos un derecho recíproco."], "d",
   NOEXP + "art. 11.3 CE: «El Estado podrá concertar tratados de doble nacionalidad con los países iberoamericanos o con aquellos que hayan tenido o tengan una particular vinculación con España. En estos mismos países, aun cuando no reconozcan a sus ciudadanos un derecho recíproco, podrán naturalizarse los españoles sin perder su nacionalidad de origen.»", ["aun cuando no reconozcan a sus ciudadanos un derecho recíproco, podrán naturalizarse los españoles sin perder su nacionalidad de origen"])
AC(M, 29, 2, "LODP", "acuao", "Defensor del Pueblo", "El nombramiento del Defensor del Pueblo será acreditado, según el artículo 4.1 de la Ley Orgánica 3/1981, de 6 de abril, del Defensor del Pueblo:",
   ["Por el Presidente del Gobierno, con su firma.", "Solamente por el Presidente del Senado, con su firma.", "Conjuntamente por los Presidentes del Congreso y del Senado con sus firmas.", "Por el Rey con su firma."], "c",
   "Art. 4.1 LO 3/1981: «Los Presidentes del Congreso y del Senado acreditarán conjuntamente con sus firmas el nombramiento del Defensor del Pueblo que se publicará en el «Boletín Oficial del Estado».»", ["acreditarán conjuntamente con sus firmas el nombramiento del Defensor del Pueblo"])
AC(M, 30, 3, "LOTC", "aveintitres", "Tribunal Constitucional", "Según la Ley Orgánica 2/1979, de 3 de octubre, del Tribunal Constitucional, en caso de cese en el cargo de Magistrado del Tribunal Constitucional, por haber sido declarado responsable civilmente por dolo:",
   ["Decidirá el Tribunal en Pleno, por mayoría simple.", "Decidirá el Tribunal en Pleno, por mayoría de las tres cuartas partes de sus miembros.", "Decidirá el presidente del Tribunal Constitucional.", "Decidirá el Tribunal en pleno, por mayoría de las tres quintas partes de sus miembros."], "b",
   NOEXP + "art. 23 LO 2/1979: cesa el Magistrado por «haber sido declarado responsable civilmente por dolo o condenado por delito doloso o por culpa grave» (séptimo) y, en esos supuestos, «decidirá el Tribunal en Pleno, por mayoría simple en los casos tercero y cuarto y por mayoría de las tres cuartas partes de sus miembros en los demás casos». El Presidente decreta el cese solo en los casos primero y segundo (renuncia y expiración del plazo) y en el de fallecimiento.", ["por mayoría de las tres cuartas partes de sus miembros en los demás casos", "haber sido declarado responsable civilmente por dolo"])
AC(M, 31, 1, "CE", "a9", "Contenido", "¿Cuáles de los siguientes principios generales del Derecho aparecen en el artículo 9.3 de la Constitución Española de 1978?",
   ["La autonomía y la solidaridad.", "La buena fe y la equidad.", "La publicidad de las normas, la responsabilidad y la interdicción de la arbitrariedad de los poderes públicos.", "La eficacia y la jerarquía."], "c",
   NOEXP + "art. 9.3 CE: «La Constitución garantiza el principio de legalidad, la jerarquía normativa, la publicidad de las normas, la irretroactividad de las disposiciones sancionadoras no favorables o restrictivas de derechos individuales, la seguridad jurídica, la responsabilidad y la interdicción de la arbitrariedad de los poderes públicos.»", ["la publicidad de las normas", "la responsabilidad y la interdicción de la arbitrariedad de los poderes públicos"])
AC(M, "32 (actualizada: reforma de 2024)", 1, "CE", "a49", "Reforma", "La reforma de la Constitución Española de 1978 de 15 de febrero de 2024 tiene por objeto:",
   ["El artículo 49.", "El artículo 33.", "El artículo 50.", "El artículo 47."], "a",
   "**Pregunta de la academia actualizada** (el enunciado original la llamaba «la última reforma», pero hoy la última es la de 2026). La reforma de 15 de febrero de 2024 modificó el **art. 49** (personas con discapacidad): «Las personas con discapacidad ejercen los derechos previstos en este Título en condiciones de libertad e igualdad reales y efectivas.»", ["Las personas con discapacidad ejercen los derechos previstos en este Título en condiciones de libertad e igualdad reales y efectivas"])
AC(M, "32 (actualizada: última reforma)", 1, "CE", "a69", "Reforma", "La última reforma de la Constitución Española de 1978, de 19 de mayo de 2026, tiene por objeto:",
   ["El artículo 69.3.", "El artículo 49.", "El artículo 135.", "El artículo 13.2."], "a",
   "**Pregunta de la academia actualizada** a la normativa vigente. La reforma de **19 de mayo de 2026** (BOE de 20-5-2026) modificó el **art. 69.3**: cada isla con Cabildo o Consejo Insular es una circunscripción para elegir Senadores y, entre otras, **Ibiza y Formentera** eligen cada una un senador (antes iban juntas como «Ibiza-Formentera»).", ["Ibiza, Formentera, Menorca"])
