# -*- coding: utf-8 -*-
"""Texto legal LITERAL (BOE consolidado, API de datos abiertos) de las preguntas
del examen GACE-L 2025 cuyas normas se descargaron de boe.es, y comprobación
plantilla ↔ ley de cada una. Si algo no casa, se detiene (assert).

LEY[n]   = [(norma, bloque, [párrafos], título, [negritas])]
SI[n]    = [(dato en la opción correcta, norma, bloque, fragmento literal de la ley)]
NO[n]    = pregunta en negativo: ([(letra, dato en ese distractor, norma, bloque, fragmento)],
            (fragmento de la opción correcta que NO está en la ley, norma, bloque))
"""
import boe

NOMBRE = {
  "LO3_1980": "Ley Orgánica 3/1980, del Consejo de Estado", "LOPJ": "Ley Orgánica 6/1985, del Poder Judicial",
  "L40": "Ley 40/2015, de Régimen Jurídico del Sector Público", "LRBRL": "Ley 7/1985, Reguladora de las Bases del Régimen Local",
  "RD931": "Real Decreto 931/2017, de la Memoria del Análisis de Impacto Normativo",
  "LO6_2013": "Ley Orgánica 6/2013, de la Autoridad Independiente de Responsabilidad Fiscal",
  "LGSS": "Texto refundido de la Ley General de la Seguridad Social (RDLeg 8/2015)",
  "L22_2009": "Ley 22/2009, del sistema de financiación de las Comunidades Autónomas de régimen común",
  "RD633": "Real Decreto 633/2025, Estrategia Española de Apoyo Activo al Empleo 2025-2028",
  "LOEX": "Ley Orgánica 4/2000, de derechos y libertades de los extranjeros en España",
  "RD389": "Real Decreto 389/2021, Estatuto de la Agencia Española de Protección de Datos",
  "LOPD": "Ley Orgánica 3/2018, de Protección de Datos Personales y garantía de los derechos digitales",
  "RD1051": "Real Decreto 1051/2013, de prestaciones del Sistema para la Autonomía y Atención a la Dependencia (redacción del Real Decreto 675/2023)",
  "L4_2023": "Ley 4/2023, para la igualdad real y efectiva de las personas trans y para la garantía de los derechos de las personas LGTBI",
  "L7_2025": "Ley 7/2025, por la que se crea la Agencia Estatal de Salud Pública",
  "CC": "Código Civil", "L39": "Ley 39/2015, del Procedimiento Administrativo Común de las Administraciones Públicas",
  "LCSP": "Ley 9/2017, de Contratos del Sector Público", "LGS": "Ley 38/2003, General de Subvenciones",
  "LEF": "Ley de 16 de diciembre de 1954 sobre expropiación forzosa", "LPAP": "Ley 33/2003, del Patrimonio de las Administraciones Públicas",
  "TREBEP": "Texto refundido de la Ley del Estatuto Básico del Empleado Público (RDLeg 5/2015)",
  "RDL6": "Real Decreto-ley 6/2023", "L53": "Ley 53/1984, de Incompatibilidades del personal al servicio de las Administraciones Públicas",
  "RD462": "Real Decreto 462/2002, sobre indemnizaciones por razón del servicio",
  "L30": "Ley 30/1984, de medidas para la reforma de la Función Pública",
  "CONV": "IV Convenio colectivo único para el personal laboral de la Administración General del Estado",
  "MUF": "Texto refundido de la Ley sobre Seguridad Social de los Funcionarios Civiles del Estado (RDLeg 4/2000)",
  "RD375": "Real Decreto 375/2003, Reglamento General del Mutualismo Administrativo",
  "RD2271": "Real Decreto 2271/2004, de acceso al empleo público y provisión de puestos de las personas con discapacidad",
  "OPJC804": "Orden PJC/804/2025, de adaptaciones y ajustes razonables en los procesos selectivos",
  "LOEP": "Ley Orgánica 2/2012, de Estabilidad Presupuestaria y Sostenibilidad Financiera",
  "LGP": "Ley 47/2003, General Presupuestaria", "LOTCu": "Ley Orgánica 2/1982, del Tribunal de Cuentas",
  "LGT": "Ley 58/2003, General Tributaria", "L8_1989": "Ley 8/1989, de Tasas y Precios Públicos",
  "ODOC": "Orden de 1 de febrero de 1996, documentos contables de la Administración General del Estado",
  "OIOC": "Orden de 1 de febrero de 1996, Instrucción de operatoria contable en la ejecución del gasto del Estado",
  "TUE": "Tratado de la Unión Europea (versión consolidada, DOUE C 202 de 7-6-2016)",
  "TFUE": "Tratado de Funcionamiento de la Unión Europea (versión consolidada, DOUE C 202 de 7-6-2016)",
  "FEMPA": "Reglamento (UE) 2021/1139, del Fondo Europeo Marítimo, de Pesca y de Acuicultura (DOUE L 247 de 13-7-2021)",
  "RD345": "Real Decreto 345/2001, por el que se regula el Observatorio Permanente de la Inmigración",
  "RES2014": "Resolución de 20 de enero de 2014, de la Dirección General de Presupuestos, códigos de la clasificación económica",
}

LEY = {
  8:  [("LO3_1980", "acuarto", [1, 2, 3, 4, 5, 6], "artículo cuarto.uno", ["Los Consejeros permanentes"]),
       ("LO3_1980", "aseptimo", [1], "artículo séptimo", ["en numero igual al de las Secciones del Consejo, son nombrados, sin límite de tiempo, por Real Decreto"])],
  10: [("LOPJ", "atercero", [2], "artículo 3.2", ["en el ámbito estrictamente castrense y, en su caso, en las materias que establezca la declaración del estado de sitio"])],
  11: [("L40", "Artículo 55 bis", [1], "artículo 55 bis", ["no superen el sesenta por ciento ni sean menos del cuarenta por ciento en el ámbito de cada departamento ministerial"])],
  12: [("L40", "Artículo 82", [1, 2], "artículo 82.1", ["registro público administrativo", "Intervención General de la Administración del Estado"])],
  16: [("LRBRL", "Artículo 22", [2, 3, 13], "artículo 22.2, párrafos a) y k)", ["al Pleno municipal en los Ayuntamientos, y a la Asamblea vecinal en el régimen de Concejo Abierto", "La declaración de lesividad de los actos del Ayuntamiento"])],
  32: [("RD931", "a3", [2], "artículo 3.2", ["listado de las normas que quedan derogadas"])],
  33: [("LO6_2013", "a17", [1], "artículo 17", ["Antes del 15 de julio de cada año"])],
  35: [("LGSS", "a125", [9], "artículo 125.3", ["conocerá semestralmente de la evolución y composición del Fondo de Reserva"])],
  36: [("L22_2009", "preambulo", None, "preámbulo", ["El Fondo de Suficiencia Global opera como recurso de cierre del sistema"])],
  37: [("RD633", "ci-3", [97, 100, 104, 107, 111, 198], "anexo (Estrategia), capítulo III, apartados 4 (objetivos estratégicos) y 5 (objetivos operativos)", ["Objetivo operativo 5.2 Promover la digitalización del Sistema Nacional de Empleo"])],
  38: [("LOEX", "Artículo 35 ter", [1, 2, 3, 4], "artículo 35 ter.1", ["contendrá"])],
  40: [("RD389", "a6", [2], "artículo 6.2", ["persona titular de la Adjuntía a la Presidencia de la Agencia Española de Protección de Datos o el Subdirector General o Director de División correspondiente"])],
  41: [("LOPD", "Artículo 88", [1], "artículo 88.1", ["el respeto de su tiempo de descanso, permisos y vacaciones, así como de su intimidad personal y familiar"])],
  42: [("RD1051", "anii", [1, 2, 3, 4], "anexo II", ["Grado II: De 38 a 64 horas mensuales"])],
  43: [("L4_2023", "Artículo 3", [8], "artículo 3 d)", ["Acoso discriminatorio"])],
  45: [("L7_2025", "Artículo 1", [1], "artículo 1.1", ["Agencia Estatal de Salud Pública"]),
       ("L7_2025", "Artículo 2", [1], "artículo 2.1", ["reforzar las capacidades del Estado para mejorar la salud de la población"])],
  46: [("CC", "a1", [1], "artículo 1.1", ["la ley, la costumbre y los principios generales del derecho"])],
  48: [("L39", "Artículo 133", [8], "artículo 133.4, párrafo primero", ["o cuando concurran razones graves de interés público que lo justifiquen"])],
  49: [("L39", "Artículo 48", [1], "artículo 48.1", ["cualquier infracción del ordenamiento jurídico, incluso la desviación de poder"])],
  50: [("LCSP", "Artículo 44", [5], "artículo 44.1, párrafo segundo", ["por sus características no sea posible fijar su precio de licitación"])],
  51: [("LCSP", "Artículo 36", [3], "artículo 36.3", ["se perfeccionan con su adjudicación"])],
  52: [("LCSP", "Artículo 88", [1, 2], "artículo 88.1 a)", ["cinco últimos años"])],
  53: [("LGS", "Artículo 20", [5], "artículo 20.3", ["La Intervención General de la Administración del Estado es el órgano responsable de la administración y custodia de la BDNS"])],
  54: [("LEF", "aveintidos", [1], "artículo veintidós.1", ["recurso de alzada ante el Ministerio correspondiente"])],
  55: [("LPAP", "Artículo 50", [2], "artículo 50.2", ["no podrá instarse"]),
       ("LPAP", "Artículo 51", [1], "artículo 51.1", ["Director General del Patrimonio del Estado", "Ministro de Hacienda la resolución", "La instrucción del procedimiento corresponderá a los Delegados de Economía y Hacienda"])],
  56: [("L39", "Artículo 91", [3], "artículo 91.3", ["Transcurridos seis meses"])],
  57: [("L39", "Artículo 73", [1], "artículo 73.1", ["en el plazo de diez días"])],
  58: [("L39", "Artículo 24", [2], "artículo 24.1, párrafo segundo", ["derecho de petición, a que se refiere el artículo 29 de la Constitución", "dominio público", "impliquen el ejercicio de actividades que puedan dañar el medio ambiente", "responsabilidad patrimonial"])],
  59: [("L39", "Artículo 121", [3], "artículo 121.2, párrafo segundo", ["deberá remitirlo al competente en el plazo de diez días"])],
  61: [("TREBEP", "Artículo 62", [1, 2, 3, 4, 5], "artículo 62.1", ["Superación del proceso selectivo", "Nombramiento por el órgano o autoridad competente", "Acto de acatamiento de la Constitución", "Toma de posesión dentro del plazo que se establezca"])],
  62: [("TREBEP", "Artículo 64", [1, 3], "artículo 64.1 y 3", ["manifestada por escrito y será aceptada expresamente por la Administración", "no inhabilita"])],
  63: [("TREBEP", "Artículo 16", [4, 5, 6, 7, 8], "artículo 16.3", ["Carrera horizontal", "Carrera vertical", "Promoción interna vertical", "Promoción interna horizontal"])],
  64: [("TREBEP", "Artículo 96", [6], "artículo 96.1 e)", ["penalización a efectos de carrera, promoción o movilidad voluntaria"])],
  65: [("TREBEP", "Artículo 70", [1], "artículo 70.1", ["dentro del plazo improrrogable de tres años"])],
  66: [("RDL6", "Artículo 110", [3], "artículo 110.3, párrafo primero", ["adscritos a una o varias áreas funcionales"])],
  67: [("RDL6", "Artículo 123", [3], "artículo 123.3", ["las personas titulares de las subdirecciones generales"]),
       ("RDL6", "Artículo 127", [1], "artículo 127.1, párrafo primero", ["sin que quepa la cobertura de carácter provisional"])],
  68: [("RDL6", "Artículo 111", [1], "artículo 111", ["concursos unitarios, de carácter abierto y permanente"])],
  69: [("TREBEP", "Artículo 85", [1, 2, 3, 4, 5, 6], "artículo 85.1", ["Servicios especiales", "Excedencia", "Suspensión de funciones"])],
  70: [("L53", "aquinto", [1, 3], "artículo quinto.1 b)", ["salvo que desempeñen en las mismas cargos retribuidos en régimen de dedicación exclusiva"])],
  71: [("RD462", "a5", [1], "artículo 5.1", ["salvo casos excepcionales, no durará más de un mes en territorio nacional y de tres en el extranjero"])],
  72: [("L30", "aveinticuatro", [1], "artículo veinticuatro.1 (derogado por el TREBEP con el alcance de su disposición final cuarta.2: se mantiene mientras no se dicten las leyes de Función Pública)", ["serán iguales en todas las Administraciones públicas, para cada uno de los grupos en que se clasifican los cuerpos, escalas, categorías o clases de funcionarios"]),
       ("L30", "aveintitres", [3, 4], "artículo veintitrés.2 a) y b) (derogado por el TREBEP con el alcance de su disposición final cuarta.2: se mantiene mientras no se dicten las leyes de Función Pública)", ["Los trienios"])],
  73: [("RD462", "a1", [1, 2, 3, 4, 5], "artículo 1.1", ["Desplazamientos dentro del término municipal por razón de servicio", "Traslados de residencia", "colaboración en centros de formación y perfeccionamiento del personal de las Administraciones públicas"])],
  74: [("CONV", "a8", [1, 2, 3, 4, 5], "artículo 8.1", ["Grupo profesional E2: Título de Bachiller o Técnico o equivalentes"])],
  75: [("CONV", "a8-7", [1, 2, 3], "artículo 85.1", ["Los Delegados y Delegadas de personal"])],
  76: [("TREBEP", "Artículo 37", [15, 21], "artículo 37.2 e)", ["Quedan excluidas de la obligatoriedad de la negociación", "La regulación y determinación concreta, en cada caso, de los sistemas, criterios, órganos y procedimientos de acceso al empleo público y la promoción profesional"])],
  77: [("MUF", "a3", [1, 2, 3, 4, 5, 6, 8], "artículo 3.1 y 3.2 a), b) y d)", ["Los funcionarios en prácticas que aspiren a incorporarse a Cuerpos de la Administración Civil del Estado", "Quedan excluidos"])],
  78: [("RD375", "Artículo 66", [1], "artículo 66", ["así como el embarazo, el parto y el puerperio"])],
  79: [("LGSS", "datercera", [1], "disposición adicional tercera.1", ["Con efectos de 1 de enero de 2011", "en el Régimen General de la Seguridad Social siempre que el acceso a la condición de que se trate se produzca a partir de aquella fecha"])],
  80: [("RD2271", "a9", [1], "artículo 9", ["la alteración del orden de prelación para la elección de las plazas dentro del ámbito territorial que se determine en la convocatoria", "dificultades de desplazamiento"])],
  81: [("OPJC804", "a5", [1, 2], "artículo 5 a)", ["Asistente personal"])],
  83: [("LOEP", "a3", [2], "artículo 3.2", ["la situación de equilibrio o superávit estructural"])],
  85: [("LGP", "a40", [4], "artículo 40.1 c)", ["agrupará los créditos por capítulos separando las operaciones corrientes, las de capital, las financieras y el Fondo de Contingencia de ejecución presupuestaria"])],
  86: [("LGP", "a51", [1, 2, 3, 4, 5, 6], "artículo 51", ["Transferencias", "Ampliaciones", "Créditos extraordinarios y suplementos de crédito", "Incorporaciones"])],
  87: [("LGP", "a56", [4, 5], "artículo 56.3 a)", ["hasta un importe del 10 %", "cuando no supere la cuantía de 500.000 euros"])],
  88: [("LGP", "a150bis", [2], "artículo 150 bis, párrafo segundo", ["el Interventor General podrá avocar para sí cualquier acto o expediente que considere oportuno"])],
  89: [("LOTCu", "atreintayocho", [3, 4, 5], "artículo treinta y ocho.tres a cinco", ["se transmiten a los causahabientes de los responsables por la aceptación expresa o tácita de la herencia, pero sólo en la cuantía a que ascienda el importe líquido de la misma"])],
  90: [("LGP", "a73", [11], "artículo 73.4", ["el acto mediante el que se declara la existencia de un crédito exigible contra la Hacienda Pública estatal"])],
  91: [("OIOC", "regla23", [4], "regla 23.3, párrafo segundo", ["expedirá un documento OK"])],
  93: [("ODOC", "sexto", [9], "apartado sexto f)", ["compromiso de gasto imputables al Presupuesto corriente"])],
  94: [("RES2014", "ai-4", [382, 383], "anexo IV (código de la clasificación económica de los gastos), capítulo 2", ["Artículo 23. Indemnizaciones por razón del servicio."])],
  95: [("LGP", "a79", [9], "artículo 79.5", ["Los perceptores de las órdenes de pago a justificar son responsables"])],
  96: [("LGP", "a43", [1], "artículo 43.1", ["las inversiones reales a nivel de capítulo"])],
  97: [("LGT", "a2", [5], "artículo 2.2 b)", ["Contribuciones especiales"])],
  98: [("L8_1989", "Artículo 10", [1], "artículo 10.1", ["deberá realizarse con arreglo a Ley"])],
  99: [("L30", "aveintitres", [10], "artículo veintitrés.3 b) (derogado por el TREBEP con el alcance de su disposición final cuarta.2: se mantiene mientras no se dicten las leyes de Función Pública)", ["El complemento específico"])],
  19: [("TUE", "Artículo 15", [5], "artículo 15.5", ["para un mandato de dos años y medio, que podrá renovarse una sola vez"])],
  20: [("TUE", "Artículo 16", [11], "artículo 16.7", ["Un Comité de Representantes Permanentes de los Gobiernos de los Estados miembros se encargará de preparar los trabajos del Consejo"])],
  21: [("TFUE", "Artículo 249", [2], "artículo 249.2", ["al menos un mes antes"])],
  22: [("TUE", "Artículo 14", [1, 5], "artículo 14.1 y 4", ["conjuntamente con el Consejo", "El Parlamento Europeo elegirá a su Presidente y a la Mesa de entre sus diputados"]),
       ("TUE", "Artículo 16", [9], "artículo 16.6, párrafo segundo", ["El Consejo de Asuntos Generales velará por la coherencia de los trabajos de las diferentes formaciones del Consejo"]),
       ("TUE", "Artículo 17", [3], "artículo 17.3", ["cinco años"])],
  23: [("TFUE", "Artículo 263", [3], "artículo 263, párrafo tercero", ["el Tribunal de Cuentas, por el Banco Central Europeo y por el Comité de las Regiones"])],
  24: [("TFUE", "Artículo 288", [2, 3, 4, 5], "artículo 288, párrafos segundo a quinto", ["La decisión será obligatoria en todos sus elementos. Cuando designe destinatarios, sólo será obligatoria para éstos."])],
  26: [("TFUE", "Artículo 319", [1], "artículo 319.1", ["El Parlamento Europeo, por recomendación del Consejo, aprobará la gestión de la Comisión en la ejecución del presupuesto"])],
  28: [("TFUE", "Artículo 3", [1, 2, 3, 4, 5, 6], "artículo 3.1", ["la política comercial común"])],
  29: [("TFUE", "Artículo 82", [1], "artículo 82.1, párrafo primero", ["se basará en el principio de reconocimiento mutuo de las sentencias y resoluciones judiciales"])],
  102: [("FEMPA", "Artículo 25", [1], "artículo 25.1, párrafo primero", ["incluso en las aguas interiores"])],
  101: [("RD345", "a4", [1, 2, 3, 4, 5, 6, 7, 8], "artículo 4.1", ["dieciséis vocales"])],
  105: [("MUF", "dasexta", [4], "disposición adicional sexta.2", ["La totalidad de los bienes, derechos y acciones de las Mutualidades, Asociaciones y Montepíos aportados con su integración a la Mutualidad General de Funcionarios Civiles del Estado constituye un Fondo especial"])],
}

SI = {
  8:  [("Los consejeros permanentes", "LO3_1980", "acuarto", "Los Consejeros permanentes"),
       ("en numero igual al de las Secciones del Consejo", "LO3_1980", "aseptimo", "en numero igual al de las Secciones del Consejo"),
       ("sin límite de tiempo, por Real Decreto", "LO3_1980", "aseptimo", "sin límite de tiempo, por Real Decreto")],
  10: [("estrictamente castrense", "LOPJ", "atercero", "estrictamente castrense"),
       ("declaración del estado de sitio", "LOPJ", "atercero", "las materias que establezca la declaración del estado de sitio")],
  11: [("en cada departamento ministerial", "L40", "Artículo 55 bis", "en el ámbito de cada departamento ministerial"),
       ("no superen el 60%", "L40", "Artículo 55 bis", "no superen el sesenta por ciento"),
       ("menos del 40 %", "L40", "Artículo 55 bis", "sean menos del cuarenta por ciento")],
  12: [("registro público administrativo", "L40", "Artículo 82", "registro público administrativo"),
       ("Intervención General de la Administración del Estado", "L40", "Artículo 82", "dependerá de la Intervención General de la Administración del Estado")],
  16: [("declaración de lesividad", "LRBRL", "Artículo 22", "La declaración de lesividad de los actos del Ayuntamiento"),
       ("Asamblea vecinal en el régimen de Concejo Abierto", "LRBRL", "Artículo 22", "a la Asamblea vecinal en el régimen de Concejo Abierto")],
  32: [("Listado de las normas que quedan derogadas", "RD931", "a3", "listado de las normas que quedan derogadas")],
  33: [("15 de julio", "LO6_2013", "a17", "Antes del 15 de julio")],
  35: [("Semestralmente", "LGSS", "a125", "conocerá semestralmente")],
  36: [("Fondo de Suficiencia Global", "L22_2009", "preambulo", "El Fondo de Suficiencia Global opera como recurso de cierre del sistema")],
  37: [("Promover la digitalización del Sistema Nacional de Empleo y el desarrollo de herramientas digitales de apoyo a la labor de los servicios públicos de empleo",
        "RD633", "ci-3", "Objetivo operativo 5.2 Promover la digitalización del Sistema Nacional de Empleo y el desarrollo de herramientas digitales de apoyo a la labor de los servicios públicos de empleo")],
  40: [("Adjuntía a la Presidencia", "RD389", "a6", "suscrito por la persona titular de la Adjuntía a la Presidencia"),
       ("Subdirector General", "RD389", "a6", "o el Subdirector General o Director de División correspondiente"),
       ("Director de División", "RD389", "a6", "Director de División correspondiente")],
  41: [("tiempo de descanso", "LOPD", "Artículo 88", "el respeto de su tiempo de descanso"),
       ("intimidad personal y familiar", "LOPD", "Artículo 88", "de su intimidad personal y familiar"),
       ("fuera del tiempo de trabajo", "LOPD", "Artículo 88", "fuera del tiempo de trabajo")],
  42: [("De 38 a 64 horas mensuales", "RD1051", "anii", "Grado II: De 38 a 64 horas mensuales")],
  43: [("con el objetivo o la consecuencia de atentar contra la dignidad de una persona o grupo en que se integra y de crear un entorno intimidatorio, hostil, degradante, humillante u ofensivo",
        "L4_2023", "Artículo 3", "Acoso discriminatorio: Cualquier conducta realizada por razón de alguna de las causas de discriminación previstas en esta ley, con el objetivo o la consecuencia de atentar contra la dignidad de una persona o grupo en que se integra y de crear un entorno intimidatorio, hostil, degradante, humillante u ofensivo")],
  45: [("Agencia Estatal de Salud Pública", "L7_2025", "Artículo 1", "la creación de la Agencia Estatal de Salud Pública")],
  46: [("La Ley, la costumbre y los principios generales del derecho", "CC", "a1", "son la ley, la costumbre y los principios generales del derecho")],
  48: [("razones graves de interés público que lo justifiquen", "L39", "Artículo 133", "cuando concurran razones graves de interés público que lo justifiquen")],
  49: [("cualquier infracción del ordenamiento jurídico, incluso la desviación de poder", "L39", "Artículo 48", "incurran en cualquier infracción del ordenamiento jurídico, incluso la desviación de poder")],
  50: [("no sea posible fijar su precio de licitación", "LCSP", "Artículo 44", "por sus características no sea posible fijar su precio de licitación")],
  51: [("Con su adjudicación", "LCSP", "Artículo 36", "se perfeccionan con su adjudicación")],
  52: [("Los cinco últimos años", "LCSP", "Artículo 88", "en el curso de los cinco últimos años")],
  53: [("La Intervención General de la Administración del Estado", "LGS", "Artículo 20", "La Intervención General de la Administración del Estado es el órgano responsable de la administración y custodia de la BDNS")],
  54: [("Recurso de alzada ante el Ministerio correspondiente", "LEF", "aveintidos", "se dará recurso de alzada ante el Ministerio correspondiente")],
  55: [("La instrucción del procedimiento corresponderá a los Delegados de Economía y Hacienda", "LPAP", "Artículo 51", "La instrucción del procedimiento corresponderá a los Delegados de Economía y Hacienda")],
  56: [("seis meses", "L39", "Artículo 91", "Transcurridos seis meses desde que se inició el procedimiento")],
  57: [("diez días", "L39", "Artículo 73", "en el plazo de diez días a partir del siguiente al de la notificación del correspondiente acto")],
  58: [("actividades que puedan dañar el medio ambiente", "L39", "Artículo 24", "impliquen el ejercicio de actividades que puedan dañar el medio ambiente")],
  59: [("deberá remitirlo al competente en el plazo de diez días, con su informe y con una copia completa y ordenada del expediente", "L39", "Artículo 121",
        "éste deberá remitirlo al competente en el plazo de diez días, con su informe y con una copia completa y ordenada del expediente")],
  62: [("manifestada por escrito", "TREBEP", "Artículo 64", "habrá de ser manifestada por escrito"),
       ("aceptada expresamente por la Administración", "TREBEP", "Artículo 64", "será aceptada expresamente por la Administración")],
  63: [("Carrera horizontal", "TREBEP", "Artículo 16", "Carrera horizontal"), ("carrera vertical", "TREBEP", "Artículo 16", "Carrera vertical"),
       ("promoción interna vertical", "TREBEP", "Artículo 16", "Promoción interna vertical"), ("promoción interna horizontal", "TREBEP", "Artículo 16", "Promoción interna horizontal")],
  64: [("penalización", "TREBEP", "Artículo 96", "Demérito, que consistirá en la penalización"), ("movilidad voluntaria", "TREBEP", "Artículo 96", "promoción o movilidad voluntaria")],
  65: [("Tres años", "TREBEP", "Artículo 70", "dentro del plazo improrrogable de tres años")],
  66: [("A una o varias áreas funcionales", "RDL6", "Artículo 110", "estarán adscritos a una o varias áreas funcionales")],
  67: [("no pueden cubrirse de manera provisional", "RDL6", "Artículo 127", "sin que quepa la cobertura de carácter provisional"),
       ("personal directivo público profesional", "RDL6", "Artículo 123", "Tendrán la consideración de personal directivo público profesional las personas titulares de las subdirecciones generales")],
  68: [("Concursos unitarios", "RDL6", "Artículo 111", "convocará concursos unitarios, de carácter abierto y permanente")],
  70: [("salvo que en la corporación local desempeñe cargos retribuidos en régimen de dedicación exclusiva", "L53", "aquinto", "Miembros de las Corporaciones locales, salvo que desempeñen en las mismas cargos retribuidos en régimen de dedicación exclusiva")],
  71: [("Salvo casos excepcionales", "RD462", "a5", "salvo casos excepcionales"), ("un mes en territorio nacional y de tres en el extranjero", "RD462", "a5", "no durará más de un mes en territorio nacional y de tres en el extranjero")],
  72: [("Serán iguales en todas las Administraciones públicas, para cada uno de los grupos en que se clasifican los cuerpos, escalas, categorías o clases de funcionarios",
        "L30", "aveinticuatro", "serán iguales en todas las Administraciones públicas, para cada uno de los grupos en que se clasifican los cuerpos, escalas, categorías o clases de funcionarios")],
  74: [("Título de Bachiller o Técnico o equivalentes", "CONV", "a8", "Grupo profesional E2: Título de Bachiller o Técnico o equivalentes")],
  75: [("de personal", "CONV", "a8-7", "Los Delegados y Delegadas de personal")],
  76: [("La regulación y determinación concreta, en cada caso, de los sistemas, criterios, órganos y procedimientos de acceso al empleo público y la promoción profesional",
        "TREBEP", "Artículo 37", "La regulación y determinación concreta, en cada caso, de los sistemas, criterios, órganos y procedimientos de acceso al empleo público y la promoción profesional")],
  77: [("Los funcionarios en prácticas que aspiren a incorporarse a Cuerpos de la Administración Civil del Estado", "MUF", "a3",
        "Los funcionarios en prácticas que aspiren a incorporarse a Cuerpos de la Administración Civil del Estado")],
  78: [(None, "RD375", "Artículo 66", "así como el embarazo, el parto y el puerperio")],
  79: [("En el Régimen General de la Seguridad Social", "LGSS", "datercera", "en el Régimen General de la Seguridad Social siempre que el acceso a la condición de que se trate se produzca a partir de aquella fecha")],
  80: [("alteración del orden de prelación para la elección de las plazas dentro del ámbito territorial que se determine en la convocatoria", "RD2271", "a9",
        "la alteración del orden de prelación para la elección de las plazas dentro del ámbito territorial que se determine en la convocatoria"),
       ("dificultades de desplazamiento", "RD2271", "a9", "dificultades de desplazamiento")],
  81: [("asistente personal", "OPJC804", "a5", "Asistente personal")],
  83: [("equilibrio o superávit estructural", "LOEP", "a3", "la situación de equilibrio o superávit estructural")],
  85: [("Agrupa los créditos por capítulos separando las operaciones corrientes, las de capital, las financieras y el Fondo de Contingencia de ejecución presupuestaria", "LGP", "a40",
        "agrupará los créditos por capítulos separando las operaciones corrientes, las de capital, las financieras y el Fondo de Contingencia de ejecución presupuestaria")],
  87: [("hasta un importe del 10 %", "LGP", "a56", "hasta un importe del 10 %"), ("cuantía de 500.000 euros", "LGP", "a56", "cuando no supere la cuantía de 500.000 euros")],
  88: [("Cualquier acto o expediente que considere oportuno", "LGP", "a150bis", "podrá avocar para sí cualquier acto o expediente que considere oportuno")],
  89: [("Se transmiten a los causahabientes de los responsables por la aceptación expresa o tácita de la herencia", "LOTCu", "atreintayocho",
        "se transmiten a los causahabientes de los responsables por la aceptación expresa o tácita de la herencia"),
       ("importe líquido de la misma", "LOTCu", "atreintayocho", "importe líquido de la misma")],
  90: [("se declara la existencia de un crédito exigible contra la Hacienda Pública estatal", "LGP", "a73", "el acto mediante el que se declara la existencia de un crédito exigible contra la Hacienda Pública estatal")],
  91: [("documento OK", "OIOC", "regla23", "expedirá un documento OK")],
  93: [("compromiso de gasto imputables al presupuesto corriente", "ODOC", "sexto", "Documento D de ejercicio corriente: Se utilizará en las operaciones de compromiso de gasto imputables al Presupuesto corriente")],
  94: [("Artículo 23", "RES2014", "ai-4", "Artículo 23. Indemnizaciones por razón del servicio.")],
  95: [("El perceptor de la orden de pago a justificar", "LGP", "a79", "Los perceptores de las órdenes de pago a justificar son responsables, en los términos previstos en esta ley, de la custodia y uso de los fondos y de la rendición de la cuenta")],
  96: [("Capítulo", "LGP", "a43", "las inversiones reales a nivel de capítulo")],
  97: [("Contribuciones especiales", "LGT", "a2", "Contribuciones especiales son los tributos cuyo hecho imponible consiste en la obtención por el obligado tributario de un beneficio o de un aumento de valor de sus bienes")],
  98: [("Por Ley.", "L8_1989", "Artículo 10", "deberá realizarse con arreglo a Ley")],
  99: [("Complemento específico", "L30", "aveintitres", "El complemento específico destinado a retribuir las condiciones particulares de algunos puestos de trabajo en atención a su especial dificultad técnica, dedicación, responsabilidad, incompatibilidad, peligrosidad o penosidad")],
  19: [("dos años y medio", "TUE", "Artículo 15", "para un mandato de dos años y medio"), ("renovable una vez", "TUE", "Artículo 15", "que podrá renovarse una sola vez")],
  20: [("Comité de Representantes Permanentes", "TUE", "Artículo 16", "Un Comité de Representantes Permanentes de los Gobiernos de los Estados miembros se encargará de preparar los trabajos del Consejo")],
  21: [("Al menos un mes antes", "TFUE", "Artículo 249", "al menos un mes antes de la apertura del período de sesiones del Parlamento Europeo")],
  22: [("El Parlamento Europeo elegirá a su Presidente y a la Mesa de entre sus diputados", "TUE", "Artículo 14", "El Parlamento Europeo elegirá a su Presidente y a la Mesa de entre sus diputados")],
  24: [("Será obligatoria en todos sus elementos. Cuando designe destinatarios, sólo será obligatoria para éstos", "TFUE", "Artículo 288",
        "La decisión será obligatoria en todos sus elementos. Cuando designe destinatarios, sólo será obligatoria para éstos")],
  26: [("El Parlamento Europeo, por recomendación del Consejo, aprobará la gestión de la Comisión en la ejecución del presupuesto", "TFUE", "Artículo 319",
        "El Parlamento Europeo, por recomendación del Consejo, aprobará la gestión de la Comisión en la ejecución del presupuesto")],
  28: [("La política comercial común", "TFUE", "Artículo 3", "e) la política comercial común")],
  29: [("Reconocimiento mutuo de las sentencias y resoluciones judiciales", "TFUE", "Artículo 82", "se basará en el principio de reconocimiento mutuo de las sentencias y resoluciones judiciales")],
  102: [("incluso en las aguas interiores", "FEMPA", "Artículo 25", "El FEMPA podrá apoyar acciones que contribuyan a la protección y la recuperación de la biodiversidad y los ecosistemas acuáticos, incluso en las aguas interiores")],
  101: [("Dieciséis", "RD345", "a4", "formarán parte del mismo dieciséis vocales")],
  105: [("La totalidad de los bienes, derechos y acciones de las Mutualidades, Asociaciones y Montepíos aportados con su integración a la Mutualidad General de Funcionarios Civiles del Estado",
         "MUF", "dasexta", "La totalidad de los bienes, derechos y acciones de las Mutualidades, Asociaciones y Montepíos aportados con su integración a la Mutualidad General de Funcionarios Civiles del Estado constituye un Fondo especial")],
}

# Preguntas en negativo («NO es…», «NO debe contener…»): los tres distractores están literales
# en la norma y la opción correcta no.
NO = {
  23: ([("a", "comité de las regiones", "TFUE", "Artículo 263", "y por el Comité de las Regiones"),
        ("b", "banco central europeo", "TFUE", "Artículo 263", "recursos interpuestos por el Tribunal de Cuentas, por el Banco Central Europeo"),
        ("c", "tribunal de cuentas", "TFUE", "Artículo 263", "recursos interpuestos por el Tribunal de Cuentas")],
       ("comité económico y social", "TFUE", "Artículo 263")),
  38: ([("a", "conjunto de criterios objetivos", "LOEX", "Artículo 35 ter", "El conjunto de criterios objetivos para la determinación"),
        ("b", "mecanismo de derivación", "LOEX", "Artículo 35 ter", "La regulación del mecanismo de derivación"),
        ("c", "número de plazas", "LOEX", "Artículo 35 ter", "Los criterios para la determinación del número de plazas")],
       ("análisis de la situación de las familias", "LOEX", "Artículo 35 ter")),
  61: ([("b", "toma de posesión dentro del plazo que se establezca", "TREBEP", "Artículo 62", "Toma de posesión dentro del plazo que se establezca"),
        ("c", "acatamiento de la Constitución", "TREBEP", "Artículo 62", "Acto de acatamiento de la Constitución"),
        ("d", "nombramiento por el órgano o autoridad competente", "TREBEP", "Artículo 62", "Nombramiento por el órgano o autoridad competente")],
       ("firma del contrato", "TREBEP", "Artículo 62")),
  69: ([("a", "excedencia", "TREBEP", "Artículo 85", "d) Excedencia."), ("c", "servicios especiales", "TREBEP", "Artículo 85", "b) Servicios especiales."),
        ("d", "suspensión de funciones", "TREBEP", "Artículo 85", "e) Suspensión de funciones.")],
       ("comisión de servicios", "TREBEP", "Artículo 85")),
  73: ([("a", "desplazamientos dentro del término municipal por razón de servicio", "RD462", "a1", "Desplazamientos dentro del término municipal por razón de servicio"),
        ("c", "traslados de residencia", "RD462", "a1", "Traslados de residencia"),
        ("d", "colaboración en centros de formación y perfeccionamiento del personal de las administraciones públicas", "RD462", "a1", "la colaboración en centros de formación y perfeccionamiento del personal de las Administraciones públicas")],
       ("redistribución de efectivos", "RD462", "a1")),
  86: ([("a", "ampliaci", "LGP", "a51", "c) Ampliaciones."), ("b", "suplemento de crédito", "LGP", "a51", "Créditos extraordinarios y suplementos de crédito"),
        ("d", "incorporaci", "LGP", "a51", "e) Incorporaciones.")],
       ("plurianual", "LGP", "a51")),
}
