# -*- coding: utf-8 -*-
"""Texto legal LITERAL (BOE consolidado, API de datos abiertos; EUR-Lex para el
Derecho de la UE) de las preguntas del examen GACE-L 2025 EXTRAORDINARIO
(primer ejercicio) y comprobación plantilla ↔ ley de cada una.

Mismo formato que leyes25L.py (ver verif_examen.py):
LEY[n]   = [(norma, bloque, [párrafos], título, [negritas])]
SI[n]    = [(dato en la opción correcta | None, norma, bloque, fragmento literal de la ley)]
NO[n]    = pregunta en negativo: ([(letra, dato en ese distractor, norma, bloque, fragmento)],
            (fragmento de la opción correcta que NO está en la ley, norma, bloque))
TEMA[n]  = código del epígrafe del programa (solo si es seguro; si no, None).
SIN_LEY  = {n: motivo} preguntas que van sin texto legal.

Revisión manual (SI con dato None: no hay dato automático que discrimine):
  4  — Art. 55.1 CE: los derechos suspendibles en los estados de excepción o
       sitio se citan por número de artículo (17, 18.2 y 3, 19, 20.1 a) y d) y
       5, 21, 28.2 y 37.2). La libertad personal (art. 17, opción b) y el derecho
       de reunión (art. 21, opción d) están en la lista; el derecho a la vida y a
       la integridad física y moral (art. 15, opción a, la de la plantilla) no.
       La opción c (protección de la salud, art. 43) tampoco está en la lista,
       pero no es un derecho fundamental (capítulo III del título I, principios
       rectores) y la pregunta pregunta por «derechos fundamentales»: la
       plantilla (a) es coherente con la ley.
  92 — Art. 134.2 CE: los PGE «incluirán la totalidad de los gastos e ingresos
       del sector público estatal». Es la definición del enunciado; el nombre
       «universalidad» (opción c) es doctrinal y no aparece literal en la norma.
       Las otras opciones nombran otros principios (especialidad, anualidad,
       transparencia) que no responden a esa definición.
"""
from leyes25L import NOMBRE as _N

NOMBRE = dict(_N, RD466_2026="Real Decreto 466/2026, por el que se aprueba el Estatuto de MUFACE",
  CE="Constitución Española",
  LODP="Ley Orgánica 3/1981, del Defensor del Pueblo",
  LOTC="Ley Orgánica 2/1979, del Tribunal Constitucional",
  RCD="Reglamento del Congreso de los Diputados, de 10 de febrero de 1982",
  LJCA="Ley 29/1998, reguladora de la Jurisdicción Contencioso-administrativa",
  ET="Texto refundido de la Ley del Estatuto de los Trabajadores (RDLeg 2/2015)",
  RD203="Real Decreto 203/2021, Reglamento de actuación y funcionamiento del sector público por medios electrónicos",
  RD951="Real Decreto 951/2005, marco general para la mejora de la calidad en la Administración General del Estado",
  L7_2022="Ley 7/2022, de residuos y suelos contaminados para una economía circular",
  L20_2013="Ley 20/2013, de garantía de la unidad de mercado",
  RD556="Real Decreto 556/2011, para el desarrollo del Inventario Español del Patrimonio Natural y la Biodiversidad",
  L7_2021="Ley 7/2021, de cambio climático y transición energética",
  L3_2023="Ley 3/2023, de Empleo",
  L19_2013="Ley 19/2013, de transparencia, acceso a la información pública y buen gobierno",
  RD1372="Real Decreto 1372/1986, Reglamento de Bienes de las Entidades Locales",
  L23_1982="Ley 23/1982, reguladora del Patrimonio Nacional",
  RD364="Real Decreto 364/1995, Reglamento General de Ingreso del Personal al servicio de la Administración General del Estado y de Provisión de Puestos de Trabajo",
  RDL670="Texto refundido de Ley de Clases Pasivas del Estado (RDLeg 670/1987)",
  L15_2014="Ley 15/2014, de racionalización del Sector Público y otras medidas de reforma administrativa",
  RD2188="Real Decreto 2188/1995, régimen del control interno ejercido por la Intervención General de la Administración del Estado",
  RD246="Real Decreto 246/2024, estructura orgánica básica del Ministerio de Igualdad",
  REFUG="Convención sobre el Estatuto de los Refugiados, hecha en Ginebra el 28 de julio de 1951 (Instrumento de Adhesión de España)",
  RGPD="Reglamento (UE) 2016/679, general de protección de datos (DOUE L 119 de 4-5-2016)",
  MFP="Reglamento (UE, Euratom) 2020/2093, marco financiero plurianual 2021-2027 (DOUE L 433I de 22-12-2020)",
  PROT13="Protocolo (n.º 13) sobre los criterios de convergencia, anejo al TUE y al TFUE (DOUE C 202 de 7-6-2016)",
)

LEY = {
  1:  [("CE", "tviii", [0, 1], "título VIII", ["De la Organización Territorial del Estado"])],
  3:  [("CE", "preambulo", [10], "preámbulo", ["las Cortes aprueban y el pueblo español ratifica"])],
  4:  [("CE", "a55", [1], "artículo 55.1", ["Los derechos reconocidos en los artículos 17, 18, apartados 2 y 3, artículos 19, 20, apartados 1, a) y d), y 5, artículos 21, 28, apartado 2, y artículo 37, apartado 2, podrán ser suspendidos"]),
       ("CE", "a15", [1], "artículo 15", ["Todos tienen derecho a la vida y a la integridad física y moral"])],
  5:  [("LODP", "atreinta", [1], "artículo treinta.uno", ["vendrán obligados a responder por escrito en término no superior al de un mes"])],
  6:  [("CE", "a54", [1], "artículo 54", ["Defensor del Pueblo", "podrá supervisar la actividad de la Administración"]),
       ("LODP", "aprimero", [1], "artículo primero", ["para la defensa de los derechos comprendidos en el Título I de la Constitución"])],
  7:  [("CE", "a162", [1, 2], "artículo 162.1 a)", ["el Presidente del Gobierno, el Defensor del Pueblo, 50 Diputados, 50 Senadores, los órganos colegiados ejecutivos de las Comunidades Autónomas y, en su caso, las Asambleas de las mismas"])],
  8:  [("CE", "a161", [6], "artículo 161.2", ["La impugnación producirá la suspensión de la disposición o resolución recurrida", "en un plazo no superior a cinco meses"])],
  9:  [("LOTC", "aveintisiete", [2, 3, 4, 5, 6, 7, 8], "artículo veintisiete.dos", ["Los Estatutos de Autonomía", "Los Tratados Internacionales", "Los Reglamentos de las Cámaras y de las Cortes Generales"])],
  10: [("CE", "a57", [1], "artículo 57.1", ["en el mismo sexo, la persona de más edad a la de menos"])],
  11: [("CE", "a61", [1, 2], "artículo 61", ["El Rey, al ser proclamado ante las Cortes Generales", "El Príncipe heredero, al alcanzar la mayoría de edad", "el Regente o Regentes al hacerse cargo de sus funciones"])],
  12: [("CE", "a70", [1, 2, 3, 4, 5, 6, 7], "artículo 70.1", ["con la excepción de los miembros del Gobierno"])],
  13: [("RCD", "art2", [1], "artículo 2", ["la diputada o diputado electos de mayor edad", "con la asistencia de los dos más jóvenes"])],
  14: [("CE", "a69", [3], "artículo 69.3", ["correspondiendo tres a cada una de las islas mayores −Gran Canaria, Mallorca y Tenerife−"])],
  15: [("CE", "a113", [1], "artículo 113.1", ["mediante la adopción por mayoría absoluta de la moción de censura"])],
  16: [("LO3_1980", "atrece", [1, 2], "artículo trece.1 y 2", ["serán ocho como mínimo", "de un Consejero permanente que la preside"])],
  17: [("LO3_1980", "aoctavo", [4, 7], "artículo octavo.2 c)", ["Serán Consejeros natos de Estado", "El Fiscal General del Estado"])],
  18: [("LOPJ", "asesentaycuatrobis", [1], "artículo 64 bis.1", ["contra las resoluciones de la Sala de lo Penal"])],
  19: [("CE", "a124", [2], "artículo 124.2", ["unidad de actuación y dependencia jerárquica", "legalidad e imparcialidad"])],
  20: [("L40", "Artículo 9", [2, 10], "artículo 9.1, párrafo segundo, y 9.4", ["Las resoluciones administrativas que se adopten por delegación indicarán expresamente esta circunstancia y se considerarán dictadas por el órgano delegante"])],
  21: [("L40", "Artículo 120", [12], "artículo 120.4", ["en un plazo no superior a seis meses"])],
  22: [("L40", "Artículo 84", [1, 7, 9], "artículo 84.1 c) y e)", ["e) Las fundaciones del sector público."]),
       ("L40", "Artículo 130", [1], "artículo 130", ["por la Ley 50/2002, de 26 de diciembre, de Fundaciones"])],
  23: [("CE", "a139", [1], "artículo 139.1", ["Todos los españoles tienen los mismos derechos y obligaciones en cualquier parte del territorio del Estado"])],
  24: [("CE", "a153", [1, 3], "artículo 153 b)", ["Por el Gobierno, previo dictamen del Consejo de Estado"])],
  25: [("LRBRL", "Artículo 43", [2], "artículo 43.2", ["Las áreas metropolitanas son entidades locales"])],
  26: [("CE", "a141", [1], "artículo 141.1", ["habrá de ser aprobada por las Cortes Generales mediante ley orgánica"])],
  27: [("LRBRL", "Artículo 25", [2, 10, 18], "artículo 25.2 h) y o)", ["o) Actuaciones en la promoción de la igualdad entre hombres y mujeres así como contra la violencia de género."])],
  28: [("TFUE", "Artículo 328", [3], "artículo 328.2", ["La Comisión y, en su caso, el Alto Representante de la Unión para Asuntos Exteriores y Política de Seguridad informarán periódicamente al Parlamento Europeo y al Consejo"])],
  29: [("TUE", "Artículo 20", [1, 3], "artículo 20.1 y 2", ["en el marco de las competencias no exclusivas de la Unión", "al menos nueve Estados miembros"]),
       ("TFUE", "Artículo 329", [1, 3], "artículo 329.1 y 2", ["dirigirán a la Comisión una solicitud", "se dirigirá al Consejo"])],
  30: [("TUE", "Artículo 48", [2], "artículo 48.2", ["El Gobierno de cualquier Estado miembro, el Parlamento Europeo o la Comisión"])],
  32: [("TUE", "Artículo 15", [3, 4, 12], "artículo 15.3, 4 y 6", ["El Consejo Europeo se pronunciará por consenso, excepto cuando los Tratados dispongan otra cosa.", "dos veces por semestre", "no podrá ejercer mandato nacional alguno"])],
  34: [("TUE", "Artículo 5", [2, 3], "artículo 5.2 y 3", ["la Unión actúa dentro de los límites de las competencias que le atribuyen los Estados miembros en los Tratados", "Toda competencia no atribuida a la Unión en los Tratados corresponde a los Estados miembros"])],
  35: [("MFP", "Artículo 1", [1], "artículo 1", ["para los ejercicios 2021 a 2027"]),
       ("TFUE", "Artículo 312", [1, 2], "artículo 312.1", ["período mínimo de cinco años"]),
       ("TFUE", "Artículo 314", [1, 2], "artículo 314, párrafo primero, y 314.1", ["procedimiento legislativo especial", "excepto el Banco Central Europeo"])],
  36: [("TUE", "Artículo 5", [1], "artículo 5.1", ["subsidiariedad y proporcionalidad"])],
  37: [("PROT13", "Artículo 1", [1], "artículo 1", ["comportamiento de precios sostenible", "1½ punto porcentual"]),
       ("PROT13", "Artículo 2", [1], "artículo 2", ["déficit excesivo"]),
       ("PROT13", "Artículo 3", [1], "artículo 3", ["durante por lo menos los dos años anteriores al examen"]),
       ("PROT13", "Artículo 4", [1], "artículo 4", ["que no exceda en más de 2 puntos porcentuales"])],
  38: [("RD931", "a3", [2], "artículo 3.2 (memoria abreviada)", ["impacto presupuestario y por razón de género, así como otros impactos detectados que se juzguen relevantes"])],
  40: [("L7_2022", "a2-7", [3, 4, 5, 6, 7, 8, 9, 10], "artículo 25.2", ["El papel, los metales, el plástico y el vidrio", "los biorresiduos de origen doméstico"])],
  41: [("L20_2013", "a10", [2], "artículo 10.2", ["estará presidida por la persona titular del Ministerio"])],
  42: [("RD556", "a5", [1, 2, 3, 4], "artículo 5", ["Componentes que se gestionarán en un sistema integrado de información", "Indicadores", "Informe anual"])],
  43: [("L7_2021", "a4", [1], "artículo 4.1", ["El Plan Nacional Integrado de Energía y Clima (PNIEC) es la herramienta de planificación estratégica nacional"])],
  45: [("L3_2023", "a1-5", [6, 7, 9, 10, 11, 12, 13], "artículo 13.3", ["f) Eje 6."])],
  46: [("REFUG", "a46", [10], "artículo 46, fórmula final", ["Hecha en Ginebra el día 28 de julio de 1951"])],
  47: [("ET", "a49", [20, 26], "artículo 49.1 n)", ["cuando no sea posible realizar los ajustes razonables por constituir una carga excesiva para la empresa, cuando no exista un puesto de trabajo vacante y disponible"])],
  48: [("L19_2013", "a37", [1], "artículo 37.1", ["El Congreso, a través de la Comisión competente y por acuerdo adoptado por mayoría absoluta, deberá refrendar el nombramiento del candidato propuesto"])],
  49: [("RGPD", "Artículo 20", [1, 4], "artículo 20.1 y 2", ["derecho a la portabilidad de los datos"])],
  50: [("LOPD", "Artículo 34", [20], "artículo 34.3", ["en el plazo de diez días"])],
  51: [("RD246", "a2", [22, 23], "artículo 2.3 a)", ["con rango de dirección general", "La Delegación del Gobierno contra la Violencia de Género"])],
  52: [("L4_2023", "Artículo 15", [1], "artículo 15.1", ["Las empresas de más de cincuenta personas trabajadoras"])],
  54: [("LCSP", "Artículo 244", [1], "artículo 244.1", ["durante un plazo de quince años a contar desde la recepción"])],
  55: [("LCSP", "Artículo 243", [2, 3], "artículo 243.1, párrafos segundo y tercero", ["Dentro del plazo de tres meses", "podrá ser ampliado, siempre que no supere en ningún caso los cinco meses"])],
  56: [("LCSP", "Artículo 103", [15], "artículo 103.8", ["El Instituto Nacional de Estadística elaborará los índices mensuales de los precios de los componentes básicos de costes"])],
  57: [("LCSP", "Artículo 247", [1], "artículo 247.1", ["acordará la realización de un estudio de viabilidad"])],
  58: [("LEF", "atercero", [1], "artículo tercero.1", ["en primer lugar, con el propietario de la cosa o titular del derecho objeto de la expropiación"])],
  59: [("RD1372", "art100", [1], "artículo 100.1", ["durante más de diez años"])],
  60: [("LPAP", "dacuarta", [1], "disposición adicional cuarta", ["aplicándose con carácter supletorio las disposiciones de esta ley y sus normas de desarrollo"]),
       ("LPAP", "ddunica", [1, 2], "disposición derogatoria única a)", ["Texto Articulado, aprobado por Decreto 1022/1964, de 15 de abril"]),
       ("L23_1982", "asexto", [1], "artículo sexto.uno (texto no actualizado tras la derogación de la Ley del Patrimonio del Estado)", ["Se aplicará, con carácter supletorio, la Ley del Patrimonio del Estado."])],
  61: [("L40", "Artículo 32", [2], "artículo 32.1, párrafo segundo", ["no presupone, por sí misma, derecho a la indemnización"])],
  62: [("L39", "Artículo 71", [1], "artículo 71.1", ["sometido al principio de celeridad"])],
  63: [("LJCA", "a28", [1], "artículo 28", ["No es admisible", "reproducción de otros anteriores definitivos y firmes y los confirmatorios de actos consentidos"]),
       ("LJCA", "a25", [1, 2], "artículo 25", ["es admisible", "También es admisible"])],
  64: [("L39", "Artículo 53", [4], "artículo 53.1 b)", ["A identificar a las autoridades y al personal al servicio de las Administraciones Públicas"])],
  65: [("CE", "a153", [1, 4], "artículo 153 c)", ["Por la jurisdicción contencioso-administrativa"])],
  66: [("RD364", "a26", [1, 2], "artículo 26.1", ["Estos destinos tendrán carácter definitivo"]),
       ("RD364", "a59", [3], "artículo 59.1, párrafo tercero", ["tendrá asimismo carácter definitivo"]),
       ("RD364", "a66ter", [4], "artículo 66 ter.2, párrafo segundo", ["La adscripción tendrá carácter definitivo"]),
       ("RD364", "a36", [3], "artículo 36.3", ["Temporalmente podrán ser cubiertos mediante comisión de servicios"]),
       ("RD364", "a64", [1], "artículo 64.1", ["en comisión de servicios de carácter voluntario"])],
  67: [("TREBEP", "Artículo 10", [1, 2, 3, 4, 5], "artículo 10.1", ["La sustitución transitoria de los titulares, durante el tiempo estrictamente necesario."])],
  68: [("TREBEP", "Artículo 15", [1, 2], "artículo 15 a)", ["A la libertad sindical."])],
  69: [("TREBEP", "Artículo 48", [8, 9], "artículo 48 e)", ["por las funcionarias embarazadas", "incluye también a las personas funcionarias trans gestantes"])],
  70: [("TREBEP", "Artículo 55", [2, 3], "artículo 55.2 a)", ["seleccionarán a su personal funcionario y laboral", "Publicidad de las convocatorias y de sus bases"]),
       ("TREBEP", "Artículo 10", [6], "artículo 10.2", ["Los procedimientos de selección del personal funcionario interino serán públicos"]),
       ("TREBEP", "Artículo 11", [3], "artículo 11.3", ["Los procedimientos de selección del personal laboral serán públicos"])],
  71: [("RDL6", "Artículo 127", [1], "artículo 127.1, párrafo primero", ["sin que quepa la cobertura de carácter provisional"])],
  72: [("RDL6", "Artículo 108", [3], "artículo 108.2, párrafo segundo", ["Las convocatorias deberán ejecutarse en el plazo máximo de dos años desde su publicación, y las respectivas fases de oposición en un año, salvo causa justificada"])],
  73: [("RD364", "a58", [3, 4], "artículo 58.2", ["no inferior en más de dos niveles al de su grado personal en el mismo municipio", "no será de aplicación cuando se trate del cese de funcionarios destinados en el exterior"])],
  74: [("RD364", "a70", [8, 10], "artículo 70.6", ["el tiempo prestado en comisión de servicios será computable para consolidar el grado correspondiente al puesto desempeñado siempre que se obtenga con carácter definitivo dicho puesto u otro de igual o superior nivel"])],
  75: [("RDL6", "Artículo 108", [5], "artículo 108.3", ["un porcentaje no inferior al treinta por ciento de las plazas de acceso libre para promoción interna"])],
  76: [("RDL6", "Artículo 127", [2], "artículo 127.1, párrafo segundo", ["El plazo máximo de presentación de solicitudes será de diez días naturales desde la publicación de la convocatoria"])],
  77: [("TREBEP", "Artículo 85", [1, 2, 3, 4, 5, 6], "artículo 85.1", ["Servicio activo", "Servicios especiales", "Excedencia"])],
  78: [("L53", "aseptimo", [1, 2], "artículo séptimo.1", ["Un 30 por 100, para los funcionarios del grupo A o personal de nivel equivalente"])],
  79: [("RD462", "a5", [1], "artículo 5.1", ["salvo casos excepcionales, no durará más de un mes en territorio nacional y de tres en el extranjero"])],
  80: [("RD462", "a12", [4, 5, 6, 7], "artículo 12.3", ["En el día de salida se podrán percibir gastos de alojamiento pero no gastos de manutención", "dietas al 100 por 100"])],
  81: [("TREBEP", "Artículo 61", [10], "artículo 61.7", ["Los sistemas selectivos de personal laboral fijo serán los de oposición, concurso-oposición", "o concurso de valoración de méritos"])],
  82: [("CONV", "a2", [1, 2], "artículo 2 a)", ["El personal laboral que presta servicios en el exterior."]),
       ("CONV", "a1", [5, 6, 7], "artículo 1.2 c), d) y e)", ["El Consejo de Seguridad Nuclear", "La Agencia Española de Protección de Datos", "El Museo Nacional Centro de Arte Reina Sofía"])],
  83: [("TREBEP", "Artículo 42", [1], "artículo 42", ["será de cuatro años, pudiendo ser reelegidos"])],
  84: [("TREBEP", "Artículo 37", [15, 18], "artículo 37.2 b)", ["Quedan excluidas de la obligatoriedad de la negociación", "La regulación del ejercicio de los derechos de los ciudadanos y de los usuarios de los servicios públicos, así como el procedimiento de formación de los actos y disposiciones administrativas"])],
  86: [("MUF", "a18", [1, 3], "artículo 18.1 y 2", ["Tendrán la consideración de estados o situaciones determinantes de la incapacidad temporal", "no tendrán la consideración de incapacidad temporal"])],
  87: [("RDL670", "a11", [1], "artículo 11.1", ["corresponde al Instituto Nacional de la Seguridad Social"])],
  88: [("RDL6", "Artículo 113", [3], "artículo 113.3", ["igual o superior al treinta y tres por cien"])],
  89: [("RCD", "art79", [1], "artículo 79.1", ["deberán ser aprobados por la mayoría simple de los miembros presentes"]),
       ("CE", "a134", [1], "artículo 134.1", ["a las Cortes Generales, su examen, enmienda y aprobación"])],
  90: [("LOEP", "a2", [1, 2, 3, 4, 5, 6], "artículo 2.1", ["Administración central, que comprende el Estado y los organismos de la administración central", "Comunidades Autónomas", "Corporaciones Locales", "Administraciones de Seguridad Social"])],
  92: [("CE", "a134", [2], "artículo 134.2", ["incluirán la totalidad de los gastos e ingresos del sector público estatal"])],
  93: [("L15_2014", "a22", [4, 5, 6, 7], "artículo 22.Dos (disposición adicional undécima de la Ley 7/1988)", ["emitirá su informe en el plazo improrrogable de treinta días", "el plazo será de quince días"])],
  94: [("RD2188", "a35", [1], "artículo 35.1", ["El control financiero se ejercerá mediante auditorías u otras técnicas de control"])],
  95: [("ODOC", "sexto", [3], "apartado sexto b)", ["Documento de desglose: Se utilizará en las operaciones de desglose de las aplicaciones presupuestarias"])],
  98: [("TREBEP", "Artículo 29", [1, 2], "artículo 29", ["tendrán a todos los efectos la consideración de retribución diferida"])],
  99: [("TREBEP", "Artículo 30", [1], "artículo 30.1", ["que no tendrá carácter sancionador"])],
  101: [("LOEX", "Artículo 68", [1], "artículo 68.1", ["La Conferencia Sectorial de Inmigración es el órgano a través del cual se asegurará la adecuada coordinación"])],
  102: [("RD203", "a4-6", [1, 2, 6], "artículo 44.1, 2 y 4", ["La Dirección Electrónica Habilitada única es el sistema de información para la notificación electrónica", "sede electrónica del PAGe", "una ampliación del plazo no vencido"]),
        ("RD203", "a4-4", [5], "artículo 42.3, párrafo segundo", ["la identificación del acto notificado"])],
  103: [("RD951", "a9", [9, 10, 14, 15, 16], "artículo 9 b)", ["De compromisos de calidad", "Niveles o estándares de calidad que se ofrecen", "Medidas que aseguren la igualdad de género", "Indicadores utilizados para la evaluación de la calidad"])],
  104: [("RD2271", "a3", [3], "artículo 3.2, párrafo segundo", ["las plazas no cubiertas se acumularán al cupo del cinco por ciento de la oferta siguiente, con un límite máximo del 10 por ciento"])],
  105: [("LOPJ", "acientoochentaytres", [1], "artículo 183", ["todos los días desde el 24 de diciembre hasta el 6 de enero del año siguiente, ambos inclusive"]),
        ("LOPJ", "acientoochentaydos", [3], "artículo 182.2", ["desde las ocho de la mañana a las ocho de la tarde"]),
        ("LOPJ", "acientoochentaycinco", [1], "artículo 185.1", ["quedarán excluidos los inhábiles"])],
}

SI = {
  1:  [("De la Organización Territorial del Estado", "CE", "tviii", "De la Organización Territorial del Estado")],
  3:  [("Las Cortes aprueban y el pueblo español ratifica", "CE", "preambulo", "las Cortes aprueban y el pueblo español ratifica la siguiente")],
  4:  [(None, "CE", "a55", "Los derechos reconocidos en los artículos 17, 18, apartados 2 y 3, artículos 19, 20, apartados 1, a) y d), y 5, artículos 21, 28, apartado 2, y artículo 37, apartado 2, podrán ser suspendidos")],
  5:  [("Un mes", "LODP", "atreinta", "vendrán obligados a responder por escrito en término no superior al de un mes")],
  6:  [("Defensor del Pueblo", "CE", "a54", "la institución del Defensor del Pueblo, como alto comisionado de las Cortes Generales, designado por éstas para la defensa de los derechos comprendidos en este Título, a cuyo efecto podrá supervisar la actividad de la Administración")],
  7:  [("el Presidente del Gobierno, el Defensor del Pueblo, 50 Diputados, 50 Senadores, los órganos colegiados ejecutivos de las Comunidades Autónomas y, en su caso, las Asambleas de las mismas", "CE", "a162",
        "Para interponer el recurso de inconstitucionalidad, el Presidente del Gobierno, el Defensor del Pueblo, 50 Diputados, 50 Senadores, los órganos colegiados ejecutivos de las Comunidades Autónomas y, en su caso, las Asambleas de las mismas")],
  8:  [("Produce la suspensión", "CE", "a161", "La impugnación producirá la suspensión de la disposición o resolución recurrida"),
       ("5 meses", "CE", "a161", "deberá ratificarla o levantarla en un plazo no superior a cinco meses")],
  10: [("En el mismo sexo, la persona de más edad a la de menos", "CE", "a57", "y en el mismo sexo, la persona de más edad a la de menos")],
  12: [("miembro del Gobierno", "CE", "a70", "A los altos cargos de la Administración del Estado que determine la ley, con la excepción de los miembros del Gobierno")],
  13: [("electo de mayor edad", "RCD", "art2", "presidida inicialmente por la diputada o diputado electos de mayor edad presente en la Cámara"),
       ("dos más jóvenes", "RCD", "art2", "con la asistencia de los dos más jóvenes, que ocuparán las Secretarías")],
  14: [("Gran Canaria, Mallorca y Tenerife", "CE", "a69", "correspondiendo tres a cada una de las islas mayores −Gran Canaria, Mallorca y Tenerife−")],
  15: [("mayoría absoluta", "CE", "a113", "mediante la adopción por mayoría absoluta de la moción de censura")],
  16: [("Ocho", "LO3_1980", "atrece", "Las Secciones del Consejo serán ocho como mínimo"),
       ("Consejero permanente", "LO3_1980", "atrece", "Cada Sección del Consejo de Estado se compone de un Consejero permanente que la preside")],
  17: [("Fiscal General del Estado", "LO3_1980", "aoctavo", "c) El Fiscal General del Estado.")],
  18: [("Sala de lo Penal", "LOPJ", "asesentaycuatrobis", "La Sala de Apelación de la Audiencia Nacional conocerá de los recursos de esta clase que establezca la ley contra las resoluciones de la Sala de lo Penal")],
  19: [("actuación, dependencia jerárquica", "CE", "a124", "conforme a los principios de unidad de actuación y dependencia jerárquica"),
       ("legalidad e imparcialidad", "CE", "a124", "con sujeción, en todo caso, a los de legalidad e imparcialidad")],
  20: [("se considerarán dictadas por el órgano delegante", "L40", "Artículo 9", "Las resoluciones administrativas que se adopten por delegación indicarán expresamente esta circunstancia y se considerarán dictadas por el órgano delegante")],
  21: [("Seis meses", "L40", "Artículo 120", "conllevará la modificación de los estatutos del consorcio en un plazo no superior a seis meses")],
  22: [("fundaciones del sector público", "L40", "Artículo 84", "e) Las fundaciones del sector público."),
       ("Ley de Fundaciones", "L40", "Artículo 130", "Las fundaciones del sector público estatal se rigen por lo previsto en esta Ley, por la Ley 50/2002, de 26 de diciembre, de Fundaciones")],
  23: [("igualdad de derechos y obligaciones de todos los españoles", "CE", "a139", "Todos los españoles tienen los mismos derechos y obligaciones en cualquier parte del territorio del Estado")],
  24: [("El Gobierno, previo dictamen del Consejo de Estado", "CE", "a153", "Por el Gobierno, previo dictamen del Consejo de Estado, el del ejercicio de funciones delegadas a que se refiere el apartado 2 del artículo 150")],
  25: [("área metropolitana", "LRBRL", "Artículo 43",
        "Las áreas metropolitanas son entidades locales integradas por los Municipios de grandes aglomeraciones urbanas entre cuyos núcleos de población existan vinculaciones económicas y sociales que hagan necesaria la planificación conjunta y la coordinación de determinados servicios y obras")],
  26: [("Cortes Generales mediante ley orgánica", "CE", "a141", "Cualquier alteración de los límites provinciales habrá de ser aprobada por las Cortes Generales mediante ley orgánica")],
  27: [("promoción de la igualdad entre hombres y mujeres así como contra la violencia de género", "LRBRL", "Artículo 25", "o) Actuaciones en la promoción de la igualdad entre hombres y mujeres así como contra la violencia de género.")],
  28: [("La Comisión y, en su caso, el Alto Representante de la Unión para Asuntos Exteriores y Política de Seguridad informarán periódicamente al Parlamento Europeo y al Consejo", "TFUE", "Artículo 328",
        "La Comisión y, en su caso, el Alto Representante de la Unión para Asuntos Exteriores y Política de Seguridad informarán periódicamente al Parlamento Europeo y al Consejo sobre la evolución de las cooperaciones reforzadas")],
  29: [("al menos nueve Estados miembros", "TUE", "Artículo 20", "a condición de que participen en ella al menos nueve Estados miembros")],
  30: [("El Gobierno de cualquier Estado miembro, el Parlamento Europeo o la Comisión", "TUE", "Artículo 48",
        "El Gobierno de cualquier Estado miembro, el Parlamento Europeo o la Comisión podrán presentar al Consejo proyectos de revisión de los Tratados")],
  32: [("Se pronunciará por consenso, excepto cuando los Tratados dispongan otra cosa", "TUE", "Artículo 15", "El Consejo Europeo se pronunciará por consenso, excepto cuando los Tratados dispongan otra cosa")],
  34: [("competencias que le atribuyen los Estados miembros en los Tratados", "TUE", "Artículo 5",
        "En virtud del principio de atribución, la Unión actúa dentro de los límites de las competencias que le atribuyen los Estados miembros en los Tratados")],
  35: [("2021-2027", "MFP", "Artículo 1", "El presente Reglamento establece el marco financiero plurianual para los ejercicios 2021 a 2027 (MFP).")],
  36: [("Subsidiariedad y proporcionalidad", "TUE", "Artículo 5", "El ejercicio de las competencias de la Unión se rige por los principios de subsidiariedad y proporcionalidad")],
  38: [("presupuestario y por razón de género, así como otros impactos detectados que se juzguen relevantes", "RD931", "a3",
        "impacto presupuestario y por razón de género, así como otros impactos detectados que se juzguen relevantes")],
  40: [("Papel, metales, plástico, vidrio", "L7_2022", "a2-7", "a) El papel, los metales, el plástico y el vidrio,"),
       ("biorresiduos", "L7_2022", "a2-7", "b) los biorresiduos de origen doméstico")],
  41: [("La persona titular del Ministerio", "L20_2013", "a10", "La Conferencia Sectorial para la Mejora Regulatoria y el Clima de Negocios estará presidida por la persona titular del Ministerio")],
  42: [("sistema integrado de información", "RD556", "a5", "a) Componentes que se gestionarán en un sistema integrado de información."),
       ("indicadores", "RD556", "a5", "b) Indicadores que permitan analizar sintéticamente sus principales características."),
       ("informe anual", "RD556", "a5", "c) Informe anual sobre el estado y evolución del Patrimonio Natural y de la Biodiversidad.")],
  43: [("Plan Nacional Integrado de Energía y Clima", "L7_2021", "a4",
        "El Plan Nacional Integrado de Energía y Clima (PNIEC) es la herramienta de planificación estratégica nacional que integra la política de energía y clima")],
  45: [("Seis", "L3_2023", "a1-5", "f) Eje 6. Mejora del marco institucional.")],
  46: [("Ginebra, en 1951", "REFUG", "a46", "Hecha en Ginebra el día 28 de julio de 1951")],
  47: [("posibilidad de adaptación o recolocación", "ET", "a49",
        "Por declaración de gran incapacidad, incapacidad permanente absoluta o total de la persona trabajadora, sin perjuicio de lo dispuesto en el artículo 48.2, cuando no sea posible realizar los ajustes razonables por constituir una carga excesiva para la empresa, cuando no exista un puesto de trabajo vacante y disponible")],
  48: [("Congreso de los Diputados", "L19_2013", "a37", "El Congreso, a través de la Comisión competente"),
       ("mayoría absoluta", "L19_2013", "a37", "por acuerdo adoptado por mayoría absoluta, deberá refrendar el nombramiento del candidato propuesto")],
  49: [("portabilidad de los datos", "RGPD", "Artículo 20", "Al ejercer su derecho a la portabilidad de los datos de acuerdo con el apartado 1")],
  50: [("Diez días", "LOPD", "Artículo 34", "comunicarán en el plazo de diez días a la Agencia Española de Protección de Datos")],
  51: [("De Dirección General", "RD246", "a2", "dependen los siguientes órganos directivos, con rango de dirección general")],
  52: [("más de cincuenta personas trabajadoras", "L4_2023", "Artículo 15", "Las empresas de más de cincuenta personas trabajadoras deberán contar")],
  54: [("Quince años", "LCSP", "Artículo 244", "durante un plazo de quince años a contar desde la recepción")],
  55: [("Tres meses", "LCSP", "Artículo 243", "el plazo de tres meses para la aprobación de la certificación final"),
       ("cinco meses", "LCSP", "Artículo 243", "podrá ser ampliado, siempre que no supere en ningún caso los cinco meses")],
  56: [("Instituto Nacional de Estadística", "LCSP", "Artículo 103", "El Instituto Nacional de Estadística elaborará los índices mensuales de los precios de los componentes básicos de costes incluidos en las fórmulas tipo de revisión de precios de los contratos")],
  57: [("Estudio de viabilidad", "LCSP", "Artículo 247", "acordará la realización de un estudio de viabilidad de las mismas")],
  58: [("Con el propietario de la cosa o titular del derecho objeto de la expropiación", "LEF", "atercero",
        "Las actuaciones del expediente expropiatorio se entenderán, en primer lugar, con el propietario de la cosa o titular del derecho objeto de la expropiación")],
  59: [("Diez años", "RD1372", "art100", "no han sido objeto de disfrute de esta índole durante más de diez años")],
  60: [("Ley 33/2003", "LPAP", "dacuarta", "aplicándose con carácter supletorio las disposiciones de esta ley y sus normas de desarrollo")],
  61: [("no presupone, por sí misma, derecho a la indemnización", "L40", "Artículo 32",
        "La anulación en vía administrativa o por el orden jurisdiccional contencioso administrativo de los actos o disposiciones administrativas no presupone, por sí misma, derecho a la indemnización")],
  62: [("celeridad", "L39", "Artículo 71", "El procedimiento, sometido al principio de celeridad")],
  63: [("reproducción de otros anteriores definitivos y firmes", "LJCA", "a28",
        "No es admisible el recurso contencioso-administrativo respecto de los actos que sean reproducción de otros anteriores definitivos y firmes y los confirmatorios de actos consentidos por no haber sido recurridos en tiempo y forma")],
  64: [("identificación", "L39", "Artículo 53", "b) A identificar a las autoridades y al personal al servicio de las Administraciones Públicas bajo cuya responsabilidad se tramiten los procedimientos")],
  65: [("jurisdicción contencioso-administrativa", "CE", "a153", "c) Por la jurisdicción contencioso-administrativa, el de la administración autónoma y sus normas reglamentarias")],
  66: [("comisión de servicios", "RD364", "a36", "Temporalmente podrán ser cubiertos mediante comisión de servicios y adscripción provisional")],
  67: [("Sustitución transitoria de los titulares, durante el tiempo estrictamente necesario", "TREBEP", "Artículo 10", "b) La sustitución transitoria de los titulares, durante el tiempo estrictamente necesario.")],
  68: [("libertad sindical", "TREBEP", "Artículo 15", "a) A la libertad sindical.")],
  69: [("funcionarias embarazadas", "TREBEP", "Artículo 48", "exámenes prenatales y técnicas de preparación al parto por las funcionarias embarazadas"),
       ("personas funcionarias trans gestantes", "TREBEP", "Artículo 48", "el término de funcionarias embarazadas incluye también a las personas funcionarias trans gestantes")],
  70: [("de carrera o interino, o de personal laboral", "TREBEP", "Artículo 10", "Los procedimientos de selección del personal funcionario interino serán públicos")],
  71: [("No cabe en ningún caso", "RDL6", "Artículo 127", "se realizará en todo caso por el procedimiento de libre designación, con las especialidades previstas en este artículo y las normas de adaptación a que se refiere el artículo 125.2, sin que quepa la cobertura de carácter provisional")],
  72: [("plazo máximo de dos años desde su publicación, y las respectivas fases de oposición en un año", "RDL6", "Artículo 108",
        "Las convocatorias deberán ejecutarse en el plazo máximo de dos años desde su publicación, y las respectivas fases de oposición en un año, salvo causa justificada")],
  73: [("no inferior en más de dos niveles al de su grado personal en el mismo municipio", "RD364", "a58",
        "serán adscritos provisionalmente a un puesto de trabajo correspondiente a su Cuerpo o Escala no inferior en más de dos niveles al de su grado personal en el mismo municipio")],
  74: [("siempre que se obtenga con carácter definitivo dicho puesto u otro de igual o superior nivel", "RD364", "a70",
        "el tiempo prestado en comisión de servicios será computable para consolidar el grado correspondiente al puesto desempeñado siempre que se obtenga con carácter definitivo dicho puesto u otro de igual o superior nivel")],
  75: [("treinta por ciento", "RDL6", "Artículo 108", "La oferta de empleo público incluirá un porcentaje no inferior al treinta por ciento de las plazas de acceso libre para promoción interna")],
  76: [("Diez días naturales", "RDL6", "Artículo 127", "El plazo máximo de presentación de solicitudes será de diez días naturales desde la publicación de la convocatoria")],
  78: [("Un 30 por 100", "L53", "aseptimo", "– Un 30 por 100, para los funcionarios del grupo A o personal de nivel equivalente.")],
  79: [("un mes en territorio nacional y de tres en el extranjero", "RD462", "a5", "no durará más de un mes en territorio nacional y de tres en el extranjero")],
  80: [("En el día de salida se podrán percibir gastos de alojamiento pero no gastos de manutención", "RD462", "a12",
        "a) En el día de salida se podrán percibir gastos de alojamiento pero no gastos de manutención, salvo que la hora fijada para iniciar la comisión sea anterior a las catorce horas")],
  81: [("Oposición, concurso-oposición o concurso de valoración de méritos", "TREBEP", "Artículo 61",
        "Los sistemas selectivos de personal laboral fijo serán los de oposición, concurso-oposición, con las características establecidas en el apartado anterior, o concurso de valoración de méritos")],
  82: [("presta servicios en el exterior", "CONV", "a2", "a) El personal laboral que presta servicios en el exterior.")],
  83: [("Cuatro años", "TREBEP", "Artículo 42", "será de cuatro años, pudiendo ser reelegidos"),
       ("con posibilidad de reelección", "TREBEP", "Artículo 42", "pudiendo ser reelegidos")],
  84: [("La regulación del ejercicio de los derechos de los ciudadanos y de los usuarios de los servicios públicos, así como el procedimiento de formación de los actos y disposiciones administrativas", "TREBEP", "Artículo 37",
        "b) La regulación del ejercicio de los derechos de los ciudadanos y de los usuarios de los servicios públicos, así como el procedimiento de formación de los actos y disposiciones administrativas.")],
  86: [("Permiso o licencia por parto, adopción o acogimiento, tanto preadoptivo como permanente o simple", "MUF", "a18",
        "Los permisos o licencias por parto, adopción o acogimiento, tanto preadoptivo como permanente o simple, y de paternidad por el nacimiento, acogimiento o adopción de un hijo")],
  87: [("Instituto Nacional de la Seguridad Social", "RDL670", "a11", "corresponde al Instituto Nacional de la Seguridad Social")],
  88: [("treinta y tres por cien", "RDL6", "Artículo 113", "siempre que éstas tengan reconocido un grado de discapacidad igual o superior al treinta y tres por cien")],
  89: [("Mayoría simple", "RCD", "art79", "Los acuerdos, para ser válidos, deberán ser aprobados por la mayoría simple de los miembros presentes del órgano correspondiente")],
  90: [("organismos de la administración central", "LOEP", "a2", "a) Administración central, que comprende el Estado y los organismos de la administración central."),
       ("Comunidades Autónomas", "LOEP", "a2", "b) Comunidades Autónomas."),
       ("Corporaciones Locales", "LOEP", "a2", "c) Corporaciones Locales."),
       ("Administraciones de Seguridad Social", "LOEP", "a2", "d) Administraciones de Seguridad Social.")],
  92: [(None, "CE", "a134", "incluirán la totalidad de los gastos e ingresos del sector público estatal")],
  93: [("Treinta días", "L15_2014", "a22", "El Tribunal de Cuentas emitirá su informe en el plazo improrrogable de treinta días"),
       ("quince días", "L15_2014", "a22", "Si en la orden de remisión se hiciere constar la urgencia del informe, el plazo será de quince días")],
  94: [("auditorías u otras técnicas de control", "RD2188", "a35", "El control financiero se ejercerá mediante auditorías u otras técnicas de control")],
  95: [("Documento de desglose", "ODOC", "sexto", "b) Documento de desglose: Se utilizará en las operaciones de desglose de las aplicaciones presupuestarias.")],
  98: [("Retribuciones diferidas", "TREBEP", "Artículo 29", "tendrán a todos los efectos la consideración de retribución diferida")],
  99: [("que no tendrá carácter sancionador", "TREBEP", "Artículo 30",
        "Sin perjuicio de la sanción disciplinaria que pueda corresponder, la parte de jornada no realizada dará lugar a la deducción proporcional de haberes, que no tendrá carácter sancionador")],
  101: [("Conferencia Sectorial de Inmigración", "LOEX", "Artículo 68",
         "La Conferencia Sectorial de Inmigración es el órgano a través del cual se asegurará la adecuada coordinación de las actuaciones que desarrollen las Administraciones Públicas en materia de inmigración")],
  102: [("es el sistema de información para la notificación electrónica", "RD203", "a4-6", "La Dirección Electrónica Habilitada única es el sistema de información para la notificación electrónica")],
  104: [("se acumularán al cupo del cinco por ciento de la oferta siguiente, con un límite máximo del 10 por ciento", "RD2271", "a3",
         "Si las plazas reservadas y que han sido cubiertas por las personas con discapacidad no alcanzaran la tasa del tres por ciento de las plazas convocadas, las plazas no cubiertas se acumularán al cupo del cinco por ciento de la oferta siguiente, con un límite máximo del 10 por ciento")],
  105: [("desde el 24 de diciembre hasta el 6 de enero del año siguiente, ambos inclusive", "LOPJ", "acientoochentaytres",
         "así como todos los días desde el 24 de diciembre hasta el 6 de enero del año siguiente, ambos inclusive, para todas las actuaciones judiciales, excepto las que se declaren urgentes por las leyes procesales")],
}

# Preguntas en negativo («NO es…», «INCORRECTA»): los tres distractores están
# literales en la norma y la opción correcta no.
NO = {
  9:  ([("a", "Reglamento del Congreso", "LOTC", "aveintisiete", "d) Los Reglamentos de las Cámaras y de las Cortes Generales."),
        ("b", "Tratado", "LOTC", "aveintisiete", "c) Los Tratados Internacionales."),
        ("c", "Estatuto de Autonomía", "LOTC", "aveintisiete", "a) Los Estatutos de Autonomía y las demás Leyes orgánicas.")],
       ("Ordenanza fiscal", "LOTC", "aveintisiete")),
  11: ([("a", "Regente o Regentes al hacerse cargo de sus funciones, así como el de fidelidad al Rey", "CE", "a61",
         "y el Regente o Regentes al hacerse cargo de sus funciones, prestarán el mismo juramento, así como el de fidelidad al Rey"),
        ("b", "El Rey, al ser proclamado ante las Cortes Generales", "CE", "a61", "El Rey, al ser proclamado ante las Cortes Generales, prestará juramento"),
        ("c", "El Príncipe heredero, al alcanzar la mayoría de edad", "CE", "a61", "El Príncipe heredero, al alcanzar la mayoría de edad")],
       ("testamento", "CE", "a61")),
  37: ([("a", "comportamiento de los precios sostenible", "PROT13", "Artículo 1", "deberán tener un comportamiento de precios sostenible"),
        ("b", "déficit excesivo", "PROT13", "Artículo 2", "relativa a la existencia de un déficit excesivo en dicho Estado miembro"),
        ("d", "durante al menos dos años", "PROT13", "Artículo 3", "durante por lo menos los dos años anteriores al examen")],
       ("tres puntos porcentuales", "PROT13", "Artículo 4")),
  77: ([("a", "Excedencia", "TREBEP", "Artículo 85", "d) Excedencia."),
        ("c", "Servicios especiales", "TREBEP", "Artículo 85", "b) Servicios especiales."),
        ("d", "Servicio activo", "TREBEP", "Artículo 85", "a) Servicio activo.")],
       ("Comisión de servicios", "TREBEP", "Artículo 85")),
  103: ([("a", "Niveles o estándares de calidad que se ofrecen", "RD951", "a9", "1.º Niveles o estándares de calidad que se ofrecen"),
         ("b", "Medidas que aseguren la igualdad de género", "RD951", "a9", "2.º Medidas que aseguren la igualdad de género"),
         ("d", "Indicadores utilizados para la evaluación de la calidad", "RD951", "a9", "4.º Indicadores utilizados para la evaluación de la calidad")],
        ("análisis de la demanda", "RD951", "a9")),
}

# Preguntas sin texto legal (motivo exacto). Toda pregunta no anulada está en LEY o aquí.
SIN_LEY = {
  2:  "Recuento de la estructura de la CE (4 disposiciones adicionales, 9 transitorias, 1 derogatoria y 1 final): no es un precepto; "
      "los bloques del texto consolidado (CE BOE-A-1978-31229) confirman ese recuento, pero ningún artículo lo dice literalmente.",
  31: "Dato histórico (Tratado de Fusión de los ejecutivos, firmado en Bruselas el 8-4-1965 y en vigor el 1-7-1967): "
      "el Tratado de Fusión no está en las fuentes descargadas (derogado por el Tratado de Ámsterdam); falta la fuente: pendiente de que el usuario la aporte.",
  33: "Dato de actualidad (la presidenta del Parlamento Europeo no es Ursula von der Leyen, presidenta de la Comisión) y "
      "Reglamento interno del Parlamento Europeo no disponible en las fuentes: sin texto legal.",
  39: "Dato de un balance del Ministerio de Inclusión, Seguridad Social y Migraciones (web/nota de prensa), no de una norma.",
  44: "Concepto doctrinal sobre la financiación de la Seguridad Social (función redistribuidora de los tributos, carácter finalista): "
      "no está literal en la LGSS.",
  53: "Dato de un plan (plan conjunto plurianual en materia de violencia contra las mujeres 2023-2027, acuerdo de la Conferencia Sectorial de Igualdad), no de una norma publicada en las fuentes.",
  91: "Definición de los programas finalistas de la clasificación por programas: está en la Orden anual de elaboración de los PGE, no disponible en las fuentes; pendiente de que el usuario la aporte.",
  97: "La LGP no enumera literalmente las fuentes de ingreso de las opciones (impuestos directos, cotizaciones, multas); la respuesta (los préstamos entre entidades privadas no son ingreso público) "
      "es de razonamiento, no de un precepto.",
  100: "Resolución de 25 de mayo de 2010, de la Secretaría de Estado de Hacienda y Presupuestos (anexo XV): no está en el texto consolidado del BOE ni en las fuentes; pendiente de que el usuario la aporte.",
}

# Tema del programa (oposicion.html, TEMAS_PROGRAMA): solo si es seguro.
TEMA = {1:"I.1",2:"I.1",3:"I.1",4:"I.2",5:"I.2",6:"I.2",7:"I.3",8:"I.3",9:"I.3",10:"I.4",11:"I.4",12:"I.5",13:"I.5",14:"I.5",15:"I.6",16:"I.6",17:"I.6",
  18:"I.7",19:"I.7",20:None,21:"I.9",22:"I.9",23:None,24:"I.10",25:"I.11",26:"I.11",27:"I.11",28:"II.1",29:"II.1",30:"II.1",31:"II.1",32:"II.2",33:"II.3",
  34:None,35:"II.5",36:None,37:"II.6",38:"III.1",39:"III.6",40:"III.3",41:"III.2",42:"III.3",43:"III.3",44:"III.4",45:"III.5",46:"III.6",47:None,48:"III.7",
  49:"III.8",50:"III.8",51:"III.9",52:"III.9",53:"III.9",54:"IV.6",55:"IV.6",56:"IV.5",57:"IV.6",58:"IV.8",59:"IV.9",60:"IV.9",61:"IV.10",62:"IV.11",
  63:"IV.13",64:"IV.12",65:"I.10",66:"V.4",67:"V.1",68:"V.2",69:None,70:"V.3",71:"V.4",72:"V.3",73:"V.4",74:"V.4",75:"V.3",76:"V.4",77:"V.5",78:"V.5",
  79:"V.6",80:"V.6",81:"V.3",82:"V.7",83:"V.8",84:"V.8",85:"V.9",86:"V.9",87:"V.9",88:"V.10",89:"VI.2",90:"VI.1",91:"VI.2",92:"VI.1",93:"VI.4",94:"VI.4",
  95:"VI.5",96:"VI.6",97:"VI.7",98:"V.6",99:"V.6",100:"VI.8",101:"III.6",102:"III.1",103:"III.1",104:"V.10",105:"I.7"}
assert sorted(TEMA) == list(range(1, 106))
# 96: RETENIDA. La plantilla definitiva da la b («10% del total de créditos del capítulo destinado a
# gastos corrientes en bienes y servicios»), pero el art. 78.3 LGP fija el límite general en el 7 % del
# capítulo 2 y el 10 % lo calcula sobre los créditos del artículo 23 y solo para el programa 222A de
# Interior. Revisado a mano sobre el texto vigente. Se muestra el texto legal y la pregunta queda fuera
# del repaso y del examen hasta que el usuario decida (CLAUDE.md: nunca publicar una respuesta que
# contradiga la ley).
RETENIDA = {96: "la plantilla oficial da la b), pero el art. 78.3 de la Ley General Presupuestaria fija el límite general en el 7 % del capítulo 2 y el 10 % lo calcula sobre los créditos del artículo 23 y solo para el programa 222A del Ministerio del Interior; ninguna opción reproduce la ley."}
# 85: el art. tercero del RD 466/2026 recoge literal el título original del RD 577/1997 (el de la pregunta) y lo sustituye.
LEY[85] = [("RD466_2026", "at", [0, 1, 2, 3], "Real Decreto 466/2026 · artículo tercero (modificación del Real Decreto 577/1997)", ["Real Decreto 577/1997, de 18 de abril, por el que se establece la estructura de los órganos de gobierno, administración y representación de la Mutualidad General de Funcionarios Civiles del Estado"])]
SI[85] = [("Real Decreto 577/1997", "RD466_2026", "at", "Real Decreto 577/1997, de 18 de abril, por el que se establece la estructura de los órganos de gobierno, administración y representación de la Mutualidad General de Funcionarios Civiles del Estado")]
LEY[96] = [("LGP", "Artículo 78", [4, 5, 6], "artículo 78.3", ["el siete por ciento del total de créditos del capítulo destinado a gastos corrientes en bienes y servicios", "hasta un máximo del 10 por ciento de los créditos del artículo 23", "del programa 222A, \"Seguridad ciudadana\", del Ministerio del Interior"])]
assert not set(SIN_LEY) & set(LEY) and set(SIN_LEY) | set(LEY) == set(range(1, 106)), "LEY + SIN_LEY deben cubrir las 105"
