"""Catalogo de alimentos del plan de alimentacion complementaria de Pablo.

Cada alimento lleva:
  n      nombre de Colombia, con el de España entre parentesis si cambia
  id     ficha del libro en la app (LIBRO), o None si no la tiene
  cat    prot | har | ver | fru | gra   (proteina, harina/farinaceo, verdura, fruta, grasa)
  al     grupo de alergeno (o None); "ya" si es de un grupo ya introducido
  sec    seccion de la lista de la compra
  blw    {edad_min: texto}  forma de darlo en la mano (7 = de 7 a 8 meses,
         9 = desde 9 meses, 12 = desde 12 meses; cada banda hereda la anterior)
  cuch   {edad_min: texto}  forma de darlo a cuchara

Las presentaciones BLW siguen las fichas de la app (receta.trozos), que ya
estan revisadas por seguridad, y la regla de la AAP (2010) sobre alimentos
redondos y firmes hasta los 4 años. El "se aplasta entre pulgar e indice" es
la prueba de blandura habitual en BLW: practica habitual, no guia oficial.
"""

BLANDO = "que se aplaste entre tu pulgar y tu índice"

def F(n, id, cat, sec, blw, cuch, al=None, nota=None):
    return dict(n=n, id=id, cat=cat, sec=sec, blw=blw, cuch=cuch, al=al, nota=nota)

ALIMENTOS = {
    # ---------------- ya introducidos ----------------
    "aguacate": F("Aguacate", "aguacate", "gra", "Frutas y verduras",
        {7: "Bastón del grosor de un dedo adulto, maduro, con un extremo asomando del puño. Resbala: puedes rebozarlo en avena molida cuando la avena ya esté introducida",
         9: "Bastón o dados blandos del tamaño de un garbanzo para la pinza"},
        {7: "Chafado con el tenedor, solo o mezclado con la fruta o el puré"},
        nota="Cuenta como grasa del plato, no como fruta."),
    "pollo": F("Pollo (muslo)", "pollo_e_higado", "prot", "Carnicería",
        {7: "Tira de muslo cocido cortada a favor de la fibra, del tamaño de un dedo, o hamburguesita blanda que se deshaga al apretarla",
         9: "Desmenuzado en hebras cortas o hamburguesita en trozos para la pinza"},
        {7: "Desmenuzado muy fino y chafado con el caldo de cocción hasta que no quede arenoso",
         9: "Desmenuzado fino, mezclado con la verdura chafada"}),
    "ahuyama": F("Ahuyama (calabaza)", "calabaza", "ver", "Frutas y verduras",
        {7: f"Bastón asado o al vapor del grosor de un dedo, {BLANDO}", 9: "Bastón o dados blandos de ~1 cm para la pinza"},
        {7: "Chafada con tenedor, con grumos", 9: "Chafada gruesa o en dados blandos"}),
    "papa": F("Papa (patata)", "papa", "har", "Frutas y verduras",
        {7: f"Bastón cocido del grosor de un dedo, con piel fuera, {BLANDO}", 9: "Bastón o dados blandos de ~1 cm"},
        {7: "Chafada con tenedor (no con batidora: queda pegajosa), aflojada con el agua de cocción"}),
    "trigo_pasta": F("Pasta de trigo (fusilli o conchitas)", "pasta_de_trigo", "har", "Despensa",
        {7: "Fusilli o conchitas muy cocidos (2-3 min más que el paquete), enteros, para cogerlos con la mano",
         9: "Fusilli o macarrones cortos muy cocidos, para la pinza"},
        {7: "Cocida de más y chafada con la verdura"}, al="ya"),
    "pan": F("Pan sin sal (trigo)", "pan_de_caja", "har", "Panadería",
        {7: "Tira de pan sin sal tostado ligeramente, del ancho de un dedo, sin corteza",
         9: "Tira o cuadraditos de pan sin sal tostado"},
        {7: "Miga remojada en la fórmula o en el puré"}, al="ya"),
    "calabacin": F("Calabacín (zucchini)", "calabacita", "ver", "Frutas y verduras",
        {7: f"Bastón al vapor con piel, {BLANDO}", 9: "Bastón o media luna blanda"},
        {7: "Chafado con tenedor"}),
    "banano": F("Banano (plátano)", "platano", "fru", "Frutas y verduras",
        {7: "Medio banano maduro pelado: quita la piel solo de la mitad de arriba y deja la de abajo como asa; o bastones a lo largo",
         9: "Rodajas cortadas a lo largo (en cuartos), nunca rodajas redondas enteras"},
        {7: "Chafado con tenedor"}),
    "huevo": F("Huevo", "huevo_entero", "prot", "Huevos y lácteos",
        {7: "Tira de tortilla francesa bien cuajada del tamaño de un dedo, o gajo de huevo duro (10 min desde que hierve)",
         9: "Tiras o dados de tortilla bien cuajada, o huevo duro en cuartos"},
        {7: "Huevo duro chafado con el puré o con la verdura; nunca crudo ni poco hecho"}, al="ya"),
    "zanahoria": F("Zanahoria", "zanahoria", "ver", "Frutas y verduras",
        {7: f"Bastón COCIDO hasta que se aplaste con el dedo. Cruda en palito, nunca (hasta los 4 años)", 9: "Bastón cocido o dados cocidos blandos"},
        {7: "Cocida y chafada"}),
    "pera": F("Pera", "pera", "fru", "Frutas y verduras",
        {7: "Muy madura: gajo pelado del grosor de un dedo. Si aún está firme, gajos al vapor 3-5 min",
         9: "Gajos o dados blandos de pera madura o cocida"},
        {7: "Rallada o chafada si está muy madura; si no, cocida y chafada"}),
    "manzana": F("Manzana", "manzana", "fru", "Frutas y verduras",
        {7: "Siempre COCIDA: gajo pelado al vapor 5-8 min hasta que se aplaste. Cruda en trozo, nunca (hasta los 4 años)",
         9: "Gajos o dados cocidos; cruda solo rallada muy fina"},
        {7: "Compota casera: cocida y chafada, sin azúcar"}),
    "aove": F("Aceite de oliva virgen extra", "aceite_de_oliva", "gra", "Despensa",
        {7: "Un hilo por encima de los bastones"}, {7: "1 cucharadita en crudo, mezclada con el plato"}),
    # ---------------- nuevos hasta diciembre ----------------
    "res": F("Carne de res (ternera)", "carne_de_res", "prot", "Carnicería",
        {7: "Hamburguesita blanda o tira de carne guisada muy tierna cortada a favor de la fibra. Nunca un taco de carne",
         9: "Hamburguesita en trozos o carne guisada desmenuzada"},
        {7: "Molida, guisada y chafada con su caldo"}),
    "pescado_blanco": F("Tilapia (pescado blanco)", "merluza", "prot", "Pescadería",
        {7: "Lasca gruesa sin espinas (repásala dos veces con los dedos), que se deshace en la boca",
         9: "Lascas desmenuzadas para la pinza"},
        {7: "Desmenuzada y chafada con la verdura"}, al="pescado"),
    "papaya": F("Papaya", "papaya", "fru", "Frutas y verduras",
        {7: "Bastón de papaya muy madura sin piel ni semillas, del grosor de un dedo", 9: "Bastón o dados blandos"},
        {7: "Chafada con tenedor (no hace falta cocerla)"}),
    "avena": F("Avena en hojuelas", "avena", "har", "Despensa",
        {7: "Precargada en cuchara para que la coja él (espesa), o en tortitas de avena y banano",
         9: "Precargada en cuchara o en tortitas cortadas en tiras"},
        {7: "Cocida con fórmula, espesa, a cuchara"}),
    "cacahuete": F("Crema de maní (cacahuete) 100 %", "cacahuete", "gra", "Despensa",
        {7: "En capa finísima untada sobre una tira de pan o de tortita. NUNCA el maní entero ni a cucharadas (es pegajosa)"},
        {7: "Diluida en la avena o en la fruta chafada hasta que no quede pegote"}, al="cacahuete"),
    "mango": F("Mango maduro", "mango", "fru", "Frutas y verduras",
        {7: "Bastón de mango maduro; resbala: deja un trocito de piel en un extremo como asa", 9: "Bastón o dados blandos"},
        {7: "Chafado"}),
    "maiz": F("Arepa de maíz (sin sal)", "elote", "har", "Despensa",
        {7: "Tira de arepa blanda del ancho de un dedo, sin la costra dura", 9: "Tiras o cuadraditos de arepa blanda"},
        {7: "Desmigada y mezclada con el huevo o la fruta"}),
    "yogur": F("Yogur natural entero sin azúcar", "yogur_y_derivados_lacteos", "prot", "Huevos y lácteos",
        {7: "Espeso, en cuchara precargada que coge él, o para mojar un bastón de fruta"},
        {7: "A cuchara, con la fruta chafada"}, al="leche"),
    "yuca": F("Yuca", "yuca", "har", "Frutas y verduras",
        {7: f"Bastón bien cocido, sin la fibra central, {BLANDO}", 9: "Bastón o dados blandos"},
        {7: "Chafada con el agua de cocción"}),
    "habichuela": F("Habichuela (judía verde)", "ejote", "ver", "Frutas y verduras",
        {7: "Vaina entera muy cocida, blanda, abierta a lo largo si es gruesa", 9: "Trozos cortos muy cocidos"},
        {7: "Cocida y chafada (pásala por colador si quedan hebras)"}),
    "tahini": F("Tahini (ajonjolí, sésamo)", "ajonjoli", "gra", "Despensa",
        {7: "En capa finísima sobre un bastón de ahuyama o de pan. Nunca a cucharadas ni la semilla entera"},
        {7: "½ cucharadita diluida en el puré de verdura"}, al="sesamo"),
    "lenteja": F("Lenteja", "lenteja", "prot", "Despensa",
        {7: "Chafada y mezclada con papa en hamburguesita blanda", 12: "Hamburguesita, o lentejas enteras muy cocidas y aplastadas un poco con el dedo"},
        {7: "Cocida muy tierna y chafada (o pasada por colador para quitar pieles)"}),
    "salmon": F("Salmón (o trucha)", "salmon", "prot", "Pescadería",
        {7: "Lasca gruesa sin espinas ni piel, al horno", 9: "Lascas para la pinza"},
        {7: "Desmenuzado y chafado con la verdura"}, al="ya:pescado",
        nota="Otra especie de pescado: se trata como nuevo por práctica habitual."),
    "pitahaya": F("Pitahaya amarilla", "pitahaya", "fru", "Frutas y verduras",
        {7: "Pulpa madura en bastones o trozos blandos (las semillitas negras se comen)", 9: "Dados de pulpa"},
        {7: "Pulpa chafada a cuchara"},
        nota="La amarilla tiene fama de laxante (conocimiento popular, sin guía oficial): empieza con poca cantidad. Si alguna vez es roja, puede teñir de rojo las heces y la orina: no es sangre."),
    "almendra": F("Crema de almendra 100 %", "oleaginosas", "gra", "Despensa",
        {7: "En capa finísima sobre tira de pan o tortita. NUNCA la almendra entera (hasta los 4 años)"},
        {7: "½ cucharadita diluida en la avena o el yogur"}, al="almendra"),
    "brocoli": F("Brócoli", "brocoli", "ver", "Frutas y verduras",
        {7: "Arbolito al vapor con el tallo como mango, muy blando", 9: "Ramitas pequeñas muy blandas"},
        {7: "Cocido y chafado"}),
    "maranon": F("Crema de marañón (anacardo) 100 %", "anacardo_pistacho", "gra", "Despensa",
        {7: "En capa finísima sobre tira de pan o tortita. Nunca entero"},
        {7: "½ cucharadita diluida en la avena o el yogur"}, al="maranon"),
    "queso": F("Queso fresco bajo en sal (cuajada)", "queso", "prot", "Huevos y lácteos",
        {7: "Tira fina de queso fresco blando", 9: "Dados blandos para la pinza"},
        {7: "Desmenuzado y mezclado con la arepa o el puré"}, al="ya:leche",
        nota="Elige el que menos sal tenga: el queso campesino suele llevar bastante."),
    "nuez": F("Nuez molida (o en crema)", "nuez_avellana", "gra", "Despensa",
        {7: "Molida muy fina, espolvoreada sobre un bastón de fruta húmedo. Nunca trozos"},
        {7: "½ cucharadita molida mezclada con la avena o el yogur"}, al="nuez"),
    "durazno": F("Durazno (melocotón)", "durazno", "fru", "Frutas y verduras",
        {7: "Gajo pelado de durazno muy maduro; si está firme, cocido al vapor 3-5 min", 9: "Gajos o dados blandos"},
        {7: "Chafado o cocido y chafado"}),
    "tofu": F("Tofu firme (soya, soja)", "tofu", "prot", "Huevos y lácteos",
        {7: "Bastón de tofu firme dorado en sartén sin sal (resbala: rebózalo en avena molida)", 9: "Dados de tofu"},
        {7: "Chafado con la verdura"}, al="soja"),
    "arroz": F("Arroz", "arroz", "har", "Despensa",
        {7: "Muy cocido y pegajoso, apretado en bolitas que pueda coger con la mano", 9: "Bolitas o arroz suelto para la pinza"},
        {7: "Muy cocido y chafado con la verdura"},
        nota="AESAN: arroz 2-3 veces por semana como mucho (arsénico)."),
    "camaron": F("Camarón (gamba)", "camaron", "prot", "Pescadería",
        {7: "Picado fino dentro de una hamburguesita o del arroz. Nunca entero (elástico: atraganta)"},
        {7: "Picado muy fino y chafado con el arroz o la verdura"}, al="crustaceo"),
    "arveja": F("Arveja (guisante)", "chicharo", "prot", "Frutas y verduras",
        {7: "Chafada sobre tira de pan o mezclada con papa en hamburguesita. Entera, no antes de 10-12 meses",
         12: "Chafada, o entera muy cocida aplastada un poco con el dedo"},
        {7: "Cocida y chafada (o pasada por colador para quitar la piel)"}),
    # ---------------- de diciembre en adelante ----------------
    "batata": F("Batata (boniato)", "camote", "har", "Frutas y verduras",
        {7: f"Bastón asado {BLANDO}", 9: "Bastón o dados blandos"}, {7: "Chafada"}),
    "avellana": F("Crema de avellana 100 % (sin cacao ni azúcar)", "avellana", "gra", "Despensa",
        {7: "En capa finísima sobre tira de pan o tortita. Nunca entera"}, {7: "½ cucharadita diluida en la avena o el yogur"}, al="avellana"),
    "coliflor": F("Coliflor", "coliflor", "ver", "Frutas y verduras",
        {7: "Arbolito al vapor muy blando con el tallo de asa", 9: "Ramitas muy blandas"}, {7: "Cocida y chafada"}),
    "garbanzo": F("Garbanzo", "garbanzo", "prot", "Despensa",
        {7: "Hummus sin sal untado en tira de pan, o hamburguesita blanda", 12: "Hamburguesita o garbanzo muy cocido aplastado"},
        {7: "Chafado o en hummus sin sal, a cuchara"}),
    "pistacho": F("Crema de pistacho 100 %", "pistacho", "gra", "Despensa",
        {7: "Capa finísima sobre tira de pan. Nunca entero"}, {7: "½ cucharadita diluida en el yogur"}, al="pistacho"),
    "pimenton": F("Pimentón (pimiento) asado", "pimiento", "ver", "Frutas y verduras",
        {9: "Tira asada y pelada, muy blanda"}, {9: "Asado, pelado y chafado"}),
    "melon": F("Melón", "melon", "fru", "Frutas y verduras",
        {9: "Bastón maduro sin cáscara (sécalo con papel: resbala) o dados"}, {9: "Chafado"}),
    "moluscos": F("Mejillón o almeja", "mejillon", "prot", "Pescadería",
        {9: "Picado fino dentro de arroz o hamburguesita. Nunca entero"}, {9: "Picado muy fino con el arroz"}, al="molusco"),
    "quinua": F("Quinua", "quinoa", "har", "Despensa",
        {9: "En bolitas o hamburguesita con verdura"}, {9: "Muy cocida, mezclada con la verdura"}),
    "cerdo": F("Cerdo (lomo)", "cerdo", "prot", "Carnicería",
        {9: "Tira fina muy cocida a favor de la fibra o albóndiga blanda"}, {9: "Desmenuzado fino con la verdura"}),
    "kiwi": F("Kiwi", "kiwi", "fru", "Frutas y verduras",
        {9: "Bastón a lo largo, pelado (nunca rodajas)"}, {9: "Chafado"}, al="kiwi",
        nota="El kiwi no está en la lista europea de 14 alérgenos, pero da alergias con frecuencia: se introduce como alérgeno por práctica habitual."),
    "tomate": F("Tomate pelado y sin semillas", "jitomate", "ver", "Frutas y verduras",
        {9: "Gajo pelado y sin semillas, o dados"}, {9: "Pelado, sin semillas y chafado"}),
    "frijol": F("Fríjol (alubia)", "frijol", "prot", "Despensa",
        {9: "Chafado en hamburguesita", 12: "Hamburguesita o fríjol muy cocido aplastado"}, {9: "Cocido, chafado y pasado por colador"}),
    "apio": F("Apio cocido", "apio", "ver", "Frutas y verduras",
        {9: "Muy picado dentro del guiso o de una hamburguesita, nunca en bastón crudo"}, {9: "Cocido y triturado con la verdura"}, al="apio"),
    "berenjena": F("Berenjena", "berenjena", "ver", "Frutas y verduras",
        {9: "Bastón asado, pelado y muy blando"}, {9: "Asada y chafada"}),
    "pavo": F("Pavo (contramuslo)", "pavo", "prot", "Carnicería",
        {9: "Tira de contramuslo cocido o albóndiga blanda"}, {9: "Desmenuzado con la verdura"}),
    "mandarina": F("Mandarina", "naranja_y_mandarina", "fru", "Frutas y verduras",
        {9: "Gajo pelado sin telilla, abierto a lo largo"}, {9: "Pulpa sin telilla chafada"}),
    "pina": F("Piña madura", "pina", "fru", "Frutas y verduras",
        {9: "Bastón grande de piña madura sin el corazón, para roer"}, {9: "Rallada fina"}),
    "puerro": F("Puerro", "puerro", "ver", "Frutas y verduras",
        {9: "Rodajas cortas cortadas a lo ancho, muy cocidas, dentro del plato"}, {9: "Cocido y triturado con la verdura"}),
    "patilla": F("Patilla (sandía)", "sandia", "fru", "Frutas y verduras",
        {9: "Bastón sin pepitas ni cáscara"}, {9: "Chafada sin pepitas"}),
    "champinon": F("Champiñón", "champinon", "ver", "Frutas y verduras",
        {9: "Láminas bien cocidas y picadas dentro del plato. Nunca el sombrero entero"}, {9: "Cocido y picado fino"}),
    "chia": F("Chía (remojada)", "chia", "gra", "Despensa",
        {10: "Siempre remojada 30 min o más y sin grumos, mezclada con fruta o avena. Nunca seca"},
        {10: "½ cucharadita remojada ≥30 min, sin grumos, en la avena o el yogur"},
        nota="Es una semilla, no cuenta como fruta."),
    "fresa": F("Fresa", "fresa", "fru", "Frutas y verduras",
        {9: "En cuartos a lo largo (nunca entera ni en rodajas)"}, {9: "Chafada"}),
    "platano_macho": F("Plátano maduro (macho)", "platano_macho", "har", "Frutas y verduras",
        {9: "Bastón cocido o asado muy blando"}, {9: "Cocido y chafado"}),
    "name": F("Ñame", "name", "har", "Frutas y verduras",
        {9: f"Bastón cocido {BLANDO}"}, {9: "Chafado"}),
    "arandano": F("Arándano", "blueberry", "fru", "Frutas y verduras",
        {9: "Aplastado entre los dedos o en cuartos a lo largo; nunca entero hasta los 4 años"}, {9: "Chafado"}),
    "guayaba": F("Guayaba (colada)", "guayaba", "fru", "Frutas y verduras",
        {9: "Solo la pulpa colada, sin pepitas, en cuchara precargada"}, {9: "Pulpa colada sin pepitas"}),
    "repollo": F("Repollo (col) cocido", "repollo", "ver", "Frutas y verduras",
        {9: "Tira de hoja cocida, blanda y corta"}, {9: "Cocido y picado fino"}),
    "arracacha": F("Arracacha", "arracacha", "har", "Frutas y verduras",
        {9: f"Bastón cocido {BLANDO}"}, {9: "Chafada"}),
    "pepino": F("Pepino cohombro", "pepino", "ver", "Frutas y verduras",
        {11: "Bastón pelado y sin semillas, para roer. Nunca en rodajas"}, {11: "Rallado fino"}),
    "uva": F("Uva", "uva", "fru", "Frutas y verduras",
        {9: "En cuartos a lo largo, nunca entera ni en rodajas (hasta los 4 años)"}, {9: "Pelada y chafada"}),
    "granadilla": F("Granadilla (colada)", "granadilla", "fru", "Frutas y verduras",
        {9: "Pulpa colada sin semillas, en cuchara precargada"}, {9: "Pulpa colada"}),
    "ciruela": F("Ciruela", "ciruela", "fru", "Frutas y verduras",
        {9: "Pelada, sin hueso, en gajos blandos"}, {9: "Chafada"}),
    "breva": F("Breva (higo)", "higo", "fru", "Frutas y verduras",
        {9: "Mitad de breva madura pelada"}, {9: "Chafada"}),
    "atun": F("Atún en lata al natural (claro)", "atun", "prot", "Despensa",
        {10: "Desmenuzado y mezclado con papa en pastelito blando"}, {10: "Desmenuzado con la papa"}, al="ya:pescado",
        nota="Ocasional. Nunca atún rojo (AESAN)."),
    "cebolla": F("Cebolla", "cebolla", "ver", "Frutas y verduras",
        {9: "Muy pochada y picada dentro del guiso"}, {9: "Pochada y triturada con la verdura"}),
    "mostaza": F("Mostaza suave", "mostaza", "gra", "Despensa",
        {12: "Una punta de cuchillo untada sobre un trozo, nunca aparte"}, {12: "Una punta de cuchillo en el puré"}, al="mostaza"),
    "espinaca": F("Espinaca cocida", "espinaca", "ver", "Frutas y verduras",
        {12: "Muy picada dentro de una tortilla o hamburguesita"}, {12: "Cocida y picada en el puré"},
        nota="AESAN: de 1 a 3 años, máximo 45 g/día de hoja verde; no en infecciones gastrointestinales."),
    "acelga": F("Acelga cocida", "acelga", "ver", "Frutas y verduras",
        {12: "Penca cocida muy blanda en tiras cortas, u hoja picada en tortilla"}, {12: "Cocida y picada en el puré"},
        nota="AESAN: de 1 a 3 años, máximo 45 g/día de hoja verde."),
    "lulo": F("Lulo (colado)", "lulo", "fru", "Frutas y verduras",
        {9: "Pulpa colada sin semillas, en cuchara precargada o con el yogur"}, {9: "Pulpa colada"}),
    "guanabana": F("Guanábana (colada)", "guanabana", "fru", "Frutas y verduras",
        {9: "Pulpa sin pepas en cuchara precargada; las pepas, nunca"}, {9: "Pulpa sin pepas, chafada"}),
    "agua": F("Agua", None, "agua", "", {7: "En vaso abierto"}, {7: "En vaso abierto"}),
}

ALERGENO_TXT = {"pescado": "pescado", "cacahuete": "cacahuete (maní)", "leche": "leche de vaca",
    "sesamo": "sésamo (ajonjolí)", "almendra": "almendra", "maranon": "marañón (anacardo)",
    "nuez": "nuez", "soja": "soja", "crustaceo": "crustáceos", "avellana": "avellana",
    "pistacho": "pistacho", "molusco": "moluscos", "kiwi": "kiwi", "apio": "apio", "mostaza": "mostaza",
    "huevo": "huevo", "gluten": "gluten (trigo)"}


def formato(k, meses, tipo):
    """Texto de la banda de edad que toca (la mas alta <= meses)."""
    tabla = ALIMENTOS[k]["blw" if tipo == "blw" else "cuch"]
    bandas = sorted(b for b in tabla if b <= meses)
    if not bandas:
        return None
    return tabla[bandas[-1]]


def edad_minima(k):
    return min(min(ALIMENTOS[k]["blw"]), min(ALIMENTOS[k]["cuch"]))
