"""Recetario del plan. Cantidades orientativas: lo que se ofrece, no lo que
tiene que comerse (la AEP pide respetar sus señales de hambre y saciedad).

Cada receta:
  titulo, rinde (raciones), ing [(producto, cantidad, unidad, seccion)],
  pasos [...], blw, cuchara, requiere {alimentos}, conserva {nevera, congelar, recalentar},
  batch: True si se puede cocinar en la sesion (aguanta 48 h en nevera o se congela),
  congela: True si aguanta congelada.

Plazos: nevera maximo 48 h (pauta indicada por la familia, AEPap); congelado
1 mes (practica habitual: no hay plazo oficial). Descongelar en nevera, no
recongelar, recalentar a fondo una sola vez y dejar templar.
"""

NEVERA = "Nevera: hasta 48 h en recipiente cerrado (AEPap, según la pauta familiar)."
CONGELA = "Congelar el mismo día en porciones individuales (cubitera o bolsita con fecha), hasta 1 mes (práctica habitual). Descongelar en la nevera la noche anterior; no recongelar."
NO_CONGELA = "No se congela bien: mejor hacerlo el mismo día."
RECALIENTA = "Recalentar a fondo una sola vez (que humee por dentro) y dejar templar antes de dárselo."

V, C, D, P, H, PA = "Frutas y verduras", "Carnicería", "Despensa", "Pescadería", "Huevos y lácteos", "Panadería"

def R(titulo, rinde, ing, pasos, blw, cuchara, requiere, batch, congela, extra=None):
    cons = [NEVERA if batch else "Al momento: no se guarda de un día para otro.",
            CONGELA if congela else NO_CONGELA]
    if batch or congela:
        cons.append(RECALIENTA)
    return dict(titulo=titulo, rinde=rinde, ing=ing, pasos=pasos, blw=blw, cuchara=cuchara,
                requiere=set(requiere), batch=batch, congela=congela, conserva=cons, extra=extra)

RECETAS = {
    # ------------------------------ desayunos ------------------------------
    "arepa": R("Arepa de maíz casera sin sal", 6,
        [("harina de maíz blanco precocida", 150, "g", D), ("agua tibia", 180, "ml", None)],
        ["Mezcla la harina con el agua tibia poco a poco, sin sal, hasta una masa que no se pegue a las manos (si se agrieta, un poco más de agua).",
         "Reposa 5 min. Haz 6 bolitas y aplánalas a 1 cm de grosor.",
         "Cocínalas en sartén antiadherente sin aceite (o con una gota) 5-6 min por lado, a fuego medio, hasta que estén hechas por dentro.",
         "Para él, ábrela y usa la parte blanda: la costra dura se quita."],
        "Tira de arepa blanda del ancho de un dedo, sin costra.", "Desmigada y mezclada con el huevo, el queso o la fruta chafada.",
        {"maiz"}, True, True),
    "tortita-trigo": R("Tortitas (pancakes) de banano sin azúcar", 6,
        [("banano maduro", 1, "unidad", V), ("huevo", 1, "unidad", H), ("harina de trigo", 30, "g", D), ("agua o fórmula", 2, "cucharadas", None)],
        ["Chafa el banano con el tenedor y bate con el huevo.", "Añade la harina y el agua hasta una masa espesa, sin grumos. Sin azúcar ni miel.",
         "Sartén antiadherente a fuego medio-bajo: cucharadas de masa, 2-3 min por lado hasta que estén bien hechas por dentro (el huevo, siempre cuajado)."],
        "Tiras de tortita del ancho de un dedo.", "Desmigada y remojada en un poco de fórmula.",
        {"huevo", "banano", "trigo_pasta"}, True, True),
    "tortita-avena": R("Tortitas de avena y banano sin azúcar", 6,
        [("banano maduro", 1, "unidad", V), ("huevo", 1, "unidad", H), ("avena en hojuelas", 30, "g", D)],
        ["Muele la avena hasta harina (o usa hojuela fina).", "Chafa el banano, bátelo con el huevo y mézclalo con la avena. Reposa 5 min.",
         "Sartén antiadherente a fuego medio-bajo, 2-3 min por lado hasta que estén bien hechas por dentro."],
        "Tiras de tortita del ancho de un dedo.", "Desmigada y remojada en un poco de fórmula.",
        {"huevo", "banano", "avena"}, True, True),
    "tortilla-calabacin": R("Tortilla de huevo con calabacín", 1,
        [("huevo", 1, "unidad", H), ("calabacín rallado", 30, "g", V), ("aceite de oliva", 1, "cucharadita", D)],
        ["Ralla el calabacín y escúrrelo apretándolo con las manos.", "Bate el huevo y mézclalo con el calabacín, sin sal.",
         "Cuaja en sartén con unas gotas de aceite, tapada, a fuego bajo, y dale la vuelta: tiene que quedar bien cuajada por dentro, sin nada líquido."],
        "Tiras del tamaño de un dedo.", "Chafada con el tenedor y aflojada con un poco de agua.",
        {"huevo", "calabacin"}, False, False),
    "huevo-duro": R("Huevo duro", 1,
        [("huevo", 1, "unidad", H)],
        ["Cuécelo 10 minutos desde que el agua rompe a hervir, enfríalo en agua y pélalo.", "Para él: en gajos (cuartos a lo largo) o chafado con el tenedor."],
        "Gajo de huevo duro (cuarto a lo largo).", "Chafado con un poco de agua o de fórmula para que no reseque la boca.",
        {"huevo"}, False, False),
    "avena-formula": R("Avena con fórmula", 1,
        [("avena en hojuelas", 15, "g", D), ("agua", 100, "ml", None), ("fórmula preparada", 30, "ml", None)],
        ["Cuece la avena en el agua 5 minutos, removiendo, hasta que esté espesa.",
         "Fuera del fuego, añade la fórmula ya preparada como siempre (no pongas los polvos directamente en la olla) y remueve.",
         "Sin azúcar ni miel: la fruta ya endulza."],
        "Espesa, en cuchara precargada que coge él.", "A cuchara, templada.",
        {"avena"}, False, False, extra="Indicada por la pediatra."),
    "yogur-fruta": R("Yogur natural con fruta chafada", 1,
        [("yogur natural entero sin azúcar", 60, "g", H)],
        ["Yogur natural entero, sin azúcar (los 'de bebé' suelen llevarla).", "Mezcla con la fruta del desayuno chafada, o úsalo para mojar los bastones de fruta."],
        "Cuchara precargada que coge él, o para mojar el bastón de fruta.", "A cuchara.",
        {"yogur"}, False, False),
    "muffins": R("Muffins salados de verdura", 8,
        [("huevo", 2, "unidad", H), ("harina de trigo", 60, "g", D), ("calabacín", 80, "g", V), ("zanahoria", 60, "g", V),
         ("aceite de oliva", 1, "cucharada", D), ("agua o fórmula", 60, "ml", None)],
        ["Horno a 180 °C. Ralla el calabacín (escúrrelo) y la zanahoria.",
         "Bate los huevos con el aceite y el agua, añade la harina y la verdura. Sin sal. (Cuando el queso esté introducido, puedes añadir 2 cucharadas de queso fresco desmenuzado.)",
         "Reparte en 8 moldes pequeños y hornea 18-20 min, hasta que un palillo salga limpio."],
        "Medio muffin o tiras.", "Desmigado y remojado en un poco de fórmula.",
        {"huevo", "trigo_pasta", "calabacin", "zanahoria"}, True, True),
    "pan-tostado": R("Tiras de pan sin sal", 1,
        [("pan sin sal", 20, "g", PA)],
        ["Pan sin sal (pídelo en la panadería o hazlo en casa; el de molde y el de panadería normal llevan sal).", "Tuéstalo ligeramente y córtalo en tiras del ancho de un dedo, sin corteza."],
        "Tira de pan tostado.", "Miga remojada en la fórmula.",
        {"pan"}, False, True),
    "crema-fruto-seco": R("Crema de fruto seco (o tahini) diluida", 1,
        [("crema 100 % del fruto seco o tahini, sin sal ni azúcar", 0.5, "cucharadita", D)],
        ["Solo cremas cuyo único ingrediente sea el fruto seco (o el sésamo).",
         "Primer día: ½ cucharadita diluida con un poco de agua caliente o mezclada con la avena, el yogur o la fruta, hasta que no quede pegote (práctica habitual: empezar con poca cantidad).",
         "Días siguientes, igual o hasta 1 cucharadita.", "Nunca el fruto seco entero ni a cucharadas del bote: se pega al paladar."],
        "Capa finísima untada sobre una tira de pan o de tortita.", "Diluida en la avena, el yogur o la fruta.",
        set(), False, False),
    # ------------------------------ proteinas ------------------------------
    "hamb-pollo": R("Hamburguesitas de pollo y ahuyama", 8,
        [("muslo de pollo deshuesado sin piel", 200, "g", C), ("ahuyama", 100, "g", V), ("aceite de oliva", 1, "cucharada", D)],
        ["Cuece la ahuyama al vapor 15 min y cháfala.", "Pica el pollo crudo muy fino (o pídelo molido) y mézclalo con la ahuyama, sin sal.",
         "Forma 8 hamburguesitas de 2 cm de grosor y cocínalas en sartén con unas gotas de aceite, tapadas, 5-6 min por lado, o al horno 20 min a 180 °C: tienen que quedar hechas por dentro y blandas."],
        "Hamburguesita entera o en tiras del ancho de un dedo.", "Chafada con un poco de agua o caldo de verduras sin sal.",
        {"pollo", "ahuyama"}, True, True),
    "pollo-desmenuzado": R("Pollo guisado y desmenuzado", 4,
        [("muslo de pollo sin piel", 250, "g", C), ("zanahoria", 1, "unidad", V), ("aceite de oliva", 1, "cucharadita", D)],
        ["Cuece el muslo entero con la zanahoria en agua que lo cubra, sin sal ni cubito, 30-35 min a fuego suave, hasta que se deshaga.",
         "Quita piel, cartílagos y huesos y desmenúzalo a favor de la fibra. Guarda el caldo.",
         "Repártelo en raciones con un poco del caldo para que no se seque."],
        "Tiras del tamaño de un dedo cortadas a favor de la fibra, o hebras cortas desde los 9 meses.", "Desmenuzado muy fino y chafado con su caldo.",
        {"pollo", "zanahoria"}, True, True),
    "hamb-res": R("Hamburguesitas de res y papa", 8,
        [("carne de res molida magra", 200, "g", C), ("papa", 100, "g", V), ("aceite de oliva", 1, "cucharada", D)],
        ["Cuece la papa pelada 15-20 min y cháfala.", "Mezcla con la carne molida, sin sal. Forma 8 hamburguesitas de 2 cm.",
         "Cocínalas tapadas en sartén con unas gotas de aceite, 6 min por lado a fuego medio-bajo, o al horno 20 min a 180 °C, hasta que no quede nada rosado."],
        "Hamburguesita o tiras del ancho de un dedo. Nunca un taco de carne entero.", "Chafada con agua o caldo de verduras sin sal.",
        {"res", "papa"}, True, True),
    "res-guisada": R("Carne de res guisada y desmenuzada", 4,
        [("carne de res para guisar (falda o morrillo)", 250, "g", C), ("zanahoria", 1, "unidad", V), ("aceite de oliva", 1, "cucharadita", D)],
        ["Dora la pieza entera con unas gotas de aceite y cúbrela con agua con la zanahoria, sin sal.",
         "Cocina a fuego suave 1 h 30 min (olla a presión: 35 min) hasta que se deshaga.",
         "Desmenúzala a favor de la fibra y guarda el caldo."],
        "Tiras muy tiernas a favor de la fibra; nunca un taco.", "Desmenuzada fina y chafada con su caldo.",
        {"res", "zanahoria"}, True, True),
    "pescado-laminas": R("Tilapia en láminas al vapor", 2,
        [("filete de tilapia", 100, "g", P), ("aceite de oliva", 1, "cucharadita", D)],
        ["Repasa el filete con los dedos y quita todas las espinas.", "Al vapor 8-10 min (o al horno, en papillote, 12 min a 180 °C) hasta que se separe en láminas.",
         "Vuelve a repasar las láminas con los dedos antes de servir."],
        "Lasca gruesa sin espinas.", "Desmenuzada y chafada con la verdura.",
        {"pescado_blanco"}, True, True),
    "salmon-horno": R("Salmón (o trucha) al horno", 2,
        [("filete de salmón o trucha", 100, "g", P), ("aceite de oliva", 1, "cucharadita", D)],
        ["Horno a 180 °C. Quita la piel y repasa las espinas con los dedos.", "Hornea 12-15 min en papillote o tapado, sin sal, hasta que se separe en lascas.",
         "Vuelve a repasar las lascas."],
        "Lasca gruesa sin espinas ni piel.", "Desmenuzado y chafado con la verdura.",
        {"salmon"}, True, True),
    "lenteja-chafada": R("Lentejas chafadas con verdura", 6,
        [("lenteja", 100, "g", D), ("zanahoria", 1, "unidad", V), ("papa", 1, "unidad", V), ("aceite de oliva", 1, "cucharada", D)],
        ["Lava las lentejas (no hace falta remojo) y cuécelas con la zanahoria y la papa en agua sin sal 30-40 min, hasta que estén muy tiernas.",
         "Chafa todo con el tenedor (o pásalo por el colador si las pieles le molestan). Añade el aceite en crudo."],
        "Chafadas sobre una tira de pan o tortita, o en hamburguesita (ver receta).", "Chafadas a cuchara.",
        {"lenteja", "zanahoria", "papa"}, True, True),
    "hamb-lenteja": R("Hamburguesitas de lenteja", 8,
        [("lenteja cocida y escurrida", 200, "g", D), ("papa cocida", 100, "g", V), ("harina de trigo o avena", 2, "cucharadas", D)],
        ["Chafa la lenteja cocida con la papa.", "Añade la harina hasta que se pueda dar forma. Forma 8 hamburguesitas.",
         "Hornea 20 min a 180 °C o dora en sartén con unas gotas de aceite."],
        "Hamburguesita o tiras.", "Chafada a cuchara.",
        {"lenteja", "papa"}, True, True),
    "tofu-dorado": R("Bastones de tofu dorados", 2,
        [("tofu firme", 80, "g", H), ("avena molida (para rebozar)", 1, "cucharada", D)],
        ["Seca el tofu con papel y córtalo en bastones del tamaño de un dedo.", "Rebózalo en avena molida (agarra mejor) y dóralo en sartén antiadherente sin sal, 2 min por lado."],
        "Bastón de tofu.", "Chafado con la verdura.",
        {"tofu", "avena"}, False, False),
    "camaron-papa": R("Pastelitos de papa con camarón picado", 4,
        [("camarón pelado", 60, "g", P), ("papa", 200, "g", V), ("aceite de oliva", 1, "cucharadita", D)],
        ["Cuece la papa pelada 15-20 min en agua sin sal y cháfala.",
         "Cuece el camarón 3-4 min en agua sin sal hasta que esté bien hecho (opaco por dentro) y pícalo muy fino.",
         "Mezcla, forma 4 pastelitos y dóralos en sartén con unas gotas de aceite."],
        "Pastelito o tiras, con el camarón picado dentro. El camarón entero, nunca (elástico: atraganta).", "Chafado a cuchara.",
        {"camaron", "papa"}, False, False),
    "pasta-mariscos": R("Pasta con mejillón o almeja picados", 2,
        [("pasta corta", 40, "g", D), ("mejillones o almejas", 150, "g", P), ("aceite de oliva", 1, "cucharadita", D)],
        ["Cuece los mejillones/almejas al vapor hasta que se abran; los que sigan cerrados, a la basura.",
         "Saca la carne y pícala muy fina. Cuece la pasta 2-3 min más de lo que diga el paquete, sin sal, y mézclalos con el aceite."],
        "Fusilli muy cocidos con el marisco picado pegado. Nunca el marisco entero.", "Chafado a cuchara.",
        {"trigo_pasta", "moluscos"}, False, False),
    "hummus": R("Hummus sin sal", 6,
        [("garbanzo cocido", 200, "g", D), ("tahini", 1, "cucharada", D), ("aceite de oliva", 1, "cucharada", D), ("agua de la cocción", 4, "cucharadas", None)],
        ["Garbanzo cocido en casa sin sal (o de bote, muy bien enjuagado).", "Tritura con el tahini, el aceite y el agua hasta una crema lisa. Sin sal ni ajo crudo."],
        "Untado en tira de pan o en bastones de verdura cocida.", "A cuchara.",
        {"garbanzo", "tahini"}, True, True),
    "cerdo-guisado": R("Lomo de cerdo guisado y desmenuzado", 4,
        [("lomo de cerdo", 250, "g", C), ("zanahoria", 1, "unidad", V)],
        ["Cuece el lomo entero con la zanahoria en agua sin sal 40 min a fuego suave.", "Desmenúzalo fino a favor de la fibra y guarda el caldo."],
        "Tiras finas muy tiernas.", "Desmenuzado y chafado con su caldo.",
        {"cerdo", "zanahoria"}, True, True),
    "pavo-guisado": R("Pavo guisado y desmenuzado", 4,
        [("contramuslo de pavo", 250, "g", C), ("zanahoria", 1, "unidad", V)],
        ["Cuece el contramuslo entero con la zanahoria en agua sin sal 40 min.", "Quita piel y huesos y desmenúzalo."],
        "Tiras a favor de la fibra.", "Desmenuzado con su caldo.",
        {"pavo", "zanahoria"}, True, True),
    "atun-pastelito": R("Pastelitos de atún y papa", 4,
        [("atún claro en lata al natural", 60, "g", D), ("papa cocida", 150, "g", V)],
        ["Escurre bien el atún y desmenúzalo.", "Chafa la papa y mézclala con el atún. Forma 4 pastelitos y dóralos en sartén con unas gotas de aceite."],
        "Pastelito o tiras.", "Chafado.",
        {"atun", "papa"}, True, False),
    "quinua-verdura": R("Quinua con verdura", 4,
        [("quinua", 60, "g", D), ("zanahoria", 1, "unidad", V)],
        ["Lava bien la quinua (quita el amargor) y cuécela 15-18 min en el doble de agua sin sal con la zanahoria rallada.", "Debe quedar muy blanda."],
        "Bolitas apretadas o hamburguesita.", "Muy cocida y chafada.",
        {"quinua", "zanahoria"}, True, True),
    # ------------------------------ harinas ------------------------------
    "bastones-papa": R("Papa cocida en bastones", 2,
        [("papa", 150, "g", V)],
        ["Pela la papa y córtala en bastones del grosor de un dedo adulto.", "Cuécela al vapor o en agua sin sal 15-20 min, hasta que se aplaste entre tus dedos.",
         "Con un hilo de aceite de oliva en crudo."],
        "Bastón del grosor de un dedo con un extremo asomando del puño.", "Chafada con el tenedor y el agua de cocción.",
        {"papa"}, True, False),
    "bastones-yuca": R("Yuca cocida en bastones", 4,
        [("yuca", 300, "g", V)],
        ["Pela la yuca, ábrela a lo largo y quita la fibra central dura.", "Córtala en bastones y cuécela en agua sin sal 25-30 min, hasta que esté muy blanda.",
         "Escúrrela bien."],
        "Bastón blando sin fibra.", "Chafada con su agua de cocción.",
        {"yuca"}, True, True),
    "bastones-batata": R("Batata asada en bastones", 4,
        [("batata", 300, "g", V), ("aceite de oliva", 1, "cucharadita", D)],
        ["Pela y corta en bastones del grosor de un dedo.", "Hornea a 200 °C con un hilo de aceite 25-30 min, hasta que se aplasten entre tus dedos."],
        "Bastón asado blando.", "Chafada.",
        {"batata"}, True, True),
    "tuberculo-cocido": R("Tubérculo cocido en bastones (ñame, arracacha, plátano maduro)", 4,
        [("ñame, arracacha o plátano maduro", 300, "g", V)],
        ["Pela y corta en bastones del grosor de un dedo.", "Cuece en agua sin sal hasta que se aplaste entre tus dedos (20-30 min según el tubérculo)."],
        "Bastón blando.", "Chafado con el agua de cocción.",
        set(), True, True),
    "pasta-verdura": R("Pasta con verdura chafada", 1,
        [("pasta corta (fusilli, conchitas)", 20, "g", D)],
        ["Cuece la pasta en agua sin sal 2-3 min más de lo que diga el paquete.", "Escurre y mezcla con la verdura del día chafada y un hilo de aceite de oliva."],
        "Fusilli enteros muy cocidos para coger con la mano.", "Cocida de más y chafada con la verdura.",
        {"trigo_pasta"}, False, False),
    "arroz-blando": R("Arroz blando", 1,
        [("arroz", 20, "g", D)],
        ["Cuece el arroz en el triple de agua sin sal hasta que esté muy blando y pegajoso.", "AESAN: 2-3 veces por semana como mucho (arsénico); varía con otros cereales."],
        "Bolitas apretadas que pueda coger con la mano.", "Chafado con la verdura.",
        {"arroz"}, False, False),
    # ------------------------------ verduras ------------------------------
    "verduras-vapor": R("Verdura al vapor en bastones", 1,
        [("verdura del día", 60, "g", V), ("aceite de oliva", 1, "cucharadita", D)],
        ["Lava y corta en bastones del grosor de un dedo adulto (brócoli y coliflor en arbolitos con el tallo de mango).",
         "Vapor, hasta que se aplaste entre tus dedos: calabacín 6-8 min; ahuyama y zanahoria 15-20 min; habichuela 12-15 min; brócoli y coliflor 8-10 min.",
         "Añade un hilo de aceite de oliva en crudo."],
        "Bastón o arbolito blando.", "Chafada con el tenedor y un poco del agua del vapor.",
        set(), True, False),
    "ahuyama-asada": R("Ahuyama asada en bastones", 4,
        [("ahuyama", 400, "g", V), ("aceite de oliva", 1, "cucharadita", D)],
        ["Pela, quita las pepas y corta en bastones del grosor de un dedo.", "Hornea a 200 °C con un hilo de aceite 25-30 min, hasta que se aplasten entre tus dedos."],
        "Bastón asado blando.", "Chafada.",
        {"ahuyama"}, True, True),
    "pure-verduras": R("Puré de verduras para congelar", 8,
        [("ahuyama", 300, "g", V), ("zanahoria", 2, "unidades", V), ("calabacín", 1, "unidad", V), ("aceite de oliva", 2, "cucharadas", D)],
        ["Pela y trocea. Cuece al vapor 15-20 min.", "Chafa (con grumos, a esta edad ya no liso) y reparte en cubiteras.",
         "El aceite, en crudo al servir."],
        "No es para la mano: es la versión a cuchara del día.", "A cuchara, con grumos.",
        {"ahuyama", "zanahoria", "calabacin"}, True, True),
    "arveja-chafada": R("Arveja chafada", 4,
        [("arveja (guisante) desgranada o congelada", 150, "g", V)],
        ["Cuece la arveja en agua sin sal 12-15 min, hasta que esté muy blanda.", "Cháfala (o pásala por el colador para quitar la piel)."],
        "Chafada sobre tira de pan o en hamburguesita con papa. Entera, no antes de los 10-12 meses.", "A cuchara.",
        {"arveja"}, True, True),
    "frijol-chafado": R("Fríjol chafado", 6,
        [("fríjol seco", 100, "g", D), ("zanahoria", 1, "unidad", V)],
        ["Remoja el fríjol 12 h y tira el agua.", "Cuécelo con la zanahoria en agua nueva sin sal hasta que esté muy tierno (olla a presión 25-30 min; olla normal 1 h 30 min o más).",
         "Chafa y pasa por el colador para quitar las pieles."],
        "Chafado sobre tira de pan o en hamburguesita con papa (entero, desde los 12 meses, aplastado).", "Chafado y colado, a cuchara.",
        {"frijol", "zanahoria"}, True, True),
    "verdura-asada": R("Verdura asada (pimentón, berenjena)", 2,
        [("pimentón o berenjena", 200, "g", V), ("aceite de oliva", 1, "cucharadita", D)],
        ["Pimentón: ásalo entero a 200 °C 30-35 min, déjalo sudar tapado y pélalo; quita semillas.",
         "Berenjena: en bastones con piel, 25-30 min a 200 °C; pélala para él.", "Tiene que quedar muy blanda."],
        "Tira asada y pelada, muy blanda.", "Chafada.",
        set(), True, False),
    "verdura-en-guiso": R("Verdura picada (apio, puerro, cebolla, champiñón, hoja verde)", 1,
        [("verdura del día", 30, "g", V)],
        ["Pícala muy fina y cuécela aparte, al vapor o rehogada con unas gotas de aceite, hasta que esté muy blanda (apio sin hebras; champiñón en láminas bien cocidas y luego picado).",
         "Mézclala al servir con la proteína, la harina o el puré; o cuájala dentro de una tortilla.",
         "Hoja verde (espinaca, acelga): solo desde los 12 meses y como mucho 45 g al día (AESAN); no si tiene una infección intestinal."],
        "No va suelta: picada y mezclada con la proteína o la harina (por ejemplo, pegada a la hamburguesita o dentro de las bolitas).", "Triturada con el resto del plato.",
        set(), True, True),
    "verdura-cruda": R("Verdura que se da cruda (tomate, pepino)", 1,
        [("verdura del día", 40, "g", V)],
        ["Tomate: pelado (escáldalo 30 s en agua hirviendo) y sin semillas, en gajos.", "Pepino: pelado y sin semillas, en bastón grande para roer. Nunca en rodajas."],
        "Gajo de tomate pelado; bastón de pepino para roer.", "Chafado o rallado fino.",
        set(), False, False),
    "mostaza-punta": R("Mostaza: una punta de cuchillo", 1,
        [("mostaza suave", 1, "punta de cuchillo", D)],
        ["Una punta de cuchillo untada en un trozo o mezclada en el puré. Nunca aparte ni a cucharadas."],
        "Untada en un trozo.", "Mezclada en el puré.",
        {"mostaza"}, False, False),
    # ------------------------------ hotel ------------------------------
    "hotel-cocina": R("Pedir en la cocina del hotel (sin sal)", 1,
        [],
        ["Pide en el restaurante del hotel, explicando que es para un bebé: cocido o al vapor, SOLO EN AGUA, sin sal, sin caldo de cubito, sin mantequilla ni crema ni queso (los lácteos aún no están introducidos), sin adobo.",
         "Si no pueden garantizar que vaya sin sal, no lo des: ese día, fruta, aguacate y huevo duro.",
         "Cortado o chafado en la mesa con tu cuchillo y tu tenedor."],
        "En bastones del tamaño de un dedo, blando.", "Chafado con el tenedor.",
        set(), False, False),
}

# Frutas y grasas sencillas: una receta corta generada desde el catalogo.
def receta_simple(k, al):
    a = al[k]
    cocer = {"manzana": "Pela, quita el corazón y cuece los gajos al vapor 5-8 min.",
             "pera": "Si está muy madura, pelada y cruda; si está firme, gajos al vapor 3-5 min.",
             "durazno": "Si está muy madura, pelada y cruda; si está firme, al vapor 3-5 min."}
    pasos = ["Lávala bien y pélala.", cocer.get(k, "Elige la pieza muy madura; no hace falta cocerla."),
             "Corta según la forma de darla de abajo, justo antes de servir."]
    if k == "aguacate":
        pasos = ["Elige uno maduro que ceda al apretar.", "Ábrelo, quita el hueso y córtalo justo antes (se oxida)."]
    return dict(titulo=f"{a['n']}: cómo prepararla" if a["cat"] == "fru" else f"{a['n']}: cómo prepararlo",
                rinde=1, ing=[(a["n"].lower(), 1, "ración", a["sec"])], pasos=pasos,
                blw=None, cuchara=None, requiere={k}, batch=False, congela=False,
                conserva=["Al momento." + (" Cocida, nevera hasta 48 h." if k in ("manzana", "pera", "durazno") else "")],
                extra=a.get("nota"))

# Cantidad por racion de lo que se compra (para la lista semanal): gramos o unidades.
POR_RACION_FRUTA = {"banano": (0.5, "unidad"), "pera": (0.5, "unidad"), "manzana": (0.5, "unidad"),
    "papaya": (80, "g"), "mango": (0.25, "unidad"), "pitahaya": (0.5, "unidad"), "durazno": (0.5, "unidad"),
    "aguacate": (0.25, "unidad"), "melon": (80, "g"), "kiwi": (0.5, "unidad"), "mandarina": (1, "unidad"),
    "pina": (60, "g"), "patilla": (80, "g"), "fresa": (3, "unidades"), "arandano": (8, "unidades"),
    "guayaba": (1, "unidad"), "uva": (5, "unidades"), "granadilla": (1, "unidad"), "ciruela": (1, "unidad"),
    "breva": (1, "unidad"), "lulo": (1, "unidad"), "guanabana": (80, "g")}
